### ISSUE TITLE
Move embedded plist data

### ISSUE THREAD

**Issue by JoeMatt** [SideStore/SideStore#101]
The thing i needed to add to info.plist. 

Make it read from a local file and or docs.

**Comment by jkcoxson** [comment]
The idea was to embed it during install through AltServer, just like the UDID.

**Comment by JoeMatt** [comment]
I see. Might still be better to use a resource file rather than editing plists.

I can code it so it looks for something in /Data, if fail, local file (or plist if it must be)

**Comment by Spidy123222** [comment]
I mean couldn't altserver just put the pairing data in folder and placed in /data

**Comment by JoeMatt** [comment]
I don't think iOS creates that file until after full install, maybe even first run?

will require investigation. Probalby easier to use an internal file since that code exists rather than writing to the sandbox dir
