### ISSUE TITLE
Add http-redirect support for repo urls

### ISSUE THREAD

**Issue by JoeMatt** [SideStore/SideStore#103]
The URL task should support http-redirect headers, 301s etc.

think this is just adding a block handler to the URL session for redirects to return "yes"

**Comment by JoeMatt** [comment]
OK, so I fixed jekyll so the home page is just the json automatically now using permalink: tag.

This is mostly useless for us now, but at least other repos could work if they http or 30x redirect

**Comment by Spidy123222** [comment]
This is no longer needed so I'm closing
