### ISSUE TITLE
Refreshing display 6 days

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#105]
When you refresh via side store it says it has 6 days left when refreshing yourself at 5-6 day marks or below when it should be 7 like AltStore has.

![image](https://user-images.githubusercontent.com/64176728/199684667-a64f0cd6-884f-4c8f-999a-e928b9ccab3d.png)

This also includes appid's

**Comment by jkcoxson** [comment]
Apple doesn’t give provisioning profiles to the minute that you requested one. If you request one near midnight, that makes sense why SideStore is predicting 6 days.
