### ISSUE TITLE
Im confused

### ISSUE THREAD

**Issue by harisshaukat96** [SideStore/SideStore#115]
Im confused because i dont speak code, if you can please make some sort of simplified tutorial for non developers

**Comment by JJTech0130** [comment]
As of right now, SideStore is in “developer beta”.
To quote the announcement:
> - You can tinker with the ipa to get it to install
> - You can debug the app with ``idevicedebug`` to provide logs
> - You don't mind losing app data or app IDs
> - You can share your experiences of SideStore with others
> - (preferable) You develop an iOS app

> We will be rolling this out to all users by the end of the month. **No installation help will be provided for users who do not meet the requirements**, but our source code and builds will always be public.

Once it is released to the public, we will simplify the installation process and provide tutorials.
