### ISSUE TITLE
I get a error when trying to build Sidestore using the instructions in readme.md

### ISSUE THREAD

**Issue by SummeryLavaRain** [SideStore/SideStore#119]
_Build input file cannot be found: '/Users/***/Documents/SideStore/Dependencies/em_proxy/em_proxy.h'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'EmotionalDamage' from project 
'AltStore')_

> SwiftDriver\ Compilation\ Requirements EmotionalDamage normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'EmotionalDamage' from project 'AltStore')
>     cd /Users/***/Documents/SideStore
>     builtin-Swift-Compilation-Requirements -- /Applications/Dev\ Tools/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -module-name EmotionalDamage -Onone -enforce-exclusivity\=checked @/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/Objects-normal/x86_64/EmotionalDamage.SwiftFileList -DDEBUG -sdk /Applications/Dev\ Tools/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk -target x86_64-apple-ios14.0-simulator -enable-bare-slash-regex -g -module-cache-path /Users/***/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Index.noindex/DataStore -swift-version 5 -I /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Products/Debug-iphonesimulator -F /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Products/Debug-iphonesimulator -parse-as-library -c -j6 -enable-batch-mode -incremental -output-file-map /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/Objects-normal/x86_64/EmotionalDamage-OutputFileMap.json -use-frontend-parseable-output -save-temps -no-color-diagnostics -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/Objects-normal/x86_64/EmotionalDamage.swiftmodule -Xcc -I/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/EmotionalDamage-generated-files.hmap -Xcc -I/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/EmotionalDamage-own-target-headers.hmap -Xcc -I/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/EmotionalDamage-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/EmotionalDamage-project-headers.hmap -Xcc -I/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Products/Debug-iphonesimulator/include -Xcc -isystem -Xcc /Users/***/Documents/SideStore/Dependencies/AltSign/Dependencies -Xcc -I/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/DerivedSources-normal/x86_64 -Xcc -I/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/DerivedSources/x86_64 -Xcc -I/Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/DerivedSources -Xcc -DDEBUG\=1 -emit-objc-header -emit-objc-header-path /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/AltStore.build/Debug-iphonesimulator/EmotionalDamage.build/Objects-normal/x86_64/EmotionalDamage-Swift.h -import-objc-header /Users/***/Documents/SideStore/Dependencies/em_proxy/em_proxy.h -pch-output-dir /Users/***/Library/Developer/Xcode/DerivedData/AltStore-erhphkamnhsnvjafidkrxadqufph/Build/Intermediates.noindex/PrecompiledHeaders -working-directory /Users/***/Documents/SideStore -experimental-emit-module-separately
>

**Comment by jkcoxson** [comment]
You have to build the Rust dependencies. This isn't specified in the readme, but cd into Dependencies/em_proxy and minimuxer and run ``cargo build --release``.

**Comment by JJTech0130** [comment]
We should probably add it to the README, lol. Should I hijack this issue for that?

**Comment by 1XxEPICDJxX1** [comment]
yeah probably

**Comment by 1XxEPICDJxX1** [comment]
> You have to build the Rust dependencies. This isn't specified in the readme, but cd into Dependencies/em_proxy and minimuxer and run `cargo build --release`.

don’t forget to download cargo too, i just found that out lol

**Comment by 1XxEPICDJxX1** [comment]
now `cargo build --release --target aarch64-apple-ios` when ran in _em_proxy_ throws this

> Compiling em_proxy v0.1.0 (/Users/***/SideStore/Dependencies/em_proxy)
> warning: found module declaration for lib.rs
>  --> src/run.rs:4:1
>   |
> 4 | mod lib;
>   | ^^^^^^^^
>   |
>   = note: `#[warn(special_module_name)]` on by default
>   = note: lib.rs is the root of this crate's library target
>   = help: to refer to it from other targets, use the library's name as the path
> 
> warning: `em_proxy` (bin "run") generated 1 warning

**Comment by xdccrlz** [comment]
Files em_proxy.h and minimuxer.h are not created in their respective directories after "cargo build --release --target aarch64-apple-ios".

**Comment by 1XxEPICDJxX1** [comment]
> Files em_proxy.h and minimuxer.h are not created in their respective directories after "cargo build --release --target aarch64-apple-ios".
> 
> 

Then how do i create them?

**Comment by jkcoxson** [comment]
Install cbindgen with cargo

**Comment by Babyyoda777** [comment]
Hi, I am also having the same issue, I installed cdbindgen but it didn't fix it :/

**Comment by SummeryLavaRain** [comment]
> Hi, I am also having the same issue, I installed cdbindgen but it didn't fix it :/

cd into Dependencies/em_proxy and minimuxer and run cdbindgen i think
