### ISSUE TITLE
Prebuilt ipa needed

### ISSUE THREAD

**Issue by PARKasd** [SideStore/SideStore#121]
I know this is still beta. But for the people using non-macOS, can you please build with newest repo? I found some old one in issues tab and that won't open in IOS 16 for me

**Comment by JJTech0130** [comment]
The CI automatically builds an IPA for every commit. You can find them on [the Actions tab](https://github.com/SideStore/SideStore/actions).

**Comment by PARKasd** [comment]
> The CI automatically builds an IPA for every commit. You can find them on [the Actions tab](https://github.com/SideStore/SideStore/actions).

With latest version, it shows Device pairing file not found. Any clues for that?
