### ISSUE TITLE
[feature request] add additional details for 36607

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#126]
When a user gets a 36607 error I feel there should be a detail to change anisette server or try again later after the initial message.

**Comment by upal212** [comment]
It could just throw in an alert saying 'Open Settings, Select SideStore and change the default values of the anisette URL to your liking' after that is fixed.

**Comment by Spidy123222** [comment]
Anisette server v3 fixes anisette issues and this is no longer needed.
