### ISSUE TITLE
App list goes missing after first refresh.

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#133]
Currently there seems to be a bug on after you install sidestore for the first time and sideloaded apps without refreshing sidestore. The list of apps disappears on the app during a refresh. Resideloading the apps sideloaded works but it's odd that behavior happens.

**Comment by jkcoxson** [comment]
This will be fixed by having a custom installer. It happens because overwriting with a new bundle ID will wipe the app’s SQLite database.

**Comment by Clayton630** [comment]
> This will be fixed by having a custom installer. It happens because overwriting with a new bundle ID will wipe the app’s SQLite database.

What do you mean by custom installer ? Should I reinstall SideStore using another app than sideserver ? If that's the case then, which app should I use to install it 
Thanks

**Comment by Spidy123222** [comment]
> > This will be fixed by having a custom installer. It happens because overwriting with a new bundle ID will wipe the app’s SQLite database.
> 
> What do you mean by custom installer ? Should I reinstall SideStore using another app than sideserver ? If that's the case then, which app should I use to install it 
> Thanks

This was before sideserver existed. This is still a issue for windows and Linux computers.

**Comment by Spidy123222** [comment]
Seems to happen still for some after first refresh.
