### ISSUE TITLE
Provision based anisette servers don't work

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#134]
Currently any anisette data server that is ran using Provision doesn't work. Ones that use Altserver Linux's container anisette server which uses windows iCloud under wine works fine.

**Comment by JJTech0130** [comment]
I’ll work on this as soon as my MacBook arrives (hopefully this afternoon 🤞)

**Comment by upal212** [comment]
> 

Until then users can run ScarletCloud in order to use it as their Anisette servers flawlessly and @JJTech0130 If possible do look at their code as it seems different.

**Comment by JJTech0130** [comment]
Well, the issue should be fixed on Provision's side. It was a bug with the HTTP library, apparently. It would occasionally just return Content-Length: 0, which broke SideStore. I'll close this issue now. Maybe in the future I'll implement something to retry failed requests, but it's not necessary if you use an up-to-date Provision server.
