### ISSUE TITLE
Change default anisette server (Sideloadly may lock accounts)

### ISSUE THREAD

**Issue by Sakooooo** [SideStore/SideStore#135]
this may seem a bit stupid at first but what i have found out is that sideloadly's anisette server has been overflowed with so many devices that ANYONE who tries to connect to it and use it WILL get locked out of their apple id RIGHT AWAY i was able to get my apple id back though PLEASE add a warning or remove sideloadly as the default server thanks

**Comment by jkcoxson** [comment]
This is not a universal issue. I used Sideloadly just fine for the months of development I did and never got my account blocked. Until there is a more stable server or the other solution is fleshed out, I don’t see this changing.

**Comment by JJTech0130** [comment]
It might not be a universal issue, but I've experienced it myself.
It's really confusing to new users, and it's *especially* confusing on builds that seem to configure the anisette server but actually hard-code it.
I think we should switch to your jkcoxson.com anisette server, it's been rock solid in my experience.

**Comment by JJTech0130** [comment]
Also, I think it's the first time you log in that gets your account locked. As long as you don't remove the "fake iMac" from your Apple ID settings and require 2FA again, it seems to be fine. You just have to try a bunch to get it to go through the first time.

**Comment by Spidy123222** [comment]
I also experienced this and it happens every time you use it now had to remove the iMac and use jkcoxsons altserver-Linux url.

**Comment by Spidy123222** [comment]
Just had my account locked a few minutes ago testing a pr if it defaults to sideloady. Well it did work but right when it errored 36607 it locked account

**Comment by Sakooooo** [comment]
Resolved: Turns out Apple has blacklisted new devices from entering Sideloadly's server
Closing issue now

**Comment by JJTech0130** [comment]
What do you mean by “new devices”?

**Comment by JJTech0130** [comment]
From an anisette perspective, Sideloadly is the device, and people have been adding it to their accounts. Now, perhaps apple has blocked Sideloadly from being added to new *accounts*, but new devices doesn’t make sense.

**Comment by Sakooooo** [comment]
> From an anisette perspective, Sideloadly is the device, and people have been adding it to their accounts. Now, perhaps apple has blocked Sideloadly from being added to new *accounts*, but new devices doesn’t make sense.

my bad should have said new accounts instead

**Comment by Spidy123222** [comment]
This isn't really how it's working. I removed the iMac it had on my account and try logging back in and it locked me out so it is for adding the fake device in some form.

**Comment by Sakooooo** [comment]
> This isn't really how it's working. I removed the iMac it had on my account and try logging back in and it locked me out so it is for adding the fake device in some form.

then it must be new accounts then

**Comment by Spidy123222** [comment]
Not really as my account isn't new it's 3 years old.

**Comment by JJTech0130** [comment]
It’s happened to my account, which is definitely really old. I’m reopening as it’s still an issue, and keeps happening to people on the Discord

**Comment by BlyatBeauty** [comment]
> 

Sorry to ping y'all without being able to help but there's a discord? Can I get an invite?

**Comment by JJTech0130** [comment]
Sure! The public mostly seems to be using the JITStreamer server for now, though we might migrate to our own soon. Here’s an invite: https://discord.gg/WsT2hcwRVy

**Comment by Sakooooo** [comment]
alright so stupid me cant send good messages
Sideloadly locks NEW accounts as in NEW accounts to the device, 
What I mean is that once sidestore begins the sideloading process, Sideloadly's anisette servers lock the device because of a blacklist apple has put.
New accounts AKA Newly added accounts to the device (NOT ACCOUNT AGE) will get locked.
Otherwise, if you have added that account already to the device, it should not get locked (In theory)
Unless sideloadly finds a way to fix this, we cannot use sideloadly's anisette server.

**Comment by JJTech0130** [comment]
Yeah, sorry about the misunderstanding, that seems to be the correct explanation. I’ll keep this issue open to track any actions we take.

**Comment by Sakooooo** [comment]
> Yeah, sorry about the misunderstanding, that seems to be the correct explanation. I’ll keep this issue open to track any actions we take.

alright sounds good to me

**Comment by JJTech0130** [comment]
I guess the real question is becoming: why does Apple lock accounts? and: how can we migitate this?
It appears that the first signs of this are appearing on @jkcoxson's anisette server: not yet locking accounts, but the unable to log in error is more frequent

**Comment by yodaluca23** [comment]
My Apple account was locked bc of this and I had to reset my password, now it’s saying theirs an “iMac” 27” signed into my account, I’m assuming it’s emulating this from my phone to sign the apps somehow… right?

**Comment by Spidy123222** [comment]
Correct and it's apple locking accounts because of the virtual Mac because it's on so many accounts that it looks suspicious.

**Comment by yodaluca23** [comment]
> Correct and it's apple locking accounts because of the virtual Mac because it's on so many accounts that it looks suspicious.

Anyway, y'all could change that to say like "SideStore Virtual iMac" as the name of it?

**Comment by JJTech0130** [comment]
Well, I think it's theoretically possible, but I don't think we currently know how to change the name of the device. We know how to change the *model* (and serial number), but not add a friendly name. Perhaps we can look into it.

**Comment by Rihcus** [comment]
> I also experienced this and it happens every time you use it now had to remove the iMac and use jkcoxsons altserver-Linux url.

Out of curiosity how did you do this? Was there an option in sidestore or did you have to recompile sidestore?

**Comment by SwagJesus** [comment]
Still nothing? I try to sign in & it hangs at the sign in screen on Sidestore..

**Comment by Spidy123222** [comment]
This has been changed but locking issue is an anisette server issue so. Will close this issue for such reason.
