### ISSUE TITLE
Collaboration offer

### ISSUE THREAD

**Issue by meniazabrali** [SideStore/SideStore#136]
Hi!

I'm ZonD80, I have a proposal for sidestore development, and I can make server side of it (in case if you will accept this), If you are interested, how can I contact you on telegram or any other messenger (I'm @ZonD80 everywhere)

Btw your email github@sidestore is not working, that's why it is here

**Comment by Nythepegasus** [comment]
If you want to collaborate, you can open PRs on this repository. If you'd like to communicate with the team, consider dropping by the [JitStreamer Discord](https://discord.gg/RgpFBX3Q3k).

**Comment by ZonD80** [comment]
I wanted to contact privately using messengers, not a discord

**Comment by Nythepegasus** [comment]
You can message me on Signal (\@Nythepegasus) and I'll relay it to the rest of the team.

**Comment by ZonD80** [comment]
There is no way to message by nickname on Signal
