### ISSUE TITLE
Error launching SIdestore

### ISSUE THREAD

**Issue by SummeryLavaRain** [SideStore/SideStore#137]
Device paring file not found. Does anyone know what this means?

**Comment by Spidy123222** [comment]
It's pairing file data to act as a different computer it's used for sideloading and jit. You can get it from jitterbug pair. Currently you can use mobiledevicepairing files if you name them .plist until solved.

**Comment by SummeryLavaRain** [comment]
> It's pairing file data to act as a different computer it's used for sideloading and jit. You can get it from jitterbug pair. Currently you can use mobiledevicepairing files if you name them .plist until solved.

After I have a paring file what do I do with it?

**Comment by jkcoxson** [comment]
Once my PR is merged, you can import it.

**Comment by jkcoxson** [comment]
Wait for my PR to be merged

**Comment by SummeryLavaRain** [comment]
> It's pairing file data to act as a different computer it's used for sideloading and jit. You can get it from jitterbug pair. Currently you can use mobiledevicepairing files if you name them .plist until solved.

I meant using this method

**Comment by jkcoxson** [comment]
I understand, wait

**Comment by jkcoxson** [comment]
When you open the app now, it will prompt for you to select the file.
