### ISSUE TITLE
Updating sidestore doesn't complete until going Home Screen.

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#144]
When doing a update it will get stuck at the end of the bar until you exit the app. This behavior usually doesn't happen with AltStore so thought was interesting behavior.

**Comment by jkcoxson** [comment]
There is no way to fix this. App installs cannot complete while the replacement is open. Note that this doesn’t affect background refreshes.

**Comment by upal212** [comment]
This does put the app into a staging mode which likely causes most of the errors for example you cannot sideload UTM and Dolphin at the same it, it will throw an 'Staging Error' and AltStore does not have this behavior as it refreshes the app's license instead of the entire app itself.
