### ISSUE TITLE
[Feature Request] Allow the app’s files to be accessible from the Files app

### ISSUE THREAD

**Issue by SummeryLavaRain** [SideStore/SideStore#145]
For example: 
Go into Files
On my phone
Open the SideStore folder

There would be SideStore’s files where you can manually put the pairing file or other stuff.

**Comment by lonkelle** [comment]
Interesting idea, what other benefits can you think of to exposing SideStore's files to the Files app?

**Comment by yodaluca23** [comment]
https://github.com/SideStore/SideStore/pull/219
