### ISSUE TITLE
SideStore ipa 0.11

### ISSUE THREAD

**Issue by SummeryLavaRain** [SideStore/SideStore#152]
“Cannot start a AFC server on the device.” Occurs when I try to refresh or download an app. The app-ids are there tho. 

I got my pairing file from another iOS device using Jitterbug, and the VPN is turned on.

**Comment by Spidy123222** [comment]
Please make a better title to specify its issue. Also if you used a different devices pairing file then that's why you have this issue. It has to be for THAT device. If it's for that device then you might have to restart the app.

**Comment by SummeryLavaRain** [comment]
> Please make a better title to specify its issue. Also if you used a different devices pairing file then that's why you have this issue. It has to be for THAT device. If it's for that device then you might have to restart the app.

Okay, I’m sorry, and thanks for your help.

**Comment by SummeryLavaRain** [comment]
> Please make a better title to specify its issue. Also if you used a different devices pairing file then that's why you have this issue. It has to be for THAT device. If it's for that device then you might have to restart the app.

It still throws the error while using the device's pairing file.
