### ISSUE TITLE
Unable to install the app from staging directory

### ISSUE THREAD

**Issue by andre1808** [SideStore/SideStore#158]
Hey. 
I’ve installed SideStore using AltServer. 
When installing an app SideStore shows “Unable to install the app from staging directory” and it won’t show on SideStore. However it is installed to my iPhone, regardless of that error.

I’ve tried the ipa from [the action](https://github.com/Spidy123222/SideStore/actions/runs/3492216908), which according to the issues section should fix this. Same error using this version. Also when trying to refresh SideStore. 
Updating SideStore throws the error as well, but once updated, refreshing works. The installation of other apps still throws the error and won’t show up. 

I’ve tried using different Anisette servers (including my own one). 

Any ideas? I will try to create a fresh Apple ID tomorrow and see if this fixes it. 

Thanks
André

**Comment by jkcoxson** [comment]
You can’t install more than 3 apps from any App Store.

**Comment by andre1808** [comment]
I’ve got none installed.
I’ve removed AltStore and uyou+.
Afterwards installed SideStore and tried to install uyou+, which unfortunately results in above error :(

**Comment by andre1808** [comment]
I’ve just created a new appleid. 
I’ve removed all sideload edits apps (AltStore and uyou+)
Afterwards I shutdown my phone and turned it back on. 

Now I’ve installed SideStore (from actions) using my new appleid, approved my account in settings -> general -> vpn
Went to settings -> SideStore and changed the server to my own one (http://anisette.xxx.xx:80 - though I don’t think the port is needed). 
now I have connected the WireGuard VPN opened SideStore and logged in. 

I tried updating SideStore and got that staging error again. The app still got updated and when I’ve launched it again the update option was gone. 
So I tried to install uyou+ again and got the same error again. YouTube still was installed and working, but it doesn’t show up in SideStore. So I suppose I won’t be able to refresh it :(

**Comment by Spidy123222** [comment]
You need to install via releases not actions. We haven't been doing that for a long while now.

**Comment by andre1808** [comment]
Just gave it another shot (same steps as above, but without creating another appleid)

This time using the Release version - I was under the impression that it’s the version SideStore gets updated to. 
But unfortunately still the same error and behaviour. 

I’m very thankful for, and impressed by, your work already and appreciate it a lot. I was already so happy to have altserver running on my rpi all at the Anisette server.  This new project however brings everything to a new level really!

**Comment by andre1808** [comment]
It's working now.
Yesterday I tried installing it from my rpi altserver over wifi. It installed fine, but I've had above mentioned errors.
Today I did the installation using Windows and a USB cable and this seems to have resolved the issue I've had.

Thus closing the issue.

**Comment by qhgary** [comment]
I encountered the same issue even when I used Windows and a USB cable. Sometimes I can succeed, but most of the time I failed with the captioned issue.

**Comment by menotuu** [comment]
sidestore 0.3.2-pr.311+875b25c
I get the „unable to install the app from the staging directory“ error too.

Log
Minimuxer https://paste.kodi.tv/ofekipohuk.kodi
Sidestore https://paste.kodi.tv/lowejawimo.kodi

iOS 16.3.1
Only Windows pc available


now I have SideStore 0.3.2-pr.321+d43fd4f installed. 
it gives me the same staging error again.
log minimuxer https://paste.kodi.tv/ubihuseseq.kodi
I installed it fresh with my own forked anisette

I dont know what to do and I dont understand what the staging error means.
I try to install the same ipa file every time (13Mb) but with a other ipa (123Mb) its same, trying not to waste app ids.

![2023-03-26 16 36 53](https://user-images.githubusercontent.com/38182429/227784321-f4409146-5e37-4321-aaba-bbb1125b2d58.png)
![2023-03-26 16 56 48](https://user-images.githubusercontent.com/38182429/227784324-e9b1a321-0181-4c43-a8ea-ccb4b3ed9e94.png)
![2023-03-26 16 56 38](https://user-images.githubusercontent.com/38182429/227784326-90e3dac5-9032-470d-9553-d99f8db8efea.png)
