### ISSUE TITLE
[BUG] apps.json JSON parser can crash

### ISSUE THREAD

**Issue by JoeMatt** [SideStore/SideStore#160]
I've been told the current code can crash the app on json errors.

That shouldn't happen and is easy enough to fix.

Notes:

Current Source.swift is a NSManaged object

Todo:

1. Create a simple Codable struct type for serializing from JSON
2. Use the struct to generate the managed type and vice-versa

**Comment by JJTech0130** [comment]
Is this related to the malformed anisette response from old Provision servers? Or another JSON parser?

**Comment by JoeMatt** [comment]
Different parser I believe, unless the code is shared, which I doubt.
This is for the apps.json feed.

**Comment by Spidy123222** [comment]
This has been fixed
