### ISSUE TITLE
Fetch UDID via em_proxy

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#162]
Currently, the UDID is injected into `info.plist` via AltStore (`ALTDeviceID`).
This means that it doesn't work if you install it with anything else without first modifying the IPA.
It seems to be the root cause of at least some of the staging issues.

Proposed solution: just have em_proxy fetch the UDID

**Comment by JJTech0130** [comment]
Would also close https://github.com/SideStore/SideStore/issues/30 as an alternative solution

**Comment by lonkelle** [comment]
I never thought of this but it's a great idea, and should be a simple change too. I'm surprised it has ties with the staging issue tho.

**Comment by JJTech0130** [comment]
It's because iOS refuses to install the app out of staging if the UDID is incorrect

**Comment by JJTech0130** [comment]
I investigated because I got the staging issue, so I pulled the IPA out of the staging folder and manually checked the signing. If fixing the UDID doesn't fix all staging issues, then I could create a program to automatically pull the IPA for further diagnosis.
