### ISSUE TITLE
Anisette Ideas

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#165]
Here are some of the ideas we've had so far:
+ Using provision, first request generates new provisioning data, capture state and send with response, POST state back with subsequent requests
+ Load balance or JSON list of anisette servers
+ "OTP Rolls": hook the time function to generate OTPs for every time in 30sec increments, send once and re-provision
+ Provisioning pt.1 (SPIM & co.) done on-device
+ Private framework?
+ ?

**Comment by JoeMatt** [comment]
Probably Better to move this to GitHub discussions tab
