### ISSUE TITLE
[task] make subdomains for known anisette servers

### ISSUE THREAD

**Issue by JoeMatt** [SideStore/SideStore#172]
Using subdomains should make it easier for us to change address and or forwards as needed.

**Comment by JoeMatt** [comment]
This is what I got so far
![image](https://user-images.githubusercontent.com/399864/205483898-e1ec02c4-70d7-486b-bd93-54f28e4316ae.png)

**Comment by f1shy-dev** [comment]
What if we add a bit to https://apps.altstore.io with a schema of anisette servers, and in the app we could have a way to see if they're online and let the user pick one

Much easier than finding working servers on discord channels and changing the URL in ios settings

**Comment by JoeMatt** [comment]
removing since ppl didn't really want this
