### ISSUE TITLE
New Platform Request

### ISSUE THREAD

**Issue by nanashi211** [SideStore/SideStore#175]
Would you please add Windows, thank you so much! There are "maybe" alot of people expecting that this will be usable (I'm one of them since I can not afford a Mac) on Windows.

**Comment by JPPlayzz** [comment]
it is usable on windows? join jitstreamer discord instructions are all there

**Comment by JJTech0130** [comment]
As previously mentioned, Windows is already supported. You can join the [JitStreamer Discord](https://discord.gg/WsT2hcwRVy) for support.
