### ISSUE TITLE
[Q&A] How to use the SideStore?

### ISSUE THREAD

**Issue by bachig26** [SideStore/SideStore#182]
I've been using the AltStore for almost a year now and I want to know how can use the SideStore as the installation instructions are not clearly defined for general user.

Also I saw the v0.1.1 ipa in the release and if I had to install that means I need the AltStore anyway.

Please let me know the steps to make use of the SideStore.

**Comment by Spidy123222** [comment]
App isn't meant for public usage yet to the full extent. We have basic instructions in the jitstreamer discord and some random person made some instructions in Reddit. Once we finalize the app it should be like installing AltStore.

**Comment by bachig26** [comment]
> App isn't meant for public usage yet to the full extent. We have basic instructions in the jitstreamer discord and some random person made some instructions in Reddit. Once we finalize the app it should be like installing AltStore.

thank you so much.
i'm looking forward to see it soon 👍

**Comment by ArxiChen** [comment]
![Uploading F3B84F7B-064C-4867-8B20-739DC5EF3014.png…]()
Ios16.1.2 xsmax Unable to use

**Comment by JJTech0130** [comment]
I'm going to close this issue, @ArxiChen if you join [the Discord](https://discord.gg/WsT2hcwRVy) you'll be able to get better support.
