### ISSUE TITLE
[BUG] Can't open after restart...

### ISSUE THREAD

**Issue by yodaluca23** [SideStore/SideStore#185]
**Describe the bug**
Every time I restart my phone, and try to open the SideStore app, it just crashes instantly, and I have to resideload it ~~and then resign all my apps because it forgets them...~~

**To Reproduce**
1. Download and install latest SideStore version.
2. Restart you phone.
3. Attempt to open SideStore app.

**Expected behavior**
I want it to just open and work normally, ~~if this is not possible at least make it so we can backup the apps and not have to resign them...~~

**Screenshots**
https://user-images.githubusercontent.com/67206487/207676183-27e67701-d263-436a-ad14-cdc6f5727f98.MOV

**Logs**
Could not find...

**iDevice (please complete the following information):**
Device: iPhone 14 Pro
OS: IOS 16.2

**Additional context**
It also happens at random, only to the SideStore app, not any of my other side-loaded ones.

Edit: I'm stupid, if instead of deleting it, and then resideloading it, you just sideload it on top of it. It keeps all of the memory of the apps, and all of your repos.

**Comment by yodaluca23** [comment]
Some thing else you could do that would be pretty cool, and make it to where you don't need a computer, except for the jitterbug pairing file. Make an app on like AppDB or something that can sign and install SideStore with your personal certificate. This would also solve this problem because every time this happened I could just use that app to re-download and install SideStore.

**Comment by f1shy-dev** [comment]
Which SideStore iPA does this happen with? Because this isn't intended behavior

**Comment by yodaluca23** [comment]
> Which SideStore iPA does this happen with? Because this isn't intended behavior

Yea, sorry I figured out the problem, you have to refresh SideStore before anything else.. and it fixes a lot of stuff including this.
