### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by M0HID** [SideStore/SideStore#195]
**Describe the bug**
Website not working ([sidestore.io](https://sidestore.io))

**To Reproduce**
1. Go to 'sidestore.io'
2. See error

**Expected behavior**
The website should load

**Screenshots**
![image](https://user-images.githubusercontent.com/91326009/208694290-5db9252e-f86e-43a7-8c8f-ebd7ab12c3c2.png)

**Comment by f1shy-dev** [comment]
wrong repo, already reported
