### ISSUE TITLE
[BUG] Can't sign into Apple ID due to -36607 and Developer Program error

### ISSUE THREAD

**Issue by xdccrlz** [SideStore/SideStore#199]
Can't sign in with Apple ID when change Apple ID password:
1. Unnable to sign you  in to your Apple ID, try again later (-36607).
2. This device is already associated with other accounts the Apple Developer Program or the Apple Developer Enterprise Program. Please use a different device.

How to fix it?

**Comment by xdccrlz** [comment]
An attempt to sign in under any AppleID leads to its blocking!
The application turns from a pleasant stray into a destructive fuck.

**Comment by Rihcus** [comment]
https://github.com/SideStore/SideStore/issues/135

**Comment by xdccrlz** [comment]
Thanks! Unfortunately, it was possible to make only the version from Discord work, other builds give an authorization error with any anisette server.
