### ISSUE TITLE
Make onboarding and News more professional

### ISSUE THREAD

**Issue by LitRitt** [SideStore/SideStore#205]
- Remove YouTube link to Rick Roll in pairing file popup. Replace with official guide until SideInstaller is complete.
- Remove Rick Roll News item
- Fix/repurpose permanent top News item. Should link somewhere useful until faq.sidestore.io is ready.

![image](https://user-images.githubusercontent.com/78584620/210119588-9bc1fbc3-669c-4128-88a2-b8f972ac79ea.jpeg)
![image](https://user-images.githubusercontent.com/78584620/210119590-01eab8d6-5d45-43d5-88b5-283f95dd0b93.jpeg)

**Comment by Spidy123222** [comment]
Looks like most of these are resolved just need a video creating a pairing file and we are good.
