### ISSUE TITLE
[BUG] cannot start a AFC server on this device

### ISSUE THREAD

**Issue by 57Zeus** [SideStore/SideStore#217]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Please send logs generated with [idevicedebug](https://github.com/libimobiledevice/libimobiledevice) or Xcode. We will close the issue if a log is missing.

**iDevice (please complete the following information):**

**Additional context**
![IMG_0003](https://user-images.githubusercontent.com/121982667/211200982-eecb4e6b-60f4-4d75-8937-a1f4bc78c5ee.png)
I have had this issue after installing sidestore. i thought it might be a buggy version so i tried other with no success. I am on an iphone SE 2020 with software version 16.1.1. This issue randomly accured after installing the ipa

**Comment by HJRaptor** [comment]
What did you set the ArtworkDeviceSubType value to for dynamic island?

**Comment by gitkanghub** [comment]
same version same error

**Comment by Spidy123222** [comment]
If it's consistent you might need to make a new pairing file for sidestore. There is also issues like minimuxer not handling afc correctly. This is being investigated.

**Comment by eliyoung540** [comment]
I’m experiencing the same problem

**Comment by eliyoung540** [comment]
Mine works now. I made a new paring file and redownloaded the ipa from the official site, I didn’t chose the beta option this time.Then I installed it again.

**Comment by greybaron** [comment]
I experienced this bug when using an Apple ID without 2FA. Using a burner with 2FA worked for me.

**Comment by abhishekgi** [comment]
> I experienced this bug when using an Apple ID without 2FA. Using a burner with 2FA worked for me.

Can you explain what are you saying

**Comment by MARCO-E5** [comment]
Same issue on iPhone 14 Pro, and M1 iPad 11"(16.3), but my other M1 iPad 11"(16.3) don't have this problem.

**Comment by oy842180683** [comment]
I have encountered the same problem, there is no brother to solve this problem, we ask for help.

**Comment by Josuerbth23** [comment]
> O meu funciona agora. Fiz um novo paring file e baixei novamente o ipa do site oficial, dessa vez não escolhi a opção beta. Depois instalei de 


how did you do it buddy? I'm having the same problem, make a video on youtube and send us the link here

**Comment by BigBoiMan123** [comment]
Same issue on a 2021 M1 iPad Pro 12.9" after downgrading to 15.6rc and then delayota'ing to 16.1.1. Worked fine before on 16.2.

**Comment by Boos4721** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/43845654/219932806-9cdd4863-20b9-44b9-8aad-ab2762b09d97.png">

**Comment by abhishekgi** [comment]
anyone know how to fix this error

**Comment by BigBoiMan123** [comment]
Creating a new pairing file and using it fixed the error for me.

**Comment by Josuerbth23** [comment]
Criar um novo arquivo de emparelhamento e usá-lo corrigiu o erro para mim.

**Comment by Josuerbth23** [comment]
> alguem sabe como corrigir esse erro?

Criar um novo arquivo de emparelhamento e usá-lo corrigir o erro para mim.

**Comment by abhishekgi** [comment]
> Creating a new pairing file and using it fixed the error for me.

Really

**Comment by abhishekgi** [comment]
> Creating a new pairing file and using it fixed the error for me.

Actually at first this app worked for me but on second day when I tried to refresh and install new apps int says cannot start a afc server on this device 

after that I tried using new pairing file but it doesn’t work for me I have also tried beta ,stable and others versions unfortunately it doesn’t work and it remain saying cannot start a afc server

**Comment by 1208nn** [comment]
> Creating a new pairing file and using it fixed the error for me.

It works.

---

> > Creating a new pairing file and using it fixed the error for me.
> 
> Actually at first this app worked for me but on second day when I tried to refresh and install new apps int says cannot start a afc server on this device
> 
> after that I tried using new pairing file but it doesn’t work for me I have also tried beta ,stable and others versions unfortunately it doesn’t work and it remain saying cannot start a afc server

It should work. **_I think you'd better check the low-battery mode and ensure it is off._**

**Comment by zisra** [comment]
Same problem

**Comment by dis667** [comment]
same problem guys

**Comment by dis667** [comment]
> Creating a new pairing file and using it fixed the error for me.

TYSM!

**Comment by Takrak** [comment]
Still broken after reinstalling and generating a new pairing file multiple times

**Comment by abhishekgi** [comment]
> Still broken after reinstalling and generating a new pairing file multiple times

Same case with me

**Comment by Takrak** [comment]
Working now, I was using the wrong pairing file

**Comment by deardaveed** [comment]
can someone educate me on exactly how to creating a pairing file?

**Comment by aaadddcom** [comment]
If someone has that problem and generating a new pairing file doesn’t work make sure you enabled the sidestore vpn

**Comment by naturecodevoid** [comment]
> can someone educate me on exactly how to creating a pairing file?

Check the wiki (https://wiki.sidestore.io)

**Comment by unilock** [comment]
To be more specific:

1. Follow the "Pairing File" guide on the SideStore wiki to obtain a copy of your pairing file ("`<UUID>.mobiledevicepairing`")  
  https://wiki.sidestore.io/guides/install.html#pairing-file
2. Rename the pairing file to "`ALTPairingFile.mobiledevicepairing`"
3. Use Finder or what have you to transfer the file to the root of the SideStore app's storage (in the same directory as the "`DMG`" folder and the "`minimuxer.log`" file)
4. Open SideStore on your device -> go to Settings -> select "Reset Pairing File" and follow the instructions
5. SideStore will probably work now. If it doesn't, reboot your device, re-enable the VPN, and try SideStore again.

**Comment by naturecodevoid** [comment]
You can skip steps 2-3. "Reset Pairing File" deletes ALTPairingFile.mobiledevicepairing so those steps are useless

**Comment by abhishekgi** [comment]
> To be more specific:
> 
> 1. Follow the "Pairing File" guide on the SideStore wiki to obtain a copy of your pairing file ("`<UUID>.mobiledevicepairing`")
>    https://wiki.sidestore.io/guides/install.html#pairing-file
> 2. Rename the pairing file to "`ALTPairingFile.mobiledevicepairing`"
> 3. Use Finder or what have you to transfer the file to the root of the SideStore app's storage (in the same directory as the "`DMG`" folder and the "`minimuxer.log`" file)
> 4. Open SideStore on your device -> go to Settings -> select "Reset Pairing File" and follow the instructions
> 5. SideStore will probably work now. If it doesn't, reboot your device, re-enable the VPN, and try SideStore again.

In my case , side store always works for me after installation for 1-2 days and for 1-2 days I but after that is stops working properly, However I can still refresh and install apps but when I try to enable jit it says sidestore cannot start debug server on this device. for more see #400

**Comment by abhishekgi** [comment]
https://github.com/SideStore/SideStore/issues/400#issuecomment-1607826999

**Comment by unilock** [comment]
@naturecodevoid As far as I can tell, the app only checks for a file named "ALTPairingFile.mobiledevicepairing" *specifically,* but honestly I don't know Swift all that well. In any case, the problem wasn't resolved on my end until I renamed the file as such.

"Reset Pairing File" didn't delete that file for me, IIRC - if it did, wouldn't that prevent the app from working until I manually generated a new one?

**Comment by naturecodevoid** [comment]
Reset Pairing File is supposed to delete ALTPairingFile.mobiledevicepairing. If you didn't get the popup to select a pairing file, that's a known issue and it's because you used SideServer to install SideStore. SideServer automatically embeds the pairing file into the app and resetting the pairing file does not yet invalidate the embedded pairing file. However, we are planning to use AFC in the future for super easy pairing file refreshing, which will also deprecate our previous method of embedding the pairing file.

**Comment by Mar-85** [comment]
This is still happening for me, reinstalled the latest version also reset the pairing file (which for once asked me to select the pairing file). but still get the cannot start afc server error.

**Comment by naturecodevoid** [comment]
You need to reset the pairing file, regenerate it and then select the newly generated one

**Comment by Mar-85** [comment]
> You need to reset the pairing file, regenerate it and then select the newly generated one

Thanks very much, I thought I did this but I used the steps from a comment above around putting the file in the SideStore folder. This time I uninstalled it, and used the new file and its all working. Appreciate you commenting, its all working now. Minus the auto refreshing of the apps….that’s never worked
