### ISSUE TITLE
[FEATURE REQUEST] Remove extensions from apps installed via a source

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#218]
Title speaks itself but this is important if you don't have much appid's anymore and want to save appid's.

**Comment by AlixCozmo** [comment]
bump i guess

**Comment by Spidy123222** [comment]
> bump i guess

Unfortunately bumping doesn't help. There is a lot of bug stuff that's in the way. Could see how this goes though if we can cram it in an update.

**Comment by junepark678** [comment]
1397389f95fe47451193ecec9e5f69a8d8fe3135 fixes
