### ISSUE TITLE
[BUG] Unable to check integrity

### ISSUE THREAD

**Issue by Dybo007** [SideStore/SideStore#222]
Can't launch the app after Sideloadly. 

**To Reproduce:**
1. Sideloadly
2. On the phone (the app have no icon) "unable to check integrity".

**iDevice:**
 - Device: iphone 13
 - OS: 16.1.2

**Comment by Spidy123222** [comment]
We don't recommend using sideloady. Use altserver instead. We are tying to figure out why sideloady and other services do this problem but might be a while if it's a problem on their side.

**Comment by Dybo007** [comment]
Ok i'll give it a try with altserver!
Thanks for your help!!
