### ISSUE TITLE
Error when logging in to apple id

### ISSUE THREAD

**Issue by lambs13** [SideStore/SideStore#223]
After the installation is complete, an error occurs when logging in to Appleid, and it is the same when changing another Appleid.
![photo_2023-01-14_15-51-25](https://user-images.githubusercontent.com/55617991/212462358-8b947470-988d-4bd2-9175-b72013dc9bd4.jpg)

**Comment by Spidy123222** [comment]
This is a anisette server problem. Please tell what server is used.

**Comment by lambs13** [comment]
Self-built servers![image](https://user-images.githubusercontent.com/55617991/212462773-30993121-d87c-4cb8-876e-d977a60321c1.png)

**Comment by Spidy123222** [comment]
> Self-built servers![image](https://user-images.githubusercontent.com/55617991/212462773-30993121-d87c-4cb8-876e-d977a60321c1.png)
> 
> 

Since you mention self hosted. What server software did you use?

**Comment by lambs13** [comment]
I restarted the device and logged in again, it worked, anyway, thank you very much.

**Comment by Spidy123222** [comment]
> I restarted the device and logged in again, it worked, anyway, thank you very much.

Yeah sure thing and I'll close this issue as it's resolved.
