### ISSUE TITLE
"Unable to Launch AltStore"

### ISSUE THREAD

**Issue by maomao110112** [SideStore/SideStore#224]
I am using iPad air 5 with iPadOS 15.61
The app Altstore said "
Unable to Launch AltStore
The file "Apps" couldn't be saved in the folder "Application Support"."
there is a button named "retry"
but it`s useless
how can i fix it?
@JJTech0130

**Comment by naturecodevoid** [comment]
Are you using AltStore or SideStore?

**Comment by naturecodevoid** [comment]
@maomao110112 I’m going to close this issue for now; if you are using SideStore, please re-open it.
