### ISSUE TITLE
[FEATURE REQUEST] Live minimuxer logs

### ISSUE THREAD

**Issue by Blockr22** [SideStore/SideStore#231]
Minimuxer logs are not live, these should be live.
If i install any app I would like to see what’s happening in the background live instead of opening & closing minimuxer logs every 5-10seconds to know all the changes

**Comment by naturecodevoid** [comment]
Unless QuickLook supports this, it seems much more trouble than it's worth.

**Comment by Spidy123222** [comment]
Latest sidestore has a log viewer in view logs in settings by clicking button on top right.
