### ISSUE TITLE
[BUG] SideStore crashing on installing a large sized app

### ISSUE THREAD

**Issue by ansnw** [SideStore/SideStore#235]
I was attempting to install GTA:SA. I tried a few versions of the IPA. Some of them had the error “the app is invalid”. One of them installed to about 80% then SideStore crashed. When I reopen SideStore, one of the App IDs were used by GTA:SA but it was not installed.

Apparently Rosha xD#0601 on Discord is having the same issue too.

**Comment by ansnw** [comment]
![F89B246C-80F6-4EED-96FC-EC3F41CE1052](https://user-images.githubusercontent.com/103784554/213943351-3e29044c-f300-4e1d-930f-c10c557bff1d.png)

Also got this

**Comment by ansnw** [comment]
I’m on this build: https://github.com/SideStore/SideStore/releases/tag/auto-update-test

Also SideStore seems to be using 2GB of storage after every failed attempts of installing GTA:SA

**Comment by wayluzy** [comment]
where did you get that spotify ipa? i got mine from this  https://mega.nz/file/TIl3gAaY#lrXBfDc6JBjRDtLjlhg2J3jJCMeFlN5lCUiWl5te3EI and i can't deactivate.

**Comment by wayluzy** [comment]
> > where did you get that spotify ipa? i got mine from this https://mega.nz/file/TIl3gAaY#lrXBfDc6JBjRDtLjlhg2J3jJCMeFlN5lCUiWl5te3EI and i can't deactivate.
> 
> I’m using this: https://mega.nz/file/os0lFILR#BlbD-qtRkYflviKCfNuyaFxT4j1fWxXJjfUhBdRqgYo

it doesn't have premium feature.
