### ISSUE TITLE
Hey I have a question about the Macs on my Apple ID

### ISSUE THREAD

**Issue by Nateay0** [SideStore/SideStore#237]
So there were 2 new Macs on my Apple ID and I don't own any Macs at all so I thought it was sidestore emulating something idk.  But is it safe to remove the 2 Macs on my Apple ID? 

![image](https://user-images.githubusercontent.com/92893096/214029168-66c898fd-7d07-49c8-8db0-4cdd0599fabf.jpeg)

**Comment by naturecodevoid** [comment]
SideStore doesn't emulate a mac. If you never signed into these devices with your apple ID, you might want to ensure that no one has gotten access to your account.

**Comment by naturecodevoid** [comment]
One of these is caused by the device originally used to sideload SideStore, and one is caused by anisette. If you want to be safe, don't remove them because it might cause issues.

**Comment by Nateay0** [comment]
Well the discord says it should be sidestore and they have the same thing

**Comment by Nateay0** [comment]
> One of these is caused by the device originally used to sideload SideStore, and one is caused by anisette. If you want to be safe, don't remove them because it might cause issues.

But what can happen if I remove them?

**Comment by naturecodevoid** [comment]
Some people have reported nothing happening, but it might've locked another persons account
