### ISSUE TITLE
Move SideServer for macOS into a separate repo

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#24]
This will make it easier to track against the Windows and Linux versions, as well as make it easier to rewrite AltServer when the time comes.

**Comment by JJTech0130** [comment]
I'm going to work on copying it by hand first, then I'll redo the copy with `git filter-repo` to keep all git history.

**Comment by JJTech0130** [comment]
I've gotten a version to compile. I just need to redo it properly with filter and keeping the submodules

**Comment by JJTech0130** [comment]
```
git filter-repo                         \
  --path AltPlugin/                     \
  --path AltServer/                     \
  --path AltServer.xcconfig             \
  --path AltStore.xcodeproj/            \
  --path AltXPC/                        \
  --path AltXPC.xcconfig                \
  --path Build.xcconfig                 \
  --path CodeSigning.xcconfig.sample    \
  --path Dependencies/AltSign/          \
  --path Dependencies/libimobiledevice/ \
  --path Dependencies/libplist/         \
  --path Dependencies/libusbmuxd/       \
  --path Shared/                        \
  --path LICENSE                        \
  --path .gitignore                     \
  --path .gitmodules                    \
  ```

**Comment by JJTech0130** [comment]
https://github.com/JJTech0130/SideServer

**Comment by JJTech0130** [comment]
Ok! [SideServer](https://github.com/JJTech0130/SideServer) is mostly complete. I stripped out almost everything from AltStore, and AltServer still builds. A few aesthetic changes like the Xcode project name would be nice, but it's mostly there.
I did include all the other branches, but I haven't reviewed any other than `develop` (though they should still be filtered).

**Comment by JoeMatt** [comment]
Nice.

Only concern is do we care this will make git upstream changes from AltServer difficult?

**Comment by JoeMatt** [comment]
I added this repo and gave you maintain access
https://github.com/SideStore/SideServer
