### ISSUE TITLE
Does sidestore work with Advanced Data Protection?

### ISSUE THREAD

**Issue by Nexxol** [SideStore/SideStore#240]
iOS 16.3 released and with that is advanced data protection that  end to end encrypts all cloud stuff. Does sidestore work with ADP on? With AltStore it doesn’t because the iCloud version is outdated

**Comment by Cr0wTom** [comment]
Yes, I have ADP on for the last month, and SideStore works flawlessly.

**Comment by Spidy123222** [comment]
It works just depends if the anisette server supports it which I believe most do now. Should mimic a newer macOS.

**Comment by Nexxol** [comment]
Forgot to mention it in windows
