### ISSUE TITLE
[BUG] No support for Hardware Security Keys 2FA on iOS 16.3

### ISSUE THREAD

**Issue by Cr0wTom** [SideStore/SideStore#241]
**Describe the bug**
With iOS 16.3 the addition of hardware security keys is added as a 2FA authentication. After adding this functionality to an iCloud account, sidestore still asks for a 6 number pin code, while there is no pin code available while having hardware security keys enabled.

**To Reproduce**
1. Enable hardware security keys on iCloud
2. Try to refresh apps or install new apps on Sidestore

**Expected behavior**
SideStore should ask for the proper 2FA method, applicable to the account, in this case hardware security key over NFC or Lightning.

**iDevice (please complete the following information):**
 - Device: iPhone12 Pro
 - OS: iOS 16.3

**Comment by Spidy123222** [comment]
This is a interesting problem that might have to be solved in a later date. It also doesn’t help none (that I know of) of the dev team has a hardware security key (yubikey, google titan, etc) yet to test with. Is there no way for you to use a code for the mean time?

**Comment by Cr0wTom** [comment]
AFAIK there is no way to have two 2FA methods right now on your iCloud account. What I did is create a separate account without hardware keys as 2FA, but this is just a temporary solution, and in my point of view it should be fixed in the future.

**Comment by veritas06** [comment]
Any chance there's an update on this? Even just to hear that it is on the roadmap?

**Comment by Spidy123222** [comment]
> Any chance there's an update on this? Even just to hear that it is on the roadmap?

Unfortunately there isn't any as we have our hands full on our current biggest issues. Which are expire early issue and anisette which is getting development on a new method. Would have to see how we could add support and if anisette will be needed or if current solution we want to add will mess with anything.

**Comment by veritas06** [comment]
Got it. Thanks for the quick reply about it though!
I could start looking over the code to see if I could lend any hand, but only just getting started playing around with iOS development.

**Comment by Spidy123222** [comment]
> Got it. Thanks for the quick reply about it though!
> 
> I could start looking over the code to see if I could lend any hand, but only just getting started playing around with iOS development.

If you have a discord account we can talk more directly than GitHub in our public server https://discord.gg/CacsuuzsBq
