### ISSUE TITLE
[BUG] Widget not working 

### ISSUE THREAD

**Issue by MARCO-E5** [SideStore/SideStore#244]
**Describe the bug**
Widget not working 

**To Reproduce**

**Expected behavior**
It should show how many days left

**Screenshots**
![4E8B8371-11AD-4639-A8DD-4D551F6B8E60](https://user-images.githubusercontent.com/69240218/215301276-00e7362e-39f1-4ab7-a5a0-2585cb5d3264.jpeg)

**Logs**
Please send logs generated with [idevicedebug](https://github.com/libimobiledevice/libimobiledevice) or Xcode. We will close the issue if a log is missing.

**iDevice (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.3

**Additional context**

**Comment by naturecodevoid** [comment]
#246 will be used to track this
