### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Shizu567** [SideStore/SideStore#248]
**Describe the bug**
can’t able to sign in Sidestore with my apple id, it’s says data is in incorrect format.

**iDevice (please complete the following information):**
 - Device: [e.g. iPhone13]
 - OS: [e.g. iOS16.1]

**Comment by Spidy123222** [comment]
This is a anisette server setup issue. Make sure if it's a anisette server that's known to work or if it's your own then make sure it's configured correctly.
