### ISSUE TITLE
[Questions]SideStore to run on iOS 13.3

### ISSUE THREAD

**Issue by sxbai** [SideStore/SideStore#254]
If I want the SideStore to run on iOS 13.3, how do I compile the SiedStore?

**Comment by naturecodevoid** [comment]
Please use Discord or GitHub discussions for support. I think a team member tried to get it to run on iOS 13, but 13 is missing a lot of the required frameworks so the app ended up with almost a blank interface. I don't know if it was functional or not

**Comment by JJTech0130** [comment]
I believe that it was an intentional decision not to support older iOS versions, which already have mature jailbreaks or other solutions to sideload apps. This allows us to develop at a rapid pace, and adopt features only possible on the latest version of iOS.
