### ISSUE TITLE
[FEATURE REQUEST] Replicate SideStore’s VPN architecture

### ISSUE THREAD

**Issue by OniriCorpe** [SideStore/SideStore#255]
### Describe the feature

I would like to package for YunoHost a server that replicates the current SideServer function, so that it would be easy to self-host the project

Would it be possible to explain me the procedure for that?
Or maybe it is still too early?

### Use cases

Same as SideStore but self hosted 

### Alternatives

An alternative could be to host AltServer-Linux but I can't get it to work reliably

**Comment by naturecodevoid** [comment]
I'm not sure what you mean. The main feature SideStore has over AltStore is **not requiring an AltServer**. Everything is done on-device. There isn't an easy way to make a central server to handle this, since there isn't one to begin with. You would have to make some major changes to SideStore, if it's even possible.

**Comment by yuzjjl** [comment]
Perhaps what he means is to develop the Linux version of Altserver so that it can run on the local server for lightweight use (instead of running on a computer). This may not be Sideserver's job.

**Comment by naturecodevoid** [comment]
There is already a Linux version of AltServer, but it doesn't work well with SideStore ATM. (Users are having issues with it after installation.) SideServer for Linux is coming soon.

**Comment by yuzjjl** [comment]
Look forward to its coming

**Comment by naturecodevoid** [comment]
Closing since this doesn't seem feasible, and it's probably just a misunderstanding of how SideStore works. If it's not, please reopen it
