### ISSUE TITLE
[BUG] Unable to Launch SideStore

### ISSUE THREAD

**Issue by ma3252788** [SideStore/SideStore#261]
### Describe the bug

I used the latest version of the IPA file, and then I got the plist file, and then I got this error:
![image](https://user-images.githubusercontent.com/22229456/218306994-10a31415-a8a0-4189-a2fa-47959ae1be3a.png)

### Instructions to reproduce

Use jitterbugpair to get the plist file, then use Sdestore to import the plist file, and finally open Sdestore

### What version of SideStore are you using?

Nightly

### Other info

I also tried version 0.1.1, but after this version is imported into the plist file, it will be prompted as follows:

![image](https://user-images.githubusercontent.com/22229456/218307107-bdd7387d-971b-49bb-875b-03934c620f27.png)

**Comment by f1shy-dev** [comment]
Where did you get the IPA from?

**Comment by Spidy123222** [comment]
> ### Describe the bug
> I used the latest version of the IPA file, and then I got the plist file, and then I got this error: ![image](https://user-images.githubusercontent.com/22229456/218306994-10a31415-a8a0-4189-a2fa-47959ae1be3a.png)
> 
> ### Instructions to reproduce
> Use jitterbugpair to get the plist file, then use Sdestore to import the plist file, and finally open Sdestore
> 
> ### What version of SideStore are you using?
> Nightly
> 
> ### Other info
> I also tried version 0.1.1, but after this version is imported into the plist file, it will be prompted as follows:
> 
> ![image](https://user-images.githubusercontent.com/22229456/218307107-bdd7387d-971b-49bb-875b-03934c620f27.png)

Please use altserver or sideserver to install sidestore. Things like sideloady won’t work.

**Comment by ma3252788** [comment]
> Where did you get the IPA from?

From this link:
https://github.com/SideStore/SideStore/releases

**Comment by ma3252788** [comment]
> > ### Describe the bug
> > I used the latest version of the IPA file, and then I got the plist file, and then I got this error: ![image](https://user-images.githubusercontent.com/22229456/218306994-10a31415-a8a0-4189-a2fa-47959ae1be3a.png)
> > ### Instructions to reproduce
> > Use jitterbugpair to get the plist file, then use Sdestore to import the plist file, and finally open Sdestore
> > ### What version of SideStore are you using?
> > Nightly
> > ### Other info
> > I also tried version 0.1.1, but after this version is imported into the plist file, it will be prompted as follows:
> > ![image](https://user-images.githubusercontent.com/22229456/218307107-bdd7387d-971b-49bb-875b-03934c620f27.png)
> 
> Please use altserver or sideserver to install sidestore. Things like sideloady won’t work.

Thank you , I did install it with sideloady, I'll try to reinstall it

**Comment by naturecodevoid** [comment]
Sideloadly/any other installation methods other than SideServer and AltServer and not supported atm.

**Comment by ma3252788** [comment]
Finally, I used the following method to complete the automatic signature：

https://www.machunjie.com/macos/1441.html
