### ISSUE TITLE
[BUG] New SwiftUI shoved into Sidebar UI on iPads

### ISSUE THREAD

**Issue by Swifticul** [SideStore/SideStore#264]
### Describe the bug

In the latest SideStore pull-request build, all of the main UI is contained within the tiny left sidebar. Idk where you’d put it right now but this would be turned off by adding the “.navigationViewStyle(StackNavigationViewStyle())” arg to the NavigationView

### Instructions to reproduce

Install the latest SideStore pull-request build on an iPad

### What version of SideStore are you using?

SideStore 0.3.0-pr.221

**Comment by naturecodevoid** [comment]
This will be fixed once I push my SwiftUI fixes. 100% credit to you for the code that fixes it.

**Comment by Swifticul** [comment]
oh okay awesome ! cant wait to test it out
