### ISSUE TITLE
[BUG] Failed to login : The data is not in the correct format

### ISSUE THREAD

**Issue by patty1213** [SideStore/SideStore#268]
### Describe the bug

Failed to login : The data is not in the correct format

### Instructions to reproduce

Failed to login : The data is not in the correct format

### What version of SideStore are you using?

0.1.1

### Other info

Failed to login : The data is not in the correct format

**Comment by naturecodevoid** [comment]
1. 0.1.1 is an older version
2. This is probably due to using ani.sidestore.io. Please try another anisette server or [host your own](https://wiki.sidestore.io/guides/custom-anisette). Until we get our anisette problems figured out, hosting your own anisette server is 100% the best option.
