### ISSUE TITLE
[FEATURE REQUEST] Can we get clear cache like that in latest altstore

### ISSUE THREAD

**Issue by Blockr22** [SideStore/SideStore#273]
### Describe the feature

Its the same feature as new altstore update.
Clearing cache will likely remove all temporary files as well as backup data for deleted apps, freeing up space on the iPhone.

### Use cases

Sidestore is taking is more than 7gb of space on my iPhone 14 running iOS 16.3.1 & i m only using 4 ipa’s with it.
Clearing cache should free up little bit of space.

**Comment by naturecodevoid** [comment]
We should be able to cherry pick Riley's changes pretty easily.

**Comment by Blockr22** [comment]
Nice, would love this feature

**Comment by Valvify** [comment]
+1 on this feature. Hope it can be implemented as my iPad is running out of space!

**Comment by Practicalbutterfly5** [comment]
This feature is needed, otherwise sidestore just takes all my device storage

**Comment by eeshankeni** [comment]
Certainly needed, sidestore is taking up 20 gigs at the moment for me.

**Comment by KizYuka** [comment]
I want it

**Comment by Spidy123222** [comment]
Was added
