### ISSUE TITLE
Error 38607

### ISSUE THREAD

**Issue by SuperiorSpiderman** [SideStore/SideStore#275]
### Describe the bug

I am a user/have used altstore and scarlet. When using sidestore, I am unable to login and it gives me an error with code 38607. It says i need to use a different device because this device is already associated with other accounts enrolled in the developer program. Please help.

### Instructions to reproduce

Just log in normally

### What version of SideStore are you using?

0.1.1

**Comment by naturecodevoid** [comment]
1. 0.1.1 is an outdated version
2. Please use a different anisette server, or [host your own](https://wiki.sidestore.io/guides/custom-anisette.html) (hosting your own is the preferred method until we figure out our anisette problems)
