### ISSUE TITLE
[BUG] Sidestore is loading forever!

### ISSUE THREAD

**Issue by NobbeadJC** [SideStore/SideStore#277]
### Describe the bug

I had just installed Sidestore and I tried signing in but it just infinitely loads. I’ve tried reinstalled it many times, did all the steps but nothing works! Pls help fix this.

### Instructions to reproduce

e

### What version of SideStore are you using?

0.1.1

**Comment by Spidy123222** [comment]
Change the anisette server. Also if you want more features I recommend installing nightly.

**Comment by naturecodevoid** [comment]
1. 0.1.1 is an outdated version
2. Please use a different anisette server, or [host your own](https://wiki.sidestore.io/guides/custom-anisette.html) (hosting your own is the preferred method until we figure out our anisette problems)

**Comment by NobbeadJC** [comment]
> * 0.1.1 is an outdated version
> * Please use a different anisette server, or [host your own](https://wiki.sidestore.io/guides/custom-anisette.html) (hosting your own is the preferred method until we figure out our anisette problems)

Ty this helped
