### ISSUE TITLE
[BUG] Unable to Launch SideStore

### ISSUE THREAD

**Issue by JamesLewisLiu** [SideStore/SideStore#280]
### Describe the bug

![D2E0E9A5-0994-4A86-B456-5E25D1AD47F3](https://user-images.githubusercontent.com/17558260/221368469-61c9a0e7-8054-4103-a3a0-93032409dfaf.png)

### Instructions to reproduce

Use TrollStore to install SideStore

### What version of SideStore are you using?

Beta

**Comment by naturecodevoid** [comment]
Please use AltServer/SideStore to install. Other methods are currently not supported, but we are planning to support them soon.
