### ISSUE TITLE
[BUG] After connection SideStore ask for 2FA code but don't generate one

### ISSUE THREAD

**Issue by CercubeSource** [SideStore/SideStore#285]
### Describe the bug

When I try to connect it instantly ask for a 6 digit 2FA code the problem is that there isn't one being created on my other icloud devices iPhone or Macbook (2FA work correctly everywhere else)
I tryed every version of SideStore, I have my own render.com anisette server but tried with every other one. 
I have a developper apple account.

### Instructions to reproduce

Try to connect
App ask for 2FA code
There is no 2FA code on my other iCloud device.
I can't connect 
If I try too many time I get my account locked.

### What version of SideStore are you using?

0.3.1

**Comment by CercubeSource** [comment]
I figured out this is a problem with my render.com anisette server not supporting Advanced Data Protection how can I create one that support it?

**Comment by naturecodevoid** [comment]
I believe Provision supports it, make sure it's up to date. Otherwise, please open an issue in the repo

**Comment by ArowGames** [comment]
I have the same Issue what can i do about it?
