### ISSUE TITLE
[BUG] minimuxer logs "Failed to create heartbeat client: UnknownError" and unable to refresh or sideload

### ISSUE THREAD

**Issue by hurryman2212** [SideStore/SideStore#289]
### Describe the bug

Device: iPhone 14 Pro
iOS version: 16.3.1

After the first successful installation of _SideStore_ (of which version was the previous one which I got last week but I do not remember the version, and I did not update the app), it got invalidated even though it still had remaining days.
When I have reinstalled the same outdated version (with same outdated Wireguard configuration) with the same procedure, the refreshing did not work with the message that I do not remember now.

After that, I have acquired the latest versions of SideStore IPA (of which version is 0.3.1) and the corresponding Wireguard configuration file, as well as the newly generated device paring file from jitterbugpair.
After the successful installation of SideStore IPA through altlinux (of which version is the same as the initial attempt: 0.4.2-2), with or without VPN/Wi-Fi, refresh and sideloading always fails with "An unknown error occured." message.

The logger for minimuxer shows the following:
```
05:45:20 [INFO] Logger initialized!!
05:45:20 [INFO] Starting heartbeat thread
05:45:25 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Unable to start mobile image mounter: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:28 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:29 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:30 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:31 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:32 [ERROR] Failed to create heartbeat client: UnknownError
05:45:33 [ERROR] Failed to create heartbeat client: UnknownError
05:45:33 [ERROR] Unable to start mobile image mounter: UnknownError
05:45:33 [ERROR] Failed to create heartbeat client: UnknownError
...
```

### Instructions to reproduce

1. Install SideStore IPA with altlinux on Linux
2. Install Wireguard iOS application and the configuration for SideStore
3. Enable the VPN connection for it
4. Verify the developer signature for SideStore application in the iOS settings
5. Open SideStore application and apply the pairing file acquired with jitterbugpair on Linux
6. Login the Apple ID within SideStore application
7. Refresh SideStore application

### What version of SideStore are you using?

0.3.1

### Other info

_altlinux_ was acquired from [https://github.com/i-love-altlinux/AltLinux/releases/tag/altlinux](https://github.com/i-love-altlinux/AltLinux/releases/tag/altlinux).

_jtterbugpair_ was acquired from [https://sidestore.io/#downloads](https://sidestore.io/#downloads).

_SideStore_ IPA file and the Wireguard configuration was acquired from [https://github.com/SideStore/SideStore/releases/tag/0.3.1](https://github.com/SideStore/SideStore/releases/tag/0.3.1).

**Comment by naturecodevoid** [comment]
I've heard that users have issues when they install via AltLinux, is there any possibility you can try with SideServer Mac / AltServer Windows?

**Comment by hurryman2212** [comment]
> I've heard that users have issues when they install via AltLinux, is there any possibility you can try with SideServer Mac / AltServer Windows?

Sideloading the SideStore IPA with AltServer on Windows does not solve the above issue.

However after removing/reinstalling the Wireguard iOS application + other VPN applications and the VPN profiles on the iOS VPN setting screen, it is now solved.

**Comment by yeqiloi** [comment]
> However after removing/reinstalling the Wireguard iOS application + other VPN applications and the VPN profiles on the iOS VPN setting screen, it is now solved.
The same question,removing/reinstalling the Wireguard iOS application does not solve the problem。Can you elaborate on how to use other VPN applications and VPN profiles on the iOS VPN settings screen?

**Comment by yeqiloi** [comment]
> However after removing/reinstalling the Wireguard iOS application + other VPN applications and the VPN profiles on the iOS VPN setting screen, it is now solved.

The same question,removing/reinstalling the Wireguard iOS application does not solve the problem。Can you elaborate on how to use other VPN applications and VPN profiles on the iOS VPN settings screen?
