### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by matx33** [SideStore/SideStore#293]
### Describe the bug

I cant install more than 2 apps

### Instructions to reproduce

I used wireguard and anisette server. But when i try to install more than apps it says that i don’t have any app ids anymore even though wireshark should be able to bypass this issue. 

### What version of SideStore are you using?

0.3.1

**Comment by Spidy123222** [comment]
Wireguard isn't a app limit bypass it's a vpn client/server. Currently there is no offical method for MacDirtyCow on sidestore yet if this is what your referring to. So 0.3.1 doesn't haven't mdc.
