### ISSUE TITLE
[BUG] This action could not be completed due to possible environment mismatch (-29004)

### ISSUE THREAD

**Issue by HexCodeFFF** [SideStore/SideStore#295]
### Describe the bug

When trying to sideload or refresh on the latest nightly, this error occurs
![image](https://user-images.githubusercontent.com/35177464/223463767-e75cdc71-f2ed-46c5-8f15-5ba5875527ee.png)

### Instructions to reproduce

Try to sideload or refresh any app on the latest nightly

### What version of SideStore are you using?

0.3.2-nightly.2023.03.07.1

**Comment by naturecodevoid** [comment]
We are aware of this. Please try hosting your own anisette server (see https://wiki.sidestore.io)

**Comment by HexCodeFFF** [comment]
It works fine on 0.3.1 so I'm just using that for now

**Comment by josuemorais** [comment]
> Estamos cientes disso. Tente hospedar seu próprio servidor anisette (consulte https://wiki.sidestore.io )

the render platform that creates free servers is not working for free creation

**Comment by naturecodevoid** [comment]
You must fork the repo and rename your fork, then use the nrn repo for render server
