### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by josuemorais** [SideStore/SideStore#296]
### Describe the bug

Failed to Log In
This action could not be completed due to possible environment mismatch. (-29004)

### Instructions to reproduce

when trying to login, placing the pairing file, the sidestore beta application gives this error

### What version of SideStore are you using?

beta

### Other info

I can not log in

**Comment by naturecodevoid** [comment]
We are aware of this. Please try hosting your own anisette server (see https://wiki.sidestore.io)

**Comment by josuemorais** [comment]
> Estamos cientes disso. Tente hospedar seu próprio servidor anisette (consulte https://wiki.sidestore.io )

the render platform that creates free servers is not working for free creation
