### ISSUE TITLE
Crash when deleting inactive app data

### ISSUE THREAD

**Issue by ringosham** [SideStore/SideStore#297]
### Describe the bug

As title, the app crashes when deleting an inactive app’s app data.

### Instructions to reproduce

1. Install 2 apps
2. Launch one of them and generate some app data
3. Install another one, and uninstall the one that has app data
4. Delete the app data that is inactive.

### What version of SideStore are you using?

0.3.1-nightly.2023.03.01.1

**Comment by Spidy123222** [comment]
No longer crashes, closing issue
