### ISSUE TITLE
[BUG] PackageInspectionFailed

### ISSUE THREAD

**Issue by matx33** [SideStore/SideStore#299]
### Describe the bug

Can’t refresh or install apps

### Instructions to reproduce

i have this log error when i try to install or refresh apps: 
08:20:40 [INFO] Logger initialized!!
08:20:40 [INFO] Starting heartbeat thread
08:20:45 [ERROR] Failed to create heartbeat client: UnknownError
08:21:00 [ERROR] Failed to create heartbeat client: UnknownError
08:21:00 [ERROR] Unable to start mobile image mounter: UnknownError
08:21:00 [INFO] Heartbeat success!
08:21:05 [INFO] Developer disk image already mounted
08:21:05 [INFO] Auto image mounter has finished, have a great day!
08:21:10 [INFO] Heartbeat success!
08:21:21 [INFO] Heartbeat success!
08:21:28 [INFO] Created PublicStaging directory
08:21:28 [INFO] Created bundle ID directory
08:21:28 [INFO] Sending bytes of ipa
08:21:32 [INFO] Heartbeat success!
08:21:36 [ERROR] Unable to install app: UnknownError
08:21:42 [INFO] Heartbeat success!
08:21:53 [INFO] Heartbeat success!
08:22:04 [INFO] Heartbeat success!
08:22:14 [INFO] Heartbeat success!
08:22:25 [INFO] Heartbeat success!
08:22:35 [INFO] Heartbeat success!
08:22:46 [INFO] Heartbeat success!
08:22:56 [INFO] Heartbeat success!
08:23:06 [INFO] Created PublicStaging directory
08:23:06 [INFO] Created bundle ID directory
08:23:06 [INFO] Sending bytes of ipa
08:23:07 [INFO] Heartbeat success!
08:23:18 [INFO] Heartbeat success!
08:23:21 [ERROR] Unable to install app: PackageInspectionFailed
08:23:28 [INFO] Heartbeat success!
08:23:39 [INFO] Heartbeat success!

### What version of SideStore are you using?

0.3.1

**Comment by naturecodevoid** [comment]
what IPA? seems like an issue with the app you're trying to install, not SideStore

**Comment by matx33** [comment]
it’s not i’ve tried multiple ipa but it’s always the same i’ll try to reinstall it when my app ids expires

**Comment by Spidy123222** [comment]
This issue was solved in 0.5.0
