### ISSUE TITLE
ALTDeviceID in Xcode as variable

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#30]
> **(Development only)** Change the value for `ALTDeviceID` in the Info.plist to your device's UDID. Normally, SideServer embeds the device's UDID in SideStore's Info.plist during installation. When running through Xcode you'll need to set the value yourself or else SideStore won't resign (or even install) apps for the proper device. You can achieve this by changing a few things to be able to build and use SideStore.

This is confusing for people less experienced with Xcode, as `Info.plist` is generated at build time and does not show up in the editor. Instead, you must edit the property in AltStore -> Targets -> AltStore -> Info -> Custom iOS Target Properties.

I would have just PR'd a change in the README, but I wondered if another solution might be preferable, such as adding the property to `CodeSigning.xcconfig` or somewhere else more visible.

**Comment by Nythepegasus** [comment]
Probably something like:
```
#include "Build.xcconfig"

PRODUCT_BUNDLE_IDENTIFIER = $(ORG_PREFIX).AltStore

ALT_DEVICE_ID = 00008110-000A68390A82801E
```
For AltStore.xcconfig

Then in AltStore Info.plist, use $(ALT_DEVICE_ID) for the AltDeviceID key. Could probably add it to #17.

**Comment by JoeMatt** [comment]
plist var can be done with XCConig vars as @Nythepegasus mentioned, i'll look at this for #17

**Comment by zlatichoice** [comment]
Huh
