### ISSUE TITLE
[BUG] UnknownError when trying to install app

### ISSUE THREAD

**Issue by matx33** [SideStore/SideStore#301]
### Describe the bug

can’t install one special ipa
side load normally

### Instructions to reproduce

i can install ipa with scarlet but get errors when trying to install it with sidestore any ideas why ? 
log: 
08:20:57 [INFO] Logger initialized!!
08:20:57 [INFO] Starting heartbeat thread
08:20:58 [INFO] Heartbeat success!
08:21:03 [INFO] Developer disk image already mounted
08:21:03 [INFO] Auto image mounter has finished, have a great day!
08:21:08 [INFO] Heartbeat success!
08:21:19 [INFO] Heartbeat success!
08:21:29 [INFO] Heartbeat success!
08:21:40 [INFO] Heartbeat success!
08:21:51 [INFO] Heartbeat success!
08:22:01 [INFO] Heartbeat success!
08:22:12 [INFO] Heartbeat success!
08:22:22 [INFO] Heartbeat success!
08:22:29 [INFO] Created PublicStaging directory
08:22:29 [INFO] Created bundle ID directory
08:22:29 [INFO] Sending bytes of ipa
08:22:33 [INFO] Heartbeat success!
08:22:36 [ERROR] Unable to install app: UnknownError
08:22:44 [INFO] Heartbeat success!
08:22:55 [INFO] Heartbeat success!
08:23:06 [INFO] Heartbeat success!
08:23:17 [INFO] Heartbeat success!
08:23:27 [INFO] Heartbeat success!
08:23:38 [INFO] Heartbeat success!
08:23:49 [INFO] Heartbeat success!
08:23:59 [INFO] Heartbeat success!
08:24:10 [INFO] Heartbeat success!
08:24:21 [INFO] Heartbeat success!
08:24:31 [INFO] Heartbeat success!
08:24:42 [INFO] Heartbeat success!
08:24:53 [INFO] Heartbeat success!
08:25:03 [INFO] Heartbeat success!
08:25:14 [INFO] Heartbeat success!
08:25:25 [INFO] Heartbeat success!
08:25:35 [INFO] Heartbeat success!
08:25:46 [INFO] Heartbeat success!
08:25:56 [INFO] Heartbeat success!
08:26:07 [INFO] Heartbeat success!
08:26:18 [INFO] Heartbeat success!
08:26:18 [INFO] Created PublicStaging directory
08:26:18 [INFO] Created bundle ID directory
08:26:18 [INFO] Sending bytes of ipa
08:26:28 [INFO] Heartbeat success!
08:26:39 [INFO] Heartbeat success!
08:26:41 [INFO] Done!
08:26:50 [INFO] Heartbeat success!
08:27:00 [INFO] Heartbeat success!
08:27:11 [INFO] Heartbeat success!
08:27:22 [INFO] Heartbeat success!
08:27:32 [INFO] Heartbeat success!
08:27:43 [INFO] Heartbeat success!
08:27:53 [INFO] Heartbeat success!
08:28:04 [INFO] Heartbeat success!
08:28:09 [INFO] Created PublicStaging directory
08:28:09 [INFO] Created bundle ID directory
08:28:09 [INFO] Sending bytes of ipa
08:28:14 [INFO] Heartbeat success!
08:28:16 [ERROR] Unable to install app: UnknownError
08:35:08 [ERROR] Heartbeat recv failed: MuxError
08:35:12 [INFO] Heartbeat success!
08:35:23 [INFO] Heartbeat success!
08:35:33 [INFO] Heartbeat success!
08:35:42 [INFO] Created PublicStaging directory
08:35:42 [INFO] Created bundle ID directory
08:35:42 [INFO] Sending bytes of ipa
08:35:44 [INFO] Heartbeat success!
08:35:50 [ERROR] Unable to install app: UnknownError
08:37:30 [ERROR] Heartbeat recv failed: MuxError
08:37:30 [INFO] Heartbeat success!
08:37:41 [INFO] Heartbeat success!
08:37:51 [INFO] Heartbeat success!

### What version of SideStore are you using?

0.3.1

**Comment by naturecodevoid** [comment]
what IPA? and what's the size of the IPA?

**Comment by matx33** [comment]
it’s myfitnesspal from platinmods the size of the ipa is 36mb

**Comment by leo100rock** [comment]
Same problem here, even when I try to update Sidestore

**Comment by abhishekgi** [comment]
same issue i am facing
