### ISSUE TITLE
[BUG] There is no provisioning profile with the requested identifier on this team.

### ISSUE THREAD

**Issue by likereadboy** [SideStore/SideStore#306]
### Describe the bug

refresh sidestore error occurred: There is no provisioning profile with the requested identifier on this team.

### Instructions to reproduce

refresh sidestore apps

### What version of SideStore are you using?

0.3.1

**Comment by hugeBlack** [comment]
Same there, I got this error when installing new apps or refreshing existing apps. Only JIT works.

**Comment by naturecodevoid** [comment]
known issue, we will cherry pick AltStore's fix

**Comment by josephtokyo** [comment]
![Uploading ED5D28F4-E36D-4208-8524-B5EFB7D72BBB.png…]()

**Comment by yulianaonly** [comment]
so do you guys met this problem with all apps? or only several? I can't refresh my comic app, it mentioned the same bug

**Comment by chinmayp297** [comment]
Any idea how many days it would take to release the new version?

**Comment by yulianaonly** [comment]
It is already fixed now. You can re-install AltStore by AltServer on PC. You don't have to remove it at first

**Comment by Dyynex** [comment]
sideserver on macos doesnt seem to be installing the latest update, should i be instaslling through altstore?

**Comment by naturecodevoid** [comment]
you need to use the test build in our discord

**Comment by EpicGamer121** [comment]
> you need to use the test build in our discord

Where in the discord

**Comment by Baggette** [comment]
> > you need to use the test build in our discord
> 
> Where in the discord

heres a a link to it, https://cdn.discordapp.com/attachments/1037581733144559676/1088318838380187688/SideStorePR311.ipa
