### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by josephtokyo** [SideStore/SideStore#307]
### Describe the bug

![9D9E5679-7EE4-43A8-B6A4-CC3031105510](https://user-images.githubusercontent.com/13037324/226523809-4c29a6ff-1218-4975-a126-c024fa4953ae.png)

### Instructions to reproduce

Here’s the problem
![C4D23E46-496A-4D12-8F4F-9E569677EC23](https://user-images.githubusercontent.com/13037324/226523844-8607a50c-ab64-40a8-bee3-465cb11fc6cc.png)

### What version of SideStore are you using?

9.9.9

### Other info

![8EF0AD56-24A5-4648-8E9B-C6D104385FFE](https://user-images.githubusercontent.com/13037324/226523866-6d3eb641-5e6f-44e0-81c7-4f95f8105f2e.png)
I keep trying to refresh it

**Comment by naturecodevoid** [comment]
Pleaee stop creating duplicate issues with no title. This has already been reported: #306
