### ISSUE TITLE
[FEATURE REQUEST] Swipe up with 3 fingers 3 times to reveal MacDirtyCow section

### ISSUE THREAD

**Issue by lingsoul** [SideStore/SideStore#308]
### Describe the feature

Swipe up with 3 fingers 3 times to reveal MacDirtyCow section
<img width="397" alt="image" src="https://user-images.githubusercontent.com/22099083/226792371-d36f2d13-8584-4c74-abde-c30a8d055b11.png">

### Use cases

https://faq.altstore.io/how-to-use-altstore/macdirtycow

**Comment by naturecodevoid** [comment]
MDC support is integrated and WIP, join our discord for test builds
