### ISSUE TITLE
[BUG] Quantumsource++ doesn't work in SideStore even though it works in the latest AltStore beta

### ISSUE THREAD

**Issue by reticivis-net** [SideStore/SideStore#314]
### Describe the bug

When adding [Quantumsource++](https://quarksources.github.io/#sources), this error happens:

![image](https://user-images.githubusercontent.com/35177464/227286533-fcf4644a-3b99-474c-944c-72e21dc67a94.png)

The data couldn't be read because it isn't in the correct format.
E downloadURL:String or downloadURLs:[[Platform:URL]] key required.

The source loads fine on AltStore 1.6.2b.

### Instructions to reproduce

Try to add the source https://bit.ly/Quantumsource-plus

### What version of SideStore are you using?

0.3.2-pr.311+875b25c

**Comment by WuXu1** [comment]
Bro use my source. I forked from QuarkSources and made everything better - the apps actually get updated too. 

here's the website: https://wuxu1.github.io/

and the source links to add to sidestore/altstore:

https://bit.ly/wuxuslibrary
https://bit.ly/wuxuslibraryplus

let me know what u think man

**Comment by Spidy123222** [comment]
> ### Describe the bug
> 
> When adding [Quantumsource++](https://quarksources.github.io/#sources), this error happens:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/35177464/227286533-fcf4644a-3b99-474c-944c-72e21dc67a94.png)
> 
> 
> 
> The data couldn't be read because it isn't in the correct format.
> 
> E downloadURL:String or downloadURLs:[[Platform:URL]] key required.
> 
> 
> 
> The source loads fine on AltStore 1.6.2b.
> 
> ### Instructions to reproduce
> 
> Try to add the source https://bit.ly/Quantumsource-plus
> 
> ### What version of SideStore are you using?
> 
> 0.3.2-pr.311+875b25c
> 
> ### Other info
> 
> _No response_

Sidestore is using a older version of altstores source system. Might be good time to update it idk.

**Comment by stossy11** [comment]
Try Adding this Repo https://quarksources.github.io/quantumsource++.json because bitly might be messing some stuff up

**Comment by naturecodevoid** [comment]
Known issue

**Comment by preland** [comment]
Has there been any progress in fixing this issue?

**Comment by naturecodevoid** [comment]
No, there's a lot of AltStore additions we haven't cherry picked

**Comment by Spidy123222** [comment]
We should now support altstore 2.0 sources closing this issue until further notice.

**Comment by lorebored** [comment]
It doesn't work now
