### ISSUE TITLE
first start ends with error 512 after putting the mobiledevicepairing

### ISSUE THREAD

**Issue by menotuu** [SideStore/SideStore#316]
### Describe the bug

ios 16.3.1
I have installed sidestore with sideloadly because altstore have loginloop for me. is that a problem?
using windows to generate and put it in sidestore I received the following error.

![1](https://user-images.githubusercontent.com/38182429/227392283-2ac33ec6-9d92-499d-bde9-d0ac1cf84460.PNG)
![2](https://user-images.githubusercontent.com/38182429/227392288-740e954e-6d58-4c49-9a5d-438f6251c526.PNG)
![3](https://user-images.githubusercontent.com/38182429/227392290-dc21e300-9828-494a-8b0f-3761264c6e12.PNG)
![4](https://user-images.githubusercontent.com/38182429/227392294-f256b5e1-e0ea-4908-9b6c-46f481870a1f.PNG)

### Instructions to reproduce

reinstall sidestore and regenerating the mobiledevicepairing giving the same error code 512

### What version of SideStore are you using?

0.3.1

**Comment by naturecodevoid** [comment]
sideloadly is not supported
