### ISSUE TITLE
[BUG] Install SideStore Nigtly IPA

### ISSUE THREAD

**Issue by DevKoen** [SideStore/SideStore#318]
### Describe the bug

How can i install sidestore nightly ipa with the provising file not found bug

### Instructions to reproduce

?

### What version of SideStore are you using?

?

**Comment by likereadboy** [comment]
no provisioning profile 's bug is fixed by update altstore to 1.6.2, but sidestore0.3.1 not fixed it yet

**Comment by naturecodevoid** [comment]
check discord for test build
