### ISSUE TITLE
SideStore will not complete installation with public JITStreamer

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#32]
SideStore will stall with the progress bar mostly completed, right after `Successfully sent app data (XXXXXXXX bytes)`, and the server never actually installs the app on the device.

This issue only occurs when using the JITStreamer server, a local instance of SideServer works fine.

**Comment by JJTech0130** [comment]
This is no longer relevant, as JITStreamer has removed SideStore functionality on the production server.

**Comment by jkcoxson** [comment]
*salute*
