### ISSUE TITLE
[BUG] Unable to connect to the device

### ISSUE THREAD

**Issue by likereadboy** [SideStore/SideStore#320]
### Describe the bug

when install app with sidestore 0.3.2nightly.2023.03.21.1 version, keep wireGuard connected error happens: The operation couldn’t be completed. Unable to connect to the device, make sure Wireguard is enabled and you're connected to WiFi

### Instructions to reproduce

update to 0.3.2nightly.2023.03.21.1,connect the vpn as usual,install app

### What version of SideStore are you using?

0.3.2nightly.2023.03.21.1

**Comment by likereadboy** [comment]
![0DA4BD5B-4667-42CA-8D5D-484D3DE68CA3](https://user-images.githubusercontent.com/11569116/227698239-4dd204a6-54fe-4380-ae5e-7baaa382f80e.png)

**Comment by yyyfffccc** [comment]
+1

**Comment by Alex-Simedrea** [comment]
+1

**Comment by yangy666** [comment]
+1,同样的问题

**Comment by likereadboy** [comment]
https://github.com/SideStore/SideStore/files/11060913/Sidestore.Fix.zip
this really fixed it

**Comment by naturecodevoid** [comment]
what IPA is that?

**Comment by likereadboy** [comment]
0.3.2-nightly.2023.04.02.1 which released four days ago fixed this issue too

**Comment by Ilikeburgers123** [comment]
can someone tell me how to install that

**Comment by neoighodaro** [comment]
Still have it on the latest
