### ISSUE TITLE
[BUG] No effect with WDBRemove

### ISSUE THREAD

**Issue by le332313** [SideStore/SideStore#326]
### Describe the bug

No effect with WDBRemove，The same for reboot use ，didn't work

### Instructions to reproduce

Only 3 apps can be installed all the time，

### What version of SideStore are you using?

0.3.2

**Comment by Spidy123222** [comment]
0.3.2 doesn't have mdc addition please refer to https://github.com/SideStore/SideStore/pull/259

Until this is merged then we might have a build but intel then we don't.

**Comment by naturecodevoid** [comment]
MDC test build is in our discord

**Comment by baraa272** [comment]
> MDC test build is in our discord

Where ??
I'm in discord server and can't find anything in announcement

**Comment by naturecodevoid** [comment]
I believe it's in #general in pinned messages in the JitStreamer discord server
