### ISSUE TITLE
Blank Screen when opening SideStore

### ISSUE THREAD

**Issue by e-maximilian** [SideStore/SideStore#328]
### Describe the bug

Blank Screen when opening SideStore.
![IMG_3377](https://user-images.githubusercontent.com/2749152/228535410-cbc87ced-d1cc-465f-800d-5f1511ca7d36.png)

### Instructions to reproduce

Intermittent, it just suddenly happen, and it will stay blank, even force close and restart the device.

### What version of SideStore are you using?

0.3.2-pr.311+6baba4e

### Other info

iOS 16.4

**Comment by naturecodevoid** [comment]
don't use that IPA, if you must you need to delete sidestore.log in the files app after each time you close sidestore, you can automate this with a shortcut

**Comment by e-maximilian** [comment]
That IPA fixed the non provision and stuck at refreshing.
Can you recommend which IPA should I use?
Thanks.

**Comment by naturecodevoid** [comment]
you can try this one: https://github.com/SideStore/SideStore/suites/11811870084/artifacts/616639517

**Comment by e-maximilian** [comment]
Thanks!!

**Comment by shyney7** [comment]
Im having the same issue with my ipad air. I reinstalled Sidestore because I forgot to refresh it and after reinstalling it with altserver I now just have a black/blank screen when launching sidestore. Reinstalling doesnt fix it.
