### ISSUE TITLE
[BUG] can't open sidestore the next day after installing it，

### ISSUE THREAD

**Issue by le332313** [SideStore/SideStore#331]
### Describe the bug

can't open the sidestore the next day after installing it，  Flashback, without any error message，All versions of the sidestore have been tried，Same results，

### Instructions to reproduce

used altstore install，ios 15.7.1 13pm  

### What version of SideStore are you using?

0.3.2/0.3.1

**Comment by naturecodevoid** [comment]
AltStore and SideStore are known to be incompatible, SideStore may crash if AltStore is still installed
