### ISSUE TITLE
[BUG] SideStore crashed when opening, it was normal for around 2 days

### ISSUE THREAD

**Issue by e-maximilian** [SideStore/SideStore#334]
### Describe the bug

Installed SideStore Nightly 0.3.2-nightly.2023.04.02.1, was working well for 2 days, but today 4th April 2023, crashed when opening. Checked the folder there's no sidestore.log generated.
iOS 16.4 - iPhone 14 Pro.

P.S.: on my iPad Pro iPadOS 16.4, SideStore still can be opened, but unable to refresh with error "cannot connect to device, please make sure WireGuard connected.....", even-though my WireGuard is active.

### Instructions to reproduce

Open it on 3rd day, and it will crash. (at least on my iPhone).

### What version of SideStore are you using?

0.3.2-nightly.2023.04.02.1

**Comment by naturecodevoid** [comment]
go into settings > privacy > analytics & improvements > analytics data and search (scroll up) for SideStore, then choose the one with the most recent date and share it here

**Comment by e-maximilian** [comment]
[SideStore-2023-04-01-162614.ips.txt](https://github.com/SideStore/SideStore/files/11157499/SideStore-2023-04-01-162614.ips.txt)

Fyi, all the devices (my iPad, my other iPhone) now has same issue, SideStore crashes on opening on 3rd day.

**Comment by naturecodevoid** [comment]
I've never seen this crash before, not sure what it's caused by. Do you have AltStore still installed?

**Comment by e-maximilian** [comment]
![IMG_4CF8E38023EB-1](https://user-images.githubusercontent.com/2749152/230275561-ffbd713c-895d-4019-a08c-cd56f0e13d09.jpeg)

After reading discord, and I checked the settings, it's actually because the SideStore become Unverified.

Is there any fix currently?

**Comment by nextDNSconfig** [comment]
Fix: reinstall Sideload nightly.
It is working great for days now!

**Comment by Bhavinjain260** [comment]
Is this issue resolved? I faced the same issue, so I switched back to AltStore.

**Comment by sonalder-darlene** [comment]
> Refresh SideStore immediately after installation

When I do that following the official instructions the app became unusable.. It go back to my homescreen, I see it updating or refreshing whatever, then when I try to open it again it keeps crashing. I tried to wait, restart my phone, reinstalling SideStore, etc... it keeps crashing.

**Comment by sonalder-darlene** [comment]
> Install SideStore.ipa into SideStore without refreshing it, then refresh it

Seems to work thx !
