### ISSUE TITLE
Allow the sideloading of large size apps

### ISSUE THREAD

**Issue by abhishekgi** [SideStore/SideStore#335]
### Describe the feature

This feature must be added as the large size ipa could not be loaded on sidestore/altstore but by clicking shift and using sideload ipa option of altserver large size ipa could be loaded but the ipa loaded using altserver's sideload ipa option doesn't appear in altstore/sidestore means they cannot be refreshed with the help of altstore/sidestore 
So please make ipa installed by altserver's sideload ipa show in altstore/sidestore or allow the sideloading of large ipa with side store/altstore 

### Use cases

Could be helpful for many things 
Can install large size ipa

**Comment by naturecodevoid** [comment]
we are planning to allow adding previously sideloaded apps into the My Apps section

**Comment by abhishekgi** [comment]
That is nice
