### ISSUE TITLE
[BUG] There is no provisioning profile with the requested identifier on this team

### ISSUE THREAD

**Issue by iTristan2b2t** [SideStore/SideStore#336]
### Describe the bug

Whenever I try to sideload any app (from repo or ipa) it just says There is no provisioning profile with the requested identifier on this team.

### Instructions to reproduce

Try to sideload any app.

### What version of SideStore are you using?

SideStore 0.3.1

**Comment by naturecodevoid** [comment]
fixed in nightly, however it is better to use a build from our discord in #announcements

**Comment by DarkPheonix2122** [comment]
Still says it to me

**Comment by DarkPheonix2122** [comment]
Still says it to me, I got the newest version of sidestore. Using a burner Apple ID but I get that error

**Comment by DarkPheonix2122** [comment]
Still says it to me, I got the newest version of sidestore. Using a burner Apple ID but I get that error

**Comment by naturecodevoid** [comment]
> it is fixed in nightly
newest stable release is not nightly
