### ISSUE TITLE
Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by EriTang** [SideStore/SideStore#34]
/Users/eritang/Dropbox/Macerror build: Stored properties cannot be marked potentially unavailable with '@available'

**Comment by JJTech0130** [comment]
Try changing the build target from iOS 12.2 to iOS 14

**Comment by EriTang** [comment]
I'm trying to build

**Comment by JJTech0130** [comment]
Yes, in XCode, change the target version of iOS for AltStore to 14

**Comment by JJTech0130** [comment]
Keeping this open until #17 is merged
