### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by phoenix-x** [SideStore/SideStore#341]
### Describe the feature

Can I add a wireguar in the surge？I tried to put the configuration in Wireguard directly into surge, but it doesn't seem to work properly.
![414A0E60-5806-45BE-B425-059818D42459](https://user-images.githubusercontent.com/68410123/231625242-dd41dc89-edae-4fc3-a4c2-c16c4edfdb95.jpeg)

### Use cases

This can achieve true automatic refresh in a sense, without frequently turning on or off the wireguard.

**Comment by naturecodevoid** [comment]
I don't think surge works

**Comment by phoenix-x** [comment]
Yes, large doesn't make sidestore work properly, at least I can't try. I thought the Wireguard configuration in Surge was the same as in Wireguard. It is reasonable to write a large configuration.
