### ISSUE TITLE
[BUG] can't enable JIT

### ISSUE THREAD

**Issue by likereadboy** [SideStore/SideStore#342]
### Describe the bug

can not enable JIT to apps

### Instructions to reproduce

choose an app and try to enable JIT on it,this issue appears

### What version of SideStore are you using?

0.3.2.2023.04.13

### Other info

![Uploading 3EFFC2A2-C5EB-4EAC-9AC3-F8CED89A3E08.png…]()

**Comment by likereadboy** [comment]
![A60F8E6B-A62B-44E3-A1F2-A898DB4E663E](https://user-images.githubusercontent.com/11569116/231901282-1d58a751-02a6-47ee-b06d-b4e24714aeb8.png)

**Comment by naturecodevoid** [comment]
minimuxer logs? there are in Settings > View Error Log > bug icon in the top left corner. also, have you tried making a new pairing file?

**Comment by naturecodevoid** [comment]
please reopen if you have logs/tried a new pairing file
