### ISSUE TITLE
[BUG] Unable to singin -36607 on login

### ISSUE THREAD

**Issue by AkselGlyholt** [SideStore/SideStore#345]
### Describe the bug

When I'm trying to login after I've installed sidestore on my phone it just says "Unable to singin -36607"

### Instructions to reproduce

Go to settings and sign in with Apple ID

### What version of SideStore are you using?

0.3.1

**Comment by naturecodevoid** [comment]
please use another anisette server or host your own (see https://wiki.sidestore.io)

or, you can help test anisette v3, which should fix these issues, check jitstreamer discord #announcements for more info
