### ISSUE TITLE
[BUG] “Refresh all apps” iOS shortcut always fails due to reinstallation of SideStore application.

### ISSUE THREAD

**Issue by hurryman2212** [SideStore/SideStore#347]
### Describe the bug

**“Refresh all apps” iOS shortcut will never complete** normally due to the fact that during the refresh of the SideStore application, it will be reinstalled while the shortcut is still running.

The shortcut still manages to refresh all apps though.

### Instructions to reproduce

Execute “Refresh all apps” iOS shortcut with the Apr.16 version installed. The error “Could not run Refresh All Apps - **The operation took too long to complete. Please try again.**” will be invoked. Still, the refresh will be successful and the error will be limited to the running process of the iOS shortcut.

### What version of SideStore are you using?

0.3.2-nightly.2023.04.16.1+07533e0

### Other info

_IMO, implementing #337 would be helpful for more variety of situations and future bugs._

**Comment by naturecodevoid** [comment]
this will not happen. refresh all reinstalls sidestore last, and reinstalling sidestore will automatically close sidestore after a few seconds. so most likely your issue is something else

**Comment by hurryman2212** [comment]
> this will not happen. refresh all reinstalls sidestore last, and reinstalling sidestore will automatically close sidestore after a few seconds. so most likely your issue is something else

I’ve added more comments to the main issue. I forgot to mention that the actual refresh will be successful. The problem is the iOS shortcut cannot progress after the SideStore shortcut function as it “fails” on its stage.

**Comment by naturecodevoid** [comment]
that makes more sense, in that case we will need to implement the workaround where we trigger background refresh using minimuxer. we talked about this a day or two ago, but haven't implemented it

**Comment by jirikrepl** [comment]
For me, altstore shortcut never worked. I always got error mentioned above, but the app (taurine) was never refreshed. What about implementing a new shortcut, where only the selected app will be refreshed? Not all apps.

my current shortcut with screenshots and video:
I also had some other error when trying to automate it, for me, shortcuts never worked.

![B485089B-0613-4377-BDE2-06E4D62E5892](https://user-images.githubusercontent.com/2588479/233914230-1551a194-6c3e-4b84-a2a9-b14a219a4a01.png)

![5EFED018-9FF9-4724-93D7-E80F3A04F87B](https://user-images.githubusercontent.com/2588479/233914273-00876c85-324b-4c57-ab32-39c1e50e2dac.png)

https://user-images.githubusercontent.com/2588479/233914726-ffe854a8-34a3-4224-ae98-865f7ab3359c.mov




![3D7CEF5C-55D2-4EFC-A0A5-446E7160C338](https://user-images.githubusercontent.com/2588479/233914309-e31fdf68-5764-40fd-92e8-7f8992491bc0.png)

**Comment by lifedeathandtech** [comment]
Any updates on implementing the workaround? The shortcut still refreshes all apps successfully, but It would be great to be able to suppress these "Automation failed" notifications.

_Could Not Run Refresh All Apps
The file doesn't exist._

![error](https://github.com/SideStore/SideStore/assets/114445737/e213d267-ae67-489f-9536-273ad0438f0a)

SideStore 0.5.1
iOS 17.0

**Comment by le0-VV** [comment]
Still happening in almost the exact same manner in 0.5.4 on iOS 17.3.1, I'm actually considering to go back to AltStore with this bug

**Comment by Xyrhenix** [comment]
> Any updates on implementing the workaround? The shortcut still refreshes all apps successfully, but it would be great to be able to add more actions after the "Refresh All Apps" step, as well as suppress these "Automation failed" notifications.
> 
> _Could Not Run Refresh All Apps The file doesn't exist._
> 
> ![error](https://private-user-images.githubusercontent.com/114445737/269702900-e213d267-ae67-489f-9536-273ad0438f0a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Nzc4OTYsIm5iZiI6MTcxMjY3NzU5NiwicGF0aCI6Ii8xMTQ0NDU3MzcvMjY5NzAyOTAwLWUyMTNkMjY3LWFlNjctNDg5Zi05NTM2LTI3M2FkMDQzOGYwYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTU0NjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ3YjAyNWExZDYxYWZiYzY2OGM1ZjM2OTNkMmZjOWVhNzFlMWMzYTBhNGI2MTBjOTc3YjkxYWNhNGRiNTIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SQZOk3mjUl7yx4_YIBuqD16pOqDFV0F2rZ0CrX8Um8I)
> 
> SideStore 0.5.1 iOS 17.0

In this particular case, I found that duplicating the `.mobiledevicepairing` file and assigning it the name `ALTPairingFile.mobiledevicepairing` *seems* to help.  For example, normally you would only have one file with that ending and it would be a string around 25 characters long.  I found that by cloning this file and naming as mentioned above the automatic refresh seems to work fine.  Both `.mobiledevicepairing` files would reside within the SideStore folder on your device simultaneously.

This enables a shortcut to refresh SideStore, though annoyingly you *will* continue to get an error—specifically, Shortcuts says "The operation took too long to complete. Please try again.".  Despite the error, the refresh does still occur as-expected.

**Comment by hurryman2212** [comment]
> > Any updates on implementing the workaround? The shortcut still refreshes all apps successfully, but it would be great to be able to add more actions after the "Refresh All Apps" step, as well as suppress these "Automation failed" notifications.
> > _Could Not Run Refresh All Apps The file doesn't exist._
> > ![error](https://private-user-images.githubusercontent.com/114445737/269702900-e213d267-ae67-489f-9536-273ad0438f0a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Nzc4OTYsIm5iZiI6MTcxMjY3NzU5NiwicGF0aCI6Ii8xMTQ0NDU3MzcvMjY5NzAyOTAwLWUyMTNkMjY3LWFlNjctNDg5Zi05NTM2LTI3M2FkMDQzOGYwYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTU0NjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ3YjAyNWExZDYxYWZiYzY2OGM1ZjM2OTNkMmZjOWVhNzFlMWMzYTBhNGI2MTBjOTc3YjkxYWNhNGRiNTIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SQZOk3mjUl7yx4_YIBuqD16pOqDFV0F2rZ0CrX8Um8I)
> > SideStore 0.5.1 iOS 17.0
> 
> In this particular case, I found that duplicating the `.mobiledevicepairing` file and assigning it the name `ALTPairingFile.mobiledevicepairing` _seems_ to help. For example, normally you would only have one file with that ending and it would be a string around 25 characters long. I found that by cloning this file and naming as mentioned above the automatic refresh seems to work fine. Both `.mobiledevicepairing` files would reside within the SideStore folder on your device simultaneously.
> 
> This enables a shortcut to refresh SideStore, though annoyingly you _will_ continue to get an error—specifically, Shortcuts says "The operation took too long to complete. Please try again.". Despite the error, the refresh does still occur as-expected.

Refresh itself will be done normally without anything to be done. The problem here is after the SideStore's action, because of the error, any other actions cannot be done.

**Comment by Xyrhenix** [comment]
> Refresh itself will be done normally without anything to be done.

I'm not understanding what is meant by this.  Could you offer a rephrasing?

> The problem here is after the SideStore's action, because of the error, any other actions cannot be done.

I believe this is why this issue thread exists.  Shortcuts will fail at the "Refresh All Apps" stage, wherever that stage is, because SideStore is reinstalled and cannot signal to the shortcut that the operation was completed successfully.

My previous comment was primarily to help out another person who was commenting on this issue regarding a different error which I knew how to resolve.  Their issue did require specific action to resolve, and I know this from experience.
