### ISSUE TITLE
[FEATURE REQUEST] Enable JIT with Shortcuts or URL Schemes

### ISSUE THREAD

**Issue by Zhou-Shilin** [SideStore/SideStore#348]
### Describe the feature

_Google Translated: Chinese -> English_
Using Shortcuts or URL Schemes to open a app with JIT.
For example,  
(URL Scheme) `sidestore://enable-jit?bundle-id=net.kdt.pojavlauncher`
(Shortcuts) `Open <app> with JIT`

### Use cases

Shortcuts (Added in the home screen):  
```
Wireguard: Open <Tunnel/SideStore>
SideStore: Open <App/Pojavlauncher>
Wireguard: Close <Tunnel/SideStore>
```

**Comment by Spidy123222** [comment]
Duplicate of https://github.com/SideStore/SideStore/issues/166
