### ISSUE TITLE
Add support for "loopback" VPN so SideStore can install apps it's own device

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#35]
Just a tracking issue

**Comment by JJTech0130** [comment]
@jkcoxson is working on this in https://github.com/jkcoxson/Secret-Tunnel
Perhaps we can additionally integrate [Jitterbug's](https://github.com/osy/Jitterbug) tunnel if they select paid account in `CodeSigning.xcconfig`

**Comment by jkcoxson** [comment]
Once we modify/wrap libimobiledevice for raw TCP packets, it should be pretty easy to use any tunnel implementation.

**Comment by jkcoxson** [comment]
Waiting on #95
