### ISSUE TITLE
[BUG] There is no provisioning profile with the requested identifier on this team.

### ISSUE THREAD

**Issue by mnameisjeff** [SideStore/SideStore#350]
### Describe the bug

When refreshing or sideloading an IPA, the error “ There is no provisioning profile with the requested identifier on this team.” occurs.

### Instructions to reproduce

Refresh or side load an IPA

### What version of SideStore are you using?

SideStore 0.3.1

**Comment by naturecodevoid** [comment]
fixed in nightly
