### ISSUE TITLE
[FEATURE REQUEST] When will the MDC version for SIdestore be released?

### ISSUE THREAD

**Issue by sauzen** [SideStore/SideStore#351]
### Describe the feature

i want MDC version

### Use cases

many apps

**Comment by naturecodevoid** [comment]
you can check the website for a test build

**Comment by naturecodevoid** [comment]
i'll tell the developer to update it

**Comment by bananaSmoothie13** [comment]
awesome i was about to make the same request

**Comment by lingsoul** [comment]
> 

Could you tell me which link can be downloaded from? Thank you.

**Comment by bananaSmoothie13** [comment]
https://cdn.discordapp.com/attachments/949183273827983370/1088858243322871818/SideStore.ipa

**Comment by lingsoul** [comment]
> https://cdn.discordapp.com/attachments/949183273827983370/1088858243322871818/SideStore.ipa

Thank you. If there is an available MDC version, could you please help send the latest link

**Comment by bananaSmoothie13** [comment]
thats the one, anisette fix and MDC included,

**Comment by lingsoul** [comment]
> thats the one, anisette fix and MDC included,
When I download using the following link, the version is:0.3.2-nightly.2023.03.24.1,does not contain MDC
https://cdn.discordapp.com/attachments/949183273827983370/1088858243322871818/SideStore.ipa
