### ISSUE TITLE
[BUG] The MDC version on the official website, click to download or the old and unavailable version

### ISSUE THREAD

**Issue by lingsoul** [SideStore/SideStore#353]
### Describe the bug

The MDC version on the official website, click to download or the old and unavailable version
https://sidestore.io/  ---> 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/22099083/234443179-fe132c17-6332-46d8-81fd-89a4c3429eb8.png">

### Instructions to reproduce

Update to the latest available MDC version

### What version of SideStore are you using?

0.3.2-nightly.2023.04.02.1

**Comment by Spidy123222** [comment]
MDC build hasn't been updated is why it's not updated on site. It is manually created instead of automated like the others as it's technically not a mainline addition. We are thinking of way to add it to mainline without issues. The person that maintains it will update sometime soon.

**Comment by lingsoul** [comment]
> 

Thank you for your answer. Looking forward to it
