### ISSUE TITLE
[BUG] App says its not expired, but cannot open it. (expire early)

### ISSUE THREAD

**Issue by Zhou-Shilin** [SideStore/SideStore#356]
### Describe the bug

_Google Translated from Chinese -> English_
My sidestore isn't expired, but i cannot open it by clicking the icon on home screen.
But SideStore is in my backend, and I can open it through the backend.
And i can open pojavlauncher and wechat++ normally.
See the video:

https://user-images.githubusercontent.com/86581525/235296757-165e04dd-df89-4b95-8cc2-db94f293486f.mp4

### Instructions to reproduce

1. Install SideStore on you iDevice
2. Wait for a few days (<7)
3. Cannot open SideStore

### What version of SideStore are you using?

SideStore 0.3.2-pr.311+6baba4e

**Comment by Spidy123222** [comment]
This is part of the expire early issue we are currently having with sidestore and are making a fix for it. I would refresh sidestore immediately before it being in the background ends.

**Comment by Zhou-Shilin** [comment]
I just accidentally kill the program in the background and cannot open it again :(
