### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Skye-lol** [SideStore/SideStore#357]
### Describe the bug

on latest beta release (on discord) i still dont have the option to remove the 3 app limit although, i have cowabunga and removed the 3 app limit using that and it works on altstore.

Ive tried using 3 fingers to drag down but it doesn't show a MacDirtyCow section in it.

### Instructions to reproduce

be on ios 16.0.2, download latest app from dc, use 3 fingers to swipe up and see that its missing.

### What version of SideStore are you using?

SideStore-0.3.2-pr.3249766c22

**Comment by naturecodevoid** [comment]
you need to use an mdc build. the builds in discord #announcements specifically say they don't support mdc. mdc is pinned in one of the channels, however it's a bit outdated, I think a community member made an updated version

**Comment by Skye-lol** [comment]
ooh ok. thank you.

**Comment by Skye-lol** [comment]
on this version i get a provisioning profile error
