### ISSUE TITLE
[BUG] cant install Enmity

### ISSUE THREAD

**Issue by harisshaukat96** [SideStore/SideStore#360]
### Describe the bug

Unable to install a fresh Enmity .IPA as it gives the error “There is no provisioning profile with the requested identifier on this team.”

### Instructions to reproduce

Download and install a .IPA for Enmity at enmity.app

### What version of SideStore are you using?

0.3.2-nightly.2023.04.16.1

**Comment by naturecodevoid** [comment]
fixed in nightly
