### ISSUE TITLE
[BUG] reset pairing fails with sideserver

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#364]
### Describe the bug

When installing via sideserver it auto adds pairing file which is great but however once that pairing file expires you need to reset the pairing file. You select the pairing file and when you do that it intact doesn’t work because app is relying on the plist to have pairing data. When resetting pairing file it should stop using plist pairing data.

### Instructions to reproduce

- Install via sideserver
- Reset pairing file
- Restart sidestore
- No prompt for pairing file.

### What version of SideStore are you using?

Any version with pairing with sideserver

**Comment by SoY0ung** [comment]
SideServer may embed the pairing file to `Info.plist`, which is a read-only file.
SideStore read the pairing file from `Info.plist` firstly, then it will read `ALTPairingFile.mobiledevicepairing` from `/Document` if there’s no pairing file in `Info.plist`.

**Comment by pakboy221** [comment]
I have a question I have a SideStore I didn't download any application but it's said 0 apps remaining can anybody help me to fix that problem
