### ISSUE TITLE
"Unable to Launch AltStore" - can't save in Application Support

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#37]
This is more of a troubleshooting section (we need that), this issues is caused by a mismatched App Group.
Use PR #17 to fix.

**Comment by JJTech0130** [comment]
![C77D255A-2BA9-40D6-9002-CF65EBA84F06](https://user-images.githubusercontent.com/53275876/174169459-df9248a5-9b7c-4804-a3cb-1c74308f191e.jpeg)

**Comment by JJTech0130** [comment]
Actually, decided to keep it open until #17 is merged.

**Comment by imReker** [comment]
Get this error when Sidestore is installed with Sideloadly.

**Comment by JJTech0130** [comment]
> Get this error when Sidestore is installed with Sideloadly.

SideStore cannot be installed with Sideloadly right now, as Sideloadly does not inject the necessary configuration into the `Info.plist`.
