### ISSUE TITLE
[BUG] SideStore for iOS 16.6 public beta does not work because there is no supported dmg 

### ISSUE THREAD

**Issue by CivilBreak63501** [SideStore/SideStore#370]
### Describe the bug

It’s not letting me refresh my apps or enable jot

### Instructions to reproduce

Make a supported dmg for iOS 16.6 

### What version of SideStore are you using?

4.0

**Comment by naturecodevoid** [comment]
@Spidy123222

**Comment by naturecodevoid** [comment]
It seems no one has uploaded the DMG for 16.6 yet.

**Comment by CivilBreak63501** [comment]
When is it going to be released?

**Comment by Spidy123222** [comment]
> When is it going to be released?

When we get a developerdiskimage for iOS 16.6 which might be soon but unsure.
