### ISSUE TITLE
[BUG] unable to refresh apps on sidestore (iPhone 11, 16.6 beta 1

### ISSUE THREAD

**Issue by harisshaukat96** [SideStore/SideStore#372]
### Describe the bug

I am unable to refresh apps, I get the error “ An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (Could not connect to the server.). Please try again. If the issue persists, report it on GitHub Issues! “

### Instructions to reproduce

Refresh your apps 

### What version of SideStore are you using?

0.3.2-nightly

**Comment by drift7rs** [comment]
+1, unable to sign in on 0.4.0 with same error as OP

**Comment by naturecodevoid** [comment]
make sure preferred servers is off, use http://ani.sidestore.io:6969 as your anisette server

the server will go down every once and a while, you must retry later if it says the server may be down
