### ISSUE TITLE
[BUG] Sidestore crashing after 10s, wireguard VPN enable only

### ISSUE THREAD

**Issue by trcminh** [SideStore/SideStore#375]
### Describe the bug

When i open sidestore without enable wireguard vpn, nothing happend
The app will crash after 10s when vpn enable, although i do nothing and it automatically crash

### Instructions to reproduce

1. Enable Wireguard vpn (Config file i got from official website)
2. Open sidestore app and it will crash after 10s

### What version of SideStore are you using?

0.4.0 (i try older ver and it still happend)

### Other info

i try change anisset server, delete log file, restart phone and nothing work
it start happend when i delete sidestore to fresh install 0.4.0
Iphone 7, ios 15.7.6
Lastest analytic file: 
[SideStore-2023-06-08-092036.txt](https://github.com/SideStore/SideStore/files/11683665/SideStore-2023-06-08-092036.txt)

**Comment by naturecodevoid** [comment]
should be temporarily fixed, but a full fix will be put in place eventually (you do not need to update SideStore)
