### ISSUE TITLE
[BUG] Crashes After Launching

### ISSUE THREAD

**Issue by NikauM** [SideStore/SideStore#377]
### Describe the bug

It works fine for 1 day but after that when I open the app it crashes instantly.

### Instructions to reproduce

Wait 1 Day
Open the App
(Crashes Instantly)

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment]
Do you still have AltStore installed?

**Comment by NikauM** [comment]
> 

Yes

**Comment by naturecodevoid** [comment]
That's why, SideStore has known compatibility issues with AltStore, you can try uninstalling AltStore (you might also need to do a fresh install of SideStore)
