### ISSUE TITLE
Provide a pre-built IPA

### ISSUE THREAD

**Issue by JJTech0130** [SideStore/SideStore#38]
This could be an extension of #22, providing build artifacts for every commit.
Not everybody has Xcode (Windows/Linux users), and it's very finicky and often refuses to cooperate and provide a viable artifact.

**Comment by JJTech0130** [comment]
[SideStore-PR21.ipa.zip](https://github.com/SideStore/SideStore/files/8923409/SideStore-PR21.ipa.zip)
[SideStore-PR17.ipa.zip](https://github.com/SideStore/SideStore/files/8923410/SideStore-PR17.ipa.zip)

**Comment by Practicalbutterfly5** [comment]
> > [SideStore-PR21.ipa.zip](https://github.com/SideStore/SideStore/files/8923409/SideStore-PR21.ipa.zip)
> > [SideStore-PR17.ipa.zip](https://github.com/SideStore/SideStore/files/8923410/SideStore-PR17.ipa.zip)
> 
> can you plz make with latest version?

Check GitHub actions, it is configured to make ipa for every commit.
