### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by vincvinc563** [SideStore/SideStore#381]
### Describe the feature

Hello, I know the app is still under development but I was wondering why it wasn't possible to refresh using only wifi and not 4g.

### Use cases

the ability to refresh the app when wi-fi is not available would be very convenient.

**Comment by Decoder0007** [comment]
not possible

**Comment by RandomModderJDK** [comment]
See https://github.com/orgs/SideStore/discussions/380

**Comment by RandomModderJDK** [comment]
You could try using

**Comment by Decoder0007** [comment]
It’s not possible on cellular because SideStore tricks your phone into thinking it’s on the same wifi network as a Mac that signs your apps. You can’t do this on cellular unless you join someone else’s hotspot

**Comment by RandomModderJDK** [comment]
If you host a hotspot yourself, can you still use Sidestore?

**Comment by Decoder0007** [comment]
No you have to join someone else’s hotspot

**Comment by naturecodevoid** [comment]
> It’s not possible on cellular because SideStore tricks your phone into thinking it’s on the same wifi network as a Mac that signs your apps. You can’t do this on cellular unless you join someone else’s hotspot

This is not true as far as I’m aware. We cannot use SideStore on cellular for a couple of reasons:
1. lockdownd refuses to respond over network if only cellular data is active, which prevents us from installing apps, activating JIT, etc
2. WireGuard refuses to enable if both cellular and Wifi are disabled. It hasn’t been investigated if this is hardcoded in the WireGuard app or if iOS disallows it.

If you have 2 devices, you can host a hotspot using one device and join that hotspot on the other device that has SideStore. Then, you can install and refresh apps.

**Comment by Spidy123222** [comment]
It’s already investigated that it’s WireGuard stopping connection. We were able to do stuff in jitterbug which hosts its own vpn if cellular was off or if airplane mode was on.
