### ISSUE TITLE
[BUG] Building sidestore with xcode fails

### ISSUE THREAD

**Issue by Decoder0007** [SideStore/SideStore#382]
### Describe the bug

I cloned and opened sidestore in xcode and the build fails with `This Copy Files build phase contains a reference to a missing file 'Roxas.framework'.`

### Instructions to reproduce

Open XCode
Clone Sidestore
Click build

### What version of SideStore are you using?

Latest source code I guess

**Comment by Decoder0007** [comment]
I fixed that issue but now I am met with `Command RuleScriptExecution failed with a nonzero exit code` for both `em_proxy-staticlib` and `minimuxer-staticlib`

**Comment by Decoder0007** [comment]
I fixed it. Xcode wasn’t downloading minimuxer or em_proxy

**Comment by MaximeCrp** [comment]
How did you fix the second error about em_proxy-staticlib and minimuxer-staticlib? I tried running command `bash ./Dependencies/fetch-prebuilt.sh force` but apparently everything was already up-to-date
Wonder if I should try building those as well

**Comment by Decoder0007** [comment]
git clone https://www.github.com/SideStore/Sidestore --recursive
