### ISSUE TITLE
The data is not in the correct format [BUG] 

### ISSUE THREAD

**Issue by Yumega** [SideStore/SideStore#390]
### Describe the bug

I can't login appleid on sidestore with iphoneX 
the error information is :
Failed to Log In
The data is not in the correct format.

### Instructions to reproduce

Failed to Log In
The data is not in the correct format.

### What version of SideStore are you using?

0.4.0

**Comment by Spidy123222** [comment]
When doing issues make sure to do a title. Anyways your issue is anisette server related issue. Change server. Recommend sidestore preset one as doesn't have locking issue.

**Comment by gadour97** [comment]
same here, any solutions?

**Comment by MattFrom72** [comment]
I'm having the same issue now

**Comment by naturecodevoid** [comment]
When this happens report the anisette server as down in discord
