### ISSUE TITLE
[BUG] Unable to log in to my Apple ID

### ISSUE THREAD

**Issue by KuaiCode** [SideStore/SideStore#391]
### Describe the bug

Unable to log in to my Apple ID. It displays "An error occurred when getting anisette datafrom a V3 server: Couldn't fetch client info. The server may be down (The network connection was lost.). Please try again. If the issue persists, report it on GitHub Issues!"

### Instructions to reproduce

Log in to Apple ID.

### What version of SideStore are you using?

0.4.0

**Comment by Spidy123222** [comment]
Our server restarts every so often it should be working by now unless your Wi-Fi is blocking it.

**Comment by KuaiCode** [comment]
Thank you!
