### ISSUE TITLE
[BUG] Select color is still green when you sign in

### ISSUE THREAD

**Issue by siieo** [SideStore/SideStore#392]
### Describe the bug

![0F757B3C-9B1C-4A1D-878A-16FE998282D3](https://github.com/SideStore/SideStore/assets/68543703/919f3d04-41d6-4301-9ca0-32cdc1ece3f1)d

### Instructions to reproduce

1. Open SideStore
2. Go to Settings
3. Tap on Sign in with Apple ID

### What version of SideStore are you using?

0.4.0

**Comment by Spidy123222** [comment]
This was resolved
