### ISSUE TITLE
[功能请求]When can I integrate into MacDirtyCow

### ISSUE THREAD

**Issue by lvzhimou** [SideStore/SideStore#393]
### Describe the feature

When can I integrate into MacDirtyCow

### Use cases

It can be more convenient for us to use

**Comment by naturecodevoid** [comment]
MDC is WIP, we already have a working build with it integrated

**Comment by lvzhimou** [comment]
> MDC是WIP，我们已经有一个集成的工作构建

But the provided download is not the latest version, and there is no relevant configuration prompt when using it

**Comment by naturecodevoid** [comment]
Correct, the new version is not properly tested yet and it is not released.

**Comment by Zhou-Shilin** [comment]
MDC不是每个版本都有的，只有一部分支持
> MDC is not available in every version, only some of them support

**Comment by Spidy123222** [comment]
We will not be adding mdc support anymore.
