### ISSUE TITLE
[BUG] Login takes infinite time

### ISSUE THREAD

**Issue by aaronliu0130** [SideStore/SideStore#394]
### Describe the bug

Login takes forever

### Instructions to reproduce

![image](https://github.com/SideStore/SideStore/assets/11874211/8c8e18fa-10ac-4610-9278-81c0b6d451b9)
1. Install with altstore and do a pairing file
2. Try to log in

### What version of SideStore are you using?

0.4.0

### Other info

The password field only looks blank because of Apple's screenshotting features
I have a custom anisette server at https://aaronisette.onrender.com if that matters

**Comment by dlfnn** [comment]
The same.

**Comment by aaronliu0130** [comment]
@dlfnn but I am using 0.4

**Comment by Spidy123222** [comment]
> ### Describe the bug
> 
> Login takes forever
> 
> ### Instructions to reproduce
> 
> ![image](https://github.com/SideStore/SideStore/assets/11874211/8c8e18fa-10ac-4610-9278-81c0b6d451b9)
> 
> 1. Install with altstore and do a pairing file
> 
> 2. Try to log in
> 
> ### What version of SideStore are you using?
> 
> 0.4.0
> 
> ### Other info
> 
> The password field only looks blank because of Apple's screenshotting features
> 
> I have a custom anisette server at https://aaronisette.onrender.com if that matters

Your server is inactive is why. You can click link in a browser and see it doesn't load anything.

**Comment by aaronliu0130** [comment]
![image](https://github.com/SideStore/SideStore/assets/11874211/4d2e0266-ed4d-4b0d-8c89-eb87dca08acb)
1. It's not inactive. You can click the link in a browser.
2. Why would my server authenticate an Apple login? Last time I check visiting Anisette servers won't prompt you for credentials

**Comment by dlfnn** [comment]
Maybe consider reinstalling (nvm if you've already done so). My problem is solved after reinstall.

**Comment by aaronliu0130** [comment]
Still didn't work.

**Comment by naturecodevoid** [comment]
have you tried v3 anisette? just use 0.4.0 and SideStore anisette server

**Comment by aaronliu0130** [comment]
Doesn't work either.

**Comment by Nythepegasus** [comment]
Hello! Could you try a recent nightly with the anisette server set to the default? If the problem persists, please feel free to reopen this issue!

**Comment by aaronliu0130** [comment]
Nope, the latest nightly is VERY old. I tried the newest release which solved this issue, thanks.

**Comment by naturecodevoid** [comment]
It's not. That's when the release was first created, check the build date. GitHub actions edits that release to include the latest nightly

**Comment by aaronliu0130** [comment]
Huh, that's very weird. Anyway I got the release solved either way so thanks.

**Comment by MaximeCrp** [comment]
I also have the same issue 
I'm on 0.5.1 and tried different anisette servers
