### ISSUE TITLE
[FEATURE REQUEST] An auto enable JIT feature

### ISSUE THREAD

**Issue by Creeper76** [SideStore/SideStore#395]
### Describe the feature

I think it would be cool if you could make it so that when you open an app, like dolphin emulator, auto enabled JIT.

### Use cases

Emulators that require JIT

### Alternatives

It could be like the refresh all apps shortcut but for enabling JIT

**Comment by naturecodevoid** [comment]
This will be possible when SideKit is ready but will require developers to use (probably, it may be compatible with AltKit)

**Comment by Spidy123222** [comment]
Duplicate of https://github.com/SideStore/SideStore/issues/166
