### ISSUE TITLE
[FEATURE REQUEST] better ipad ui for sidestore

### ISSUE THREAD

**Issue by neon443** [SideStore/SideStore#396]
### Describe the feature

I found a bug where apps are listed wrongly, see the image. I believe that this would be a great feature 
![B8DFBEAB-4EB6-442B-A50A-003E31FD6CA3](https://github.com/SideStore/SideStore/assets/69979447/53ab3488-f886-4229-bf6b-e40650713e22)

### Use cases

Just be easier to browse apps on ipad

**Comment by Nythepegasus** [comment]
Going to close in favor of #70.

We will work on this at some point, just not yet for a 1.0.0 release.
