### ISSUE TITLE
SideStore expires after force restarting the device

### ISSUE THREAD

**Issue by KieranBLK** [SideStore/SideStore#397]
### Describe the bug

After force restarting my iPhone I’ve noticed that SideStore consistently becomes unverified (4 times in total) and requires a fresh install to reverify.

### Instructions to reproduce

• Freshly install SideStore
• Force restart your iPhone by pressing volume down, up and holding power button until Apple logo appears. 
• After devices boots SideStore should no longer be verified and will crash upon attempt to open it. 

Note: It is possible for it to take multiple force restarts before SideStore is unverified. Repeat steps as needed. 

### What version of SideStore are you using?

v0.4.0

### Other info

Device: iPhone 11
iOS: 17 Developer Beta’s (1-2)

**Comment by Valvify** [comment]
Also happens on iPhone 13, iOS 16.5.1

**Comment by Termin4lyIns4ne** [comment]
iPhone 13 Pro Max 16.5 lasting less than a day signed here having to reload via AltStore since it does not like to use the old pairing file.

**Comment by Spidy123222** [comment]
> ### Describe the bug
> 
> After force restarting my iPhone I’ve noticed that SideStore consistently becomes unverified (4 times in total) and requires a fresh install to reverify.
> 
> ### Instructions to reproduce
> 
> • Freshly install SideStore
> 
> • Force restart your iPhone by pressing volume down, up and holding power button until Apple logo appears. 
> 
> • After devices boots SideStore should no longer be verified and will crash upon attempt to open it. 
> 
> 
> 
> Note: It is possible for it to take multiple force restarts before SideStore is unverified. Repeat steps as needed. 
> 
> ### What version of SideStore are you using?
> 
> v0.4.0
> 
> ### Other info
> 
> Device: iPhone 11
> 
> iOS: 17 Developer Beta’s (1-2)

Be judging how you installed sidestore you might of not refreshed sidestore after installing as that's part of the instructions and is one of the vital ways keeping it from expiring early. This isn't related to iOS versuon luckily.
