### ISSUE TITLE
[BUG] iPadOS 17 beta 2, cannot start afc server

### ISSUE THREAD

**Issue by BrianMak94** [SideStore/SideStore#398]
### Describe the bug

Cannot start AFC server after updating to iPadOS 17 beta 2. Tried updating pairing file. Not working. 

### Instructions to reproduce

Install ipados 17 beta 2. Install/update apps in SideStore. 0.4.0-nightly.2023.06.22.1+93a6272

### What version of SideStore are you using?

0.4.0-nightly.2023.06.22.1+93a6272

**Comment by BrianMak94** [comment]
Beta 3 too

**Comment by brunodeangelis** [comment]
I'm having the same issue but on 16.5.1

**Comment by TylerOlson** [comment]
Same issue on iOS 17 public beta 1.

**Comment by Spidy123222** [comment]
This issue is unrelated to iOS version. My suggestion now would be using latest sidestore for the moments but It's usually another connection issue or pairing file issue and has been mitigated with others in the discord server. I would try retrying a few extra times and should help.
