### ISSUE TITLE
[FEATURE REQUEST] Support altstore's remove 3-App Limit

### ISSUE THREAD

**Issue by chuwza** [SideStore/SideStore#399]
### Describe the feature

As you can see, the altstore has a built-in feature to remove three app restrictions. sidestore doesn't have this feature built-in, and it's very troublesome to implement this feature at the moment. could you please support it?
![20230625132351 (2)](https://github.com/SideStore/SideStore/assets/30049891/2ed2797e-b1a1-4be2-a6c1-9326a71f5591)

### Use cases

Expand the number of apps installed at the same time to 10

**Comment by naturecodevoid** [comment]
SideStore will have MDC built in, but it's not properly tested yet
