### ISSUE TITLE
Enable entry of custom Server ip addresses

### ISSUE THREAD

**Issue by jawshoeadan** [SideStore/SideStore#40]
Currently hardcoded to 69.69.0.1 and it would be idea if there were a way to change that

**Comment by JJTech0130** [comment]
Doesn't seem too hard, but we have other priorities to sort out first. If we get loopback working, it will kind of become irrelevant.

**Comment by JoeMatt** [comment]
added her 4320df15df944379bdf6ebcd2f9085d2f777c16f

**Comment by jkcoxson** [comment]
This is still a build time argument, I think the idea here is a configurable setting.

**Comment by JoeMatt** [comment]
> This is still a build time argument, I think the idea here is a configurable setting.

it's step 1, it's just a swift contestant now. easy to make a UI to override that string too now
