### ISSUE TITLE
Cannot start a debug server on this device 

### ISSUE THREAD

**Issue by abhishekgi** [SideStore/SideStore#400]
### Describe the bug

I can enable jit for 1-2 days , after that when I try to enable jit it says cannot start a debug server on this device, earlier it was working, However I can still install apps and refresh them but whenever I try to enable jit it says cannot start a debug server on this device . 

### Instructions to reproduce

Open sidestore 
Try to launch an emulator by enabling jit

### What version of SideStore are you using?

Latest stable build from sidestore website 

### Other info
I think this is not a duplicate of #217  because refreshing and installing apps works here

**Comment by abhishekgi** [comment]
![Screenshot_20230626-215815_Video Player](https://github.com/SideStore/SideStore/assets/84626229/2aabea20-813e-4064-a92f-61571e323a1d)

**Comment by ktalothegoat10** [comment]
Hello! I have had the same issue, when I updated to iPadOS 17 Developer Beta 4 I haven't been able to enable JIT, I have a Video.


https://github.com/SideStore/SideStore/assets/139594595/59837f16-5d21-41c4-8004-76566eaa67f0

**Comment by ktalothegoat10** [comment]
Whenever I want to enable JIT in SideStore I get an error that says "Unable to start Debug Server on this Device"
What version I'm using.
SideStore installed from Windows new Sideserver
Can Anyone please help, Thank you.

**Comment by naturecodevoid** [comment]
JIT is not supported on iOS/iPadOS 17

**Comment by abhishekgi** [comment]
> JIT is not supported on iOS/iPadOS 17

First of all I am on ios 16.6 
And have not read that I have said it's works for 1-2 days and after that this issue starts

**Comment by naturecodevoid** [comment]
I was responding to someone else who said that they were on iOS/iPadOS 17.

**Comment by abhishekgi** [comment]
Okay bro

**Comment by abhishekgi** [comment]
I am clear about one thing that this issue will surely occur if we power off our iOS devices and turn them back on ,but doesn’t mean that it only occurs due to power off

**Comment by Spidy123222** [comment]
> I am sure about one thing that this issue will surely occur if we power off our iOS devices and turn them back on ,but doesn’t mean that it only occurs due to power off

What's happening on power off and on is developer disk image gets unmourned and need to mount a new one. If internet is too slow because maybe disk image got removed in sidestore some how or it is outdated then it might fail getting image and continue doing debug process only to fail at the end. 

This could be fixed waiting for the install to finish instead of assuming. For user side did you can manually download developer disk image and put it in DMG directory in sidestore files location.

What also can be the case is that your pairing file revoked and needs to be replaced. Which is unknown what causes it to revoke but it does happen sometimes during updates.

**Comment by abhishekgi** [comment]
> > I am sure about one thing that this issue will surely occur if we power off our iOS devices and turn them back on ,but doesn’t mean that it only occurs due to power off
> 
> What's happening on power off and on is developer disk image gets un-mounted and need to mount a new one. If internet is too slow because maybe disk image got removed in sidestore some how or it is outdated then it might fail getting image and continue doing debug process only to fail at the end.
> 
> This could be fixed waiting for the install to finish instead of assuming. For user side did you can manually download developer disk image and put it in DMG directory in sidestore files location.
> 
> What also can be the case is that your pairing file revoked and needs to be replaced. Which is unknown what causes it to revoke but it does happen sometimes during updates.

explain me more that how can i dowload disk image and what to do next

**Comment by abhishekgi** [comment]
Today this issue has automatically disappeared from my ipad and the folder named dmg which was empty got filled with two files automatically 
![IMG_0810](https://github.com/SideStore/SideStore/assets/84626229/272ac79d-efff-4ae5-811b-f9532858b523)

**Comment by abhishekgi** [comment]
And now i can enable jit
