### ISSUE TITLE
[BUG] Can't create a Render Web Service for a Custom Anisette Server

### ISSUE THREAD

**Issue by NighterStyle** [SideStore/SideStore#401]
### Describe the bug

When trying to create a web service in Render using this "https://github.com/Dadoum/Provision.git" public git repository i get this error "An error occurred. There’s an error above. Please fix it to continue."

I tried to fork the repository but the error still occured.

### Instructions to reproduce

1.Try to create a new web service using this public git repository "https://github.com/Dadoum/Provision.git"

### What version of SideStore are you using?

v0.4.0

**Comment by naturecodevoid** [comment]
Use anisette v3

Set server to SideStore

**Comment by shalom-aviv** [comment]
@naturecodevoid 

Step by step I use this guide:
https://wiki.sidestore.io/Advanced/anisette-server/

and have the same issue.


When you write "Set server to SideStore", did you mean this link https://github.com/SideStore/SideStore?
But this repo seems not for Render Web Service.

Could you please describe what means "Use anisette v3"?  
In guide for Anisette Server used code from https://github.com/Dadoum/Provision.git

Thank you

**Comment by naturecodevoid** [comment]
Just use the built in SideStire anisette server.
