### ISSUE TITLE
[POTENTIAL BUG] School wifi blocks sidestore anisette server from fetching client info, preventing refreshes

### ISSUE THREAD

**Issue by TicTecOfficial** [SideStore/SideStore#404]
### Describe the bug

School wifi has SSL stuff(idk) that blocks sidestore’s anisette servers, this issue wasn’t present a few months ago.

### Instructions to reproduce

HOW TO REPRODUCE:
step 1: idk turn back time and go to school?
step 2: obtain wifi somehow
step 3: use sidestore and try refreshing an app

### What version of SideStore are you using?

Latest Nightly

**Comment by naturecodevoid** [comment]
This is not our problem, we can't do anything about it.
