### ISSUE TITLE
[BUG] SideStore unable to connect to device through wireguard after some time

### ISSUE THREAD

**Issue by mayank3183** [SideStore/SideStore#405]
### Describe the bug

App refresh on SideStore fails with following persistent error "Unable to connect to device, make sure Wireguard is enabled and you're connected to wifi"
I am using latest SideStore IPA 0.4.0 and Wireguard 1.0.16 on my iphone.

Way out to refresh the app is to restart the phone. Right after restarting it works for the first time but after some time it again will not work and give same error. 

I am using following versions:
SideStore: 0.4.0
IOS: 15.7.4
WireGuard: 1.0.16(27)

I could see this same issue has been reported on earlier version too and all those Jira are closed but seems it is still not completely resolved https://github.com/SideStore/SideStore/issues/320

### Instructions to reproduce

1. Try to refresh the license on SideStore when WireGuard is enabled and running for 1 day. 
2. Refreshing any license will give following error "Unable to connect to device, make sure Wireguard is enabled and you're connected to wifi"
3. Restart your phone
4. Re-enable WireGuard and try to refresh now, it should work.
5. Again try to refresh license next day. It would fail with same error again.

### What version of SideStore are you using?

0.4.0

**Comment by jimmysofat6864** [comment]
Same issue fireguard seems to disconnect for no reason as well.

**Comment by mayank3183** [comment]
I do not think it is a wireguard issue. SideStore seems to have lost the initial connection with wireguard or something. Saying so as wireguard VPN is running when when sidestore complains for it.

**Comment by huweiunique** [comment]
I have also encountered the same issue. Restarting the phone and refreshing usually solves the problem. It seems that after a certain period of time, SideStore is unable to connect to the VPN, even though I am constantly connected to Wi-Fi and have the VPN enabled.

**Comment by Spidy123222** [comment]
> ### Describe the bug
> 
> 
> 
> App refresh on SideStore fails with following persistent error "Unable to connect to device, make sure Wireguard is enabled and you're connected to wifi"
> 
> I am using latest SideStore IPA 0.4.0 and Wireguard 1.0.16 on my iphone.
> 
> 
> 
> Way out to refresh the app is to restart the phone. Right after restarting it works for the first time but after some time it again will not work and give same error. 
> 
> 
> 
> I am using following versions:
> 
> SideStore: 0.4.0
> 
> IOS: 15.7.4
> 
> WireGuard: 1.0.16(27)
> 
> 
> 
> I could see this same issue has been reported on earlier version too and all those Jira are closed but seems it is still not completely resolved https://github.com/SideStore/SideStore/issues/320
> 
> 
> 
> ### Instructions to reproduce
> 
> 
> 
> 1. Try to refresh the license on SideStore when WireGuard is enabled and running for 1 day. 
> 
> 2. Refreshing any license will give following error "Unable to connect to device, make sure Wireguard is enabled and you're connected to wifi"
> 
> 3. Restart your phone
> 
> 4. Re-enable WireGuard and try to refresh now, it should work.
> 
> 5. Again try to refresh license next day. It would fail with same error again.
> 
> 
> 
> ### What version of SideStore are you using?
> 
> 
> 
> 0.4.0
> 
> 
> 
> ### Other info
> 
> 
> 
> _No response_

You should try using a more recent version of sidestore which helps with this a bit but the issue is our connection systems disconnects sometimes and interestingly it starts working after retrying a few times, usually 5-6 tries and then it usually would connect and do whatever action is needed.

There is a issue with WireGuard app itself where it kicks the boot on the vpn connection also so that's also a factor is to check your local vpn conenction.

**Comment by ziembar** [comment]
lol, in my case i had to spam a download button to make it work

**Comment by briangabini** [comment]
> lol, in my case i had to spam a download button to make it work

This worked for me.

**Comment by xsompyx** [comment]
turn on the airplane mod and the Wi-Fi at same time it worked for me

**Comment by jimmysofat6864** [comment]
I’ve been either spamming download or flicking wireguard on and off but one
of the two things works temporarily.

**Comment by moonvip-debug** [comment]
same problem and now i have to reinstall

**Comment by moonvip-debug** [comment]
> same problem and now i have to reinstall

and oh shiet reinstall is not working

**Comment by subhan-adsurgeai** [comment]
Still facing this issue
Was it fixed or the issue just got closed and not fixed at all?

**Comment by jimmysofat6864** [comment]
I still have the same issue it wasn’t fixed I instead resorted to using iOS
shortcuts to automate it.

**Comment by junepark678** [comment]
this is not for support, please use the discord server for that
