### ISSUE TITLE
[BUG] SideStore app crashes 1 day later

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#407]
### Describe the bug

The side store app crashes 1 day after installation. I already removed AltStore from my iPhone. In the developer settings it shows that the app is not verified but all my other apps show up as verified. This shouldn't have happened in one day as it should have lasted for 7. 

### Instructions to reproduce

Wait one day after installation and then attempt to open the app. It will crash immediately upon launch but my other apps work fine. 

### What version of SideStore are you using?

0.4.0

### Other info
![IMG_2110653EE106-1](https://github.com/SideStore/SideStore/assets/69532417/f5109b2d-9b49-4429-914c-d3c4a6e23350)

_No response_

**Comment by naturecodevoid** [comment]
Can you send the crash report? Someone reported this to me via DMs and apparently it was fixed by using a fresh install of nightly

**Comment by jimmysofat6864** [comment]
> Can you send the crash report? Someone reported this to me via DMs and apparently it was fixed by using a fresh install of nightly

@naturecodevoid How do I send crash report? The app doesn't open. Or do I get the one from the iOS settings?

**Comment by naturecodevoid** [comment]
go into settings > privacy > analytics & improvements > analytics data and search (scroll up) for SideStore, then choose the one with the most recent date and send it here (or, if you're worried about it sharing info such as phone model and team ID, send it to me on discord @naturecodevoid)

**Comment by jimmysofat6864** [comment]
@naturecodevoid Already sent and I was only able to locate only one file.

**Comment by naturecodevoid** [comment]
Oh wait, I didn't see the screenshot, your SideStore just expired early, you may have to fresh install
Also, I don't believe you sent the crash report
