### ISSUE TITLE
[BUG] Widget does not work

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#408]
### Describe the bug

Trying to use the widget to show remaining days left before requiring resigning doesn't work. It just shows app not found for some reason. Even editing the widget and selecting the app doesn't work. 

### Instructions to reproduce

Attempt to place the side store widget on the Home Screen and it will not work. 

### What version of SideStore are you using?

0.4.0

### Other info

![IMG_0950](https://github.com/SideStore/SideStore/assets/69532417/57b673e2-737c-498f-8794-a0110bd9e2a8)

_No response_

**Comment by naturecodevoid** [comment]
Known issue and probably duplicate
