### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NourozAli** [SideStore/SideStore#411]
### Describe the bug

My sidestore keeps crashing it was working fine one day before in the sitting i see it not verified i was try to do that but it is not working what i have to do ? 

I should fresh reinstall or there is anyway ? 

### Instructions to reproduce

It is crashing i have the latest version of sidestore 

### What version of SideStore are you using?

Latest version

**Comment by naturecodevoid** [comment]
1. Latest version is not helpful. While we know it's probably 0.4.0, you should put the actual version number
2. Crash report? go into settings > privacy > analytics & improvements > analytics data and search (scroll up) for SideStore, then choose the one with the most recent date and send it here or send it to me on discord @naturecodevoid 
3. Is SideStore expired? Check that in settings > general > profiles and find your profile and see it has Not Verified next to SideStore

**Comment by NourozAli** [comment]
Yeah it is Not verified i am going to send the date now

**Comment by naturecodevoid** [comment]
You got early expire, try fresh install
