### ISSUE TITLE
[BUG] Sidestore app constantly unverifying itself 1-2 days later randomly

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#413]
### Describe the bug

For some reason, when I go to open Sidestore maybe 1 or 2 days later, I go to find out that the sidestore app has unsigned itself for no reason when all my other apps remain signed. In other words, the SideStore app stops working but all my other apps keep working. Reinstalling the SideStore app multiple times has not fixed the issue. 

![252198783-f5109b2d-9b49-4429-914c-d3c4a6e23350](https://github.com/SideStore/SideStore/assets/69532417/b29aa530-a8a9-427a-b695-5314b1767e9e)

### Instructions to reproduce

1. Install sidestore
2. Install some apps
3. Come back a few days later
4. Return to see sidestore has unsigned itself but my other apps stay signed

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment]
Known issue, duplicate I think

Your best bet is to do a fresh install

**Comment by jimmysofat6864** [comment]
> 

Fresh install has been tried multiple times without success.

**Comment by naturecodevoid** [comment]
Do you refresh SideStore immediately after installing?

**Comment by grunkl** [comment]
The same issue happens with me. I can confirm I am refreshing the app immediately after install, but appox 24hrs later, usually by the morning, all apps are unverified again.

**Comment by jimmysofat6864** [comment]
> Do you refresh SideStore immediately after installing? According to spidy, not refreshing SideStore ASAP is usually what causes this

Yes I do that always but it still occurs.

**Comment by sysconf16** [comment]
> > Do you refresh SideStore immediately after installing? According to spidy, not refreshing SideStore ASAP is usually what causes this
> 
> Yes I do that always but it still occurs. It's only the SideStore app that unsigns itself but the other apps appear just fine for whatever reason.

Can confirm I am also experiencing this issue with one device. Oddly enough, another device reacts completely fine and refreshes/expires as normal.

**Comment by Spidy123222** [comment]
This issue gets fixed often in discord by right after installing sidestore is to refresh before installing apps.

**Comment by sysconf16** [comment]
> This issue gets fixed often in discord by right after installing sidestore is to refresh before installing apps.

I have always done this after installing SideStore, yet the problem re-occurs regardless.

**Comment by Spidy123222** [comment]
> > This issue gets fixed often in discord by right after installing sidestore is to refresh before installing apps.
> 
> 
> 
> I have always done this after installing SideStore, yet the problem re-occurs regardless.

Make sure aren't using a dns that blocks apple services as they cause issues with signing apps.

**Comment by sysconf16** [comment]
> > > This issue gets fixed often in discord by right after installing sidestore is to refresh before installing apps.
> > 
> > 
> > I have always done this after installing SideStore, yet the problem re-occurs regardless.
> 
> Make sure you aren't using a dns that blocks apple services as they cause issues with signing apps.

Are there any specific domains which should be whitelisted? I wonder if there are any being blocked without me having realised.

**Comment by Yan-Jobs** [comment]
same issue here, clean install isn’t working. I’m on 17.1 dev beta tho

**Comment by Spidy123222** [comment]
Issue was related to not refreshing after install
