### ISSUE TITLE
[BUG] Shortcut for Refresh fails with "The file doesn't exist"

### ISSUE THREAD

**Issue by mahee96** [SideStore/SideStore#415]
### Describe the bug

Sidestore's "Refresh my Apps" Shortcut fails with "The file doesn't exist" error when invoking from both Shortcuts app or via Siri.

The error seems to be intermittent in the sense  that apart from very few cases when sidestore is already in the foreground and VPN already connected, the Refresh most probably fails.

Upon checking the logs the pairing file seems to be not found.

![IMG_3999](https://github.com/SideStore/SideStore/assets/47920326/f48dd6b0-f82e-41d7-aa3c-605d0acf1f77)
![IMG_4001](https://github.com/SideStore/SideStore/assets/47920326/0aef8b4e-4ae4-4103-862d-59b94e97502e)
![IMG_4002](https://github.com/SideStore/SideStore/assets/47920326/cd021898-ba4b-4460-81a8-e950f63741f1)

### Instructions to reproduce

Run the "Refresh my apps" shortcut or ask siri to "Refresh my apps".

### What version of SideStore are you using?

0.4.0 stable

### Other info

Haven't looked at code yet, so can't comment, but can lend a hand if needed.

**Comment by naturecodevoid** [comment]
Known issue since I made some fixes to the shortcuts

**Comment by mahee96** [comment]
Can you reference the commit here for posterity

**Comment by naturecodevoid** [comment]
It should be pretty easy to find in commit history if you look

It's caused by some issue with reading the pairing file, we really need to clean up all the pairing file logic since there's a ton of duplicate code

**Comment by mahee96** [comment]
okay I will build from source and give a try, Thanks.

**Comment by mustafacakirogludev** [comment]
I am having the same issue and this is the final obstacle for us to make a completely automatic weekly refresh. I don't know if someone is working on this but it'd be greatly appreciated.

**Comment by kwankiu** [comment]
I am having an issue that the SideStore refreshed the app successfully, but shortcut shows an error.

I made the shortcut to automatically turn on and off the VPN, however, with SideStore’s shortcut reporting error, the shortcut will not continue to run.

**Comment by AppelBoomHD** [comment]
I'm also experiencing this issue. The app refreshes, but still throws an error saying: "The file doesn't exist". Does anyone have an idea what's causing this?

**Comment by littleblack111** [comment]
same here, still no solution?

**Comment by tonysprenk** [comment]
Same issue

**Comment by YFHD-osu** [comment]
I solved this issue by renaming pairing file to ``ALTPairingFile.mobiledevicepairing`` and put it into ``SideStore`` folder at ``On My iPhone``.

Found this method on [SideStore Docs FAQ](https://wiki.sidestore.io/faq/#im-unable-to-select-my-pairing-file-with-any-file-type)

**Comment by tonysprenk** [comment]
> I solved this issue by renaming pairing file to `ALTPairingFile.mobiledevicepairing` and put it into `SideStore` folder at `On My iPhone`.
> 
> Found this method on [SideStore Docs FAQ](https://wiki.sidestore.io/faq/#im-unable-to-select-my-pairing-file-with-any-file-type)

I don’t see this file in the side store folder. Where can I download it?

**Comment by YFHD-osu** [comment]
> > I solved this issue by renaming pairing file to `ALTPairingFile.mobiledevicepairing` and put it into `SideStore` folder at `On My iPhone`.
> > Found this method on [SideStore Docs FAQ](https://wiki.sidestore.io/faq/#im-unable-to-select-my-pairing-file-with-any-file-type)
> 
> I don’t see this file in the side store folder. Where can I download it?

The paring file needs to be generated by yourself, follow [these](https://wiki.sidestore.io/guides/getting-started/#pairing-file) steps to do so.

**Comment by junepark678** [comment]
stale
