### ISSUE TITLE
[BUG] Unable to install the app from the staging directory

### ISSUE THREAD

**Issue by Zhou-Shilin** [SideStore/SideStore#416]
### Describe the bug

![A45126A4-E9FB-4CD9-B6E7-E4D9E09A0235](https://github.com/SideStore/SideStore/assets/86581525/fe44738f-e7ec-46a2-a1da-c36e13aaea00)

### Instructions to reproduce

Try to sign this with SideStore:
[Wechat++.ipa](https://files.baimoqilin.top:8088/d/files.baimoqilin.top:8088/files/github-issues/SideStore/Wechat++.ipa)

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment]
Duplicate issue
