### ISSUE TITLE
[BUG] sidestore v3 server not working

### ISSUE THREAD

**Issue by ryanhuang10** [SideStore/SideStore#417]
### Describe the bug

By signing in sidestore

### Instructions to reproduce

I don’t know how

### What version of SideStore are you using?

0.4.0 nightly 24/07/23

**Comment by Nythepegasus** [comment]
Hello! Use https://ani.sidestore.io manually in Settings for now. We're going to release an update soon. 
![anisette_settings](https://github.com/SideStore/SideStore/assets/17764867/3912d58a-d964-4685-b82d-a448a9888127)
