### ISSUE TITLE
[BUG] I cant login to the SideStore

### ISSUE THREAD

**Issue by oski1234** [SideStore/SideStore#421]
### Describe the bug

When i click “Sign in with apple ID” and i type in my email and password, the error “Failed to login. An error occurred when getting anisette data from a V3 Server: Couldnt fetch clients info. The servers may be down (could not connect to the server.) Please try again. If the issue persists, report it on github Issues!” Pops up.

### Instructions to reproduce

1. Open up SideStore.
2. Click on “Settings”
3. Click on “Sign in with apple ID”
4. Type in anything.

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment]
Please update to 0.5.0 or turn off use preferred servers and use https://ani.sidestore.io as your anisette server

**Comment by Hunam6** [comment]
I have 0.5.0, I get the same issue when trying to install an ipa.
I tried unchecking "Use preferred servers" and inputting `https://ani.sidestore.io/` in the next field and I still have the same issue.

**Comment by JainnyAryan** [comment]
Use sideloadly server as annisette server

**Comment by naturecodevoid** [comment]
That will lock your account

**Comment by danybitw** [comment]
same here, and `https://ani.sidestore.io/` doesn't solve anything. Same goes for sideloady or any other anisette server. Is any other experiencing this?

**Comment by Hesham-Salama** [comment]
Same issue.
