### ISSUE TITLE
[BUG] error occured when getting anisette data from V3 server

### ISSUE THREAD

**Issue by tolliebol** [SideStore/SideStore#422]
### Describe the bug

after one day, cant refresh or login with apple id. Get the error: ‘an error occured when getting anisette data from a V3 server: couldn’t fetch client info. I tried changing anisette servers in iphone settings but that didnt solve the issue.

### Instructions to reproduce

download sidestore, log in and wait a day.

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment]
See https://github.com/SideStore/SideStore/issues/421
