### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IM-SPYBOY** [SideStore/SideStore#423]
### Describe the bug

Failed to Log In
An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.). Please try again.

### What version of SideStore are you using?

4.0

**Comment by Nythepegasus** [comment]
Hello! Make sure you are using the updated anisette server https://ani.sidestore.io as the one with the 6969 port has been shut down in favor of the https one. Also consider updating to [0.5.0](https://github.com/SideStore/SideStore/releases/tag/0.5.0)! 
![anisette_settings](https://github.com/SideStore/SideStore/assets/17764867/ed093ea9-039d-4850-9f93-88b46f8aa1f7)

**Comment by IM-SPYBOY** [comment]
Thanks for update my issue fixed using updated anisette server https://ani.sidestore.io
