### ISSUE TITLE
[BUG] can’t refresh apps

### ISSUE THREAD

**Issue by jay1285z** [SideStore/SideStore#425]
### Describe the bug

I been getting this error the past day. I install again on my computer and nothing.  

The operation couldn’t be completed. An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.). Please try again. If the issue persists, report it on GitHub Issues!

### Instructions to reproduce

Refresh app

### What version of SideStore are you using?

1.06

**Comment by naturecodevoid** [comment]
1.06 is not a version of SideStore

**Comment by naturecodevoid** [comment]
See #423
