### ISSUE TITLE
[BUG] App crashes when trying to remove un-activated app

### ISSUE THREAD

**Issue by home-gihub** [SideStore/SideStore#427]
### Describe the bug

Recently I deactivated an app, I wanted to remove it because I wanted to re-activate the app upon pressing the activate button I received a message "unable to install the app from the staging directory" and so I preceded to remove it as soon as I clicked the remove button the app crashed. Then I re-opened it looked at the my apps section, no change.

### Instructions to reproduce

Install an app then de-activate it then press the remove button.

### What version of SideStore are you using?

0.5.0

**Comment by Spidy123222** [comment]
Known issue

**Comment by Spidy123222** [comment]
Was resolved
