### ISSUE TITLE
[BUG] Cannot start a misagent server on the device.

### ISSUE THREAD

**Issue by lingsoul** [SideStore/SideStore#429]
### Describe the bug

The operation couldn’t be completed. Cannot start a misagent server on the device.

### Instructions to reproduce

When refreshing the app, an error message is reported:Cannot start a misagent server on the device.

### What version of SideStore are you using?

0.3.2-nightly.2023.04.02.1

**Comment by naturecodevoid** [comment]
1. Update to 0.5.0
2. Regenerate your pairing file and use the new one
3. Pretty sure this is a duplicate issue

**Comment by lingsoul** [comment]
> 

The currently used version(0.3.2-nightly.2023.04.02.1) includes MDC functionality. Could you please provide a convenient download link for the new MDC beta version? Thank you

**Comment by naturecodevoid** [comment]
In SideStore discord, there is a channel for downloads which includes MDC versions. These will require you to use WDBRemoveThreeAppLimit, MDC is not integrated.

**Comment by lingsoul** [comment]
Thank you for your help!
