### ISSUE TITLE
[BUG] Installing sidestore via Altserver 

### ISSUE THREAD

**Issue by Oectect** [SideStore/SideStore#435]
### Describe the bug

I delete the app and when I try to reinstall app, altsever said it could not access it

### Instructions to reproduce

plug in phone (ios 16.5)

open altsever in administration 

shift click to sideload .ipa 

click sidestore.ipa

enter apple id information

gets error 

![](https://cdn.discordapp.com/attachments/1137310455514275920/1137310455753359390/Screenshot_2023-08-05_020156.png)

### What version of SideStore are you using?

5.0 nightly

**Comment by naturecodevoid** [comment]
This is not an issue we can really fix, it's an issue with AltServer. Please try SideServer

**Comment by Jonaykon** [comment]
installing the app through altstore works
