### ISSUE TITLE
[BUG] SideStore fills up storage until storage limit

### ISSUE THREAD

**Issue by ZodiussDev** [SideStore/SideStore#437]
### Describe the bug

When side loading an app through SideStore, the device storage is filled up to maximum capacity. In the rare chance it actually finishes side loading, the amount of space being used persists.

### Instructions to reproduce

Use SideStore version 0.5.0
Sideload any app

### What version of SideStore are you using?

0.5.0

### Other info

Device: iPad Air 4th Generation

the size of the app I’m side loading is also a little over 700 mb if that is relevant

**Comment by naturecodevoid** [comment]
A copy of the IPA must be stored by SideStore to allow refreshing. So for a 700 MB IPA, it will take a minimum of ~1.4 GB of space.
