### ISSUE TITLE
SideStore won’t refresh with uyou +

### ISSUE THREAD

**Issue by matx33** [SideStore/SideStore#438]
### Describe the bug

Every app can refresh properly but sidestore when i have uyou+ sideloaded. When i deactivate uyou+ i can refresh sidestore. 
When trying to refresh either the app crashes or i get the message unable to install from staging directory.

### Instructions to reproduce

sideload uyou+ and refresh sidestore

### What version of SideStore are you using?

0.5

**Comment by vmavromatis** [comment]
Try reinstalling uyouplus

**Comment by naturecodevoid** [comment]
Duplicate of staging error
