### ISSUE TITLE
The operation couldn’t be completed. Unable to install the app from the staging directory

### ISSUE THREAD

**Issue by 2003-ABi** [SideStore/SideStore#439]
### Describe the bug

unable to refresh

### Instructions to reproduce

gives error every time i try to refresh sidestore app but it refreshes other aideloaded app

### What version of SideStore are you using?

latest available version

### Other info

message: unable to refresh apps from staging directory sidestore

**Comment by naturecodevoid** [comment]
Duplicate

**Comment by quyleanh** [comment]
@naturecodevoid could you tell me the reference for duplicate? I would like to track progress there. Thank you.

**Comment by naturecodevoid** [comment]
Search staging error, there are tons more duplicates as well as the original one
