### ISSUE TITLE
[BUG] Failed to start debug server: UnknownError

### ISSUE THREAD

**Issue by Zhou-Shilin** [SideStore/SideStore#441]
### Describe the bug

Failed to open JIT for Pojavlauncher.

### Instructions to reproduce

1. Open SideStore VPN
2. Enable JIT with SideStore
3. ![9FFC8156-5179-4183-9354-5DC1EF94EEB6](https://github.com/SideStore/SideStore/assets/86581525/fecbfcf0-af89-4c0b-830f-6d4762b10dfc)

### What version of SideStore are you using?

0.4.0

**Comment by naturecodevoid** [comment]
Are you on iOS 17?

**Comment by Zhou-Shilin** [comment]
No, 16.2 Beta 2

**Comment by Zhou-Shilin** [comment]
The log file: 
[minimuxer.log](https://github.com/SideStore/SideStore/files/12287203/minimuxer.log)

**Comment by Zhou-Shilin** [comment]
Log file:
```
04:24:03 [INFO] Logger initialized!!
04:24:03 [INFO] minimuxer has started!
04:24:03 [INFO] Starting listener
04:24:03 [INFO] Starting image mounter
04:24:03 [INFO] Starting heartbeat thread
04:24:03 [INFO] Heartbeat success!
04:24:08 [INFO] Debugging app ID: net.kdt.pojavlauncher.7YY7AR4K9D
04:24:08 [INFO] Trying to mount dev image
04:24:08 [ERROR] Failed to start debug server: UnknownError
04:24:08 [INFO] Removing DMG folder
04:24:08 [INFO] Downloading iOS dictionary...
04:24:09 [INFO] Downloading iOS 16.2 DMG...
04:24:11 [INFO] Debugging app ID: net.kdt.pojavlauncher.7YY7AR4K9D
04:24:11 [ERROR] Failed to start debug server: UnknownError
04:24:13 [INFO] Debugging app ID: net.kdt.pojavlauncher.7YY7AR4K9D
04:24:13 [ERROR] Failed to start debug server: UnknownError
04:24:13 [INFO] Heartbeat success!
```

**Comment by Spidy123222** [comment]
It sounds like it started debug before download was finished (slow internet likely) and mounting was never attempted because of how long. You can manually download developer disk image and name it to 16.2.dmg and 16.2.dmg.signature and make a file in sidestore directory called DMG and add those to that folder.

**Comment by Zhou-Shilin** [comment]
OK it works!
