### ISSUE TITLE
[BUG] Warning: Outdated Anisette Server

### ISSUE THREAD

**Issue by xhfpsxm** [SideStore/SideStore#442]
### Describe the bug

I suddenly got an error for no reason. What should I do?

![IMG_1788](https://github.com/SideStore/SideStore/assets/60850613/0ead212b-d24b-42cd-acb5-7d4f75539a75)

### Instructions to reproduce

I don't know. Suddenly this error occurred.

### What version of SideStore are you using?

0.5.0

**Comment by xhfpsxm** [comment]
And when attempting to sign in, it just infinitely loads.

**Comment by naturecodevoid** [comment]
Change anisette server to something other than SideStore and then change it to SideStore. Make sure use preferred servers is on

**Comment by xhfpsxm** [comment]
> Change anisette server to something other than SideStore and then change it to SideStore. Make sure use preferred servers is on

I changed server and tried again, but it failed. So I reinstalled the sidestore, but when attempting to sign in, it just infinitely loads.

**Comment by vilzio** [comment]
same

**Comment by ThommoMC** [comment]
Can also confirm getting outdated anisette server

**Comment by Nythepegasus** [comment]
@ThommoMC Try it again
