### ISSUE TITLE
[FEATURE REQUEST] Launch App and Launch App with JIT shortcuts

### ISSUE THREAD

**Issue by abhishekgi** [SideStore/SideStore#443]
### Describe the feature

Whenever i have to play on emulator i have to go to sidestore then i ahve to click on my apps section then i have to long press on the app and then i have to click enable jit . This feels very long process when we do it daily, it could be made easier by a Home Screen widget which will launch any app in one click or add a shortcut named launch app with widget for the shortcuts app which will pretty much will do the same thing 

### Use cases

Will make it easier to launch emulators with jit like pojavlauncher

**Comment by Spidy123222** [comment]
We have methods for this already planned and even some in testing using urlscheme. This will be part of the sidekit procedure to activate jit automatically.

**Comment by MalxWare47** [comment]
wow ppl are really that lazy.. aww ur fingers must be sore after that looooong process of enabling jit lmao. theres more important things that can be added/ fixed. this is pure lazyness. it takes 2 seconds to enable it.

**Comment by SternXD** [comment]
Closing this as there has been a PR produced it should be available in the next stable release
