### ISSUE TITLE
Failed to refresh 3 apps The data is not in the correct format

### ISSUE THREAD

**Issue by abhishekgi** [SideStore/SideStore#444]
### Describe the bug

I had installed sidestore about 2-3 days ago till now it was working but now it prompts “Failed to refresh 3 apps.The data is not in the correct format.”
**However i can still enable jit** 
but can’t install or refresh apps 

### Instructions to reproduce

Open sidetore click on refresh apps or try to refresh any particular app
![IMG_0741](https://github.com/SideStore/SideStore/assets/84626229/e927401a-3f6e-46ed-8549-efb1e45701fe)

### What version of SideStore are you using?

SideStore 0.5.0-nightly.2023.08.06.2+938bcd1

### Other info

The refresh doesn’t even turn green it only keeps rotating for some time prompts failed to refresh 3 apps the data is not in the correct format 
![IMG_0743](https://github.com/SideStore/SideStore/assets/84626229/30992cf7-ffb2-46d6-a4e3-1df0f2389f07)
![IMG_0744](https://github.com/SideStore/SideStore/assets/84626229/77e44a1e-8790-4744-a85f-059a89e892a3)

There nothing in refresh attempts 

Here is the minimuxer log 

14:02:03 [INFO] Logger initialized!!
14:02:03 [INFO] minimuxer has started!
14:02:03 [INFO] Starting listener
14:02:03 [INFO] Starting image mounter
14:02:03 [INFO] Starting heartbeat thread
14:02:04 [INFO] Heartbeat success!
14:02:08 [INFO] Trying to mount dev image
14:02:08 [INFO] Developer disk image already mounted
14:02:08 [INFO] Auto image mounter has finished, have a great day!
14:02:15 [INFO] Heartbeat success!
14:02:26 [INFO] Heartbeat success!
14:02:36 [INFO] Heartbeat success!
14:02:47 [INFO] Heartbeat success!
14:02:58 [INFO] Heartbeat success!
14:03:08 [INFO] Heartbeat success!
14:03:19 [INFO] Heartbeat success!
14:15:52 [ERROR] Heartbeat recv failed: MuxError
14:15:54 [INFO] Heartbeat success!
14:16:05 [INFO] Heartbeat success!
14:16:16 [INFO] Heartbeat success!
14:16:26 [INFO] Heartbeat success!
14:18:43 [ERROR] Heartbeat recv failed: MuxError
14:18:43 [INFO] Heartbeat success!
14:21:02 [ERROR] Heartbeat recv failed: MuxError
14:21:02 [INFO] Heartbeat success!
14:23:05 [ERROR] Heartbeat recv failed: MuxError
14:23:05 [INFO] Heartbeat success!
14:23:16 [INFO] Heartbeat success!
14:23:27 [INFO] Heartbeat success!
14:23:37 [INFO] Heartbeat success!
14:23:48 [INFO] Heartbeat success!
14:23:59 [INFO] Heartbeat success!
14:24:09 [INFO] Heartbeat success!
14:24:20 [INFO] Heartbeat success!
14:25:28 [ERROR] Heartbeat recv failed: MuxError
14:25:28 [INFO] Heartbeat success!
14:25:38 [INFO] Heartbeat success!
14:25:49 [INFO] Heartbeat success!
14:26:00 [INFO] Heartbeat success!
14:28:28 [ERROR] Heartbeat recv failed: MuxError
14:28:28 [INFO] Heartbeat success!
14:28:39 [INFO] Heartbeat success!
14:28:50 [INFO] Heartbeat success!
14:29:00 [INFO] Heartbeat success!

**Comment by abhishekgi** [comment]
[minimuxer.log](https://github.com/SideStore/SideStore/files/12303777/minimuxer.log)

**Comment by naturecodevoid** [comment]
Make sure you're using SideStore anisette (you may have to select a different server and then select SideStore again), otherwise the server may be down so try again later
