### ISSUE TITLE
[BUG] Sidestore Apple ID login not working

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#446]
### Describe the bug

I logged out in the SIdestore app and now I am trying to log back in. When I try to log back in I get an error message that says this. And yes I am using the latest server linked in the discord labeled [http://s.nythepegas.us:6969](http://s.nythepegas.us:6969)

`An error occurred when getting anisette data from a V3 server: std. file.FileException: /home/ ny/workspace/anisette-v3-server/provisioning/ 557d2eb9-ac9f-170c-43c1-e7798baab683:
Too many open files. Please try again. If the issue persists, report it on GitHub Issues!`
![IMG_1037](https://github.com/SideStore/SideStore/assets/69532417/d616b1f8-607f-4d3f-b3fc-10fda6aaabb5)

### Instructions to reproduce

1. Open side store then log out of Apple ID
2. Try to log back in 
3. Error produced 

### What version of SideStore are you using?

0.5.0

**Comment by naturecodevoid** [comment]
Reporting this

**Comment by jimmysofat6864** [comment]
I tried resetting adi.pd but now the login is getting stuck with no progress.

**Comment by jimmysofat6864** [comment]
> Reporting this internally

Reseting adi.pd causes the login to get stuck as shown below. 

![IMG_2D7793CF0FBA-1](https://github.com/SideStore/SideStore/assets/69532417/b85de518-9738-4cb7-a96a-7db364d4eb3f)

**Comment by naturecodevoid** [comment]
You may need to change anisette server URL back to https://ani.sidestore.io

**Comment by Dadoum** [comment]
The issue was in the new anisette server you're using. I fixed the bug but you will probably have to wait few hours before getting the online server fixed.
