### ISSUE TITLE
It keeps saying You don't have permission. To view or change permissions, select the item in the Finder and choose File > Get Info.

### ISSUE THREAD

**Issue by Jaythegamer29** [SideStore/SideStore#447]
### Describe the bug

I don’t get it I did it on Mac got WireGuard and used my Apple ID 

### Instructions to reproduce

![IMG_7411](https://github.com/SideStore/SideStore/assets/134325229/f733aded-b978-43f1-bf12-7bb6679d6d08)

### What version of SideStore are you using?

0.5.0

**Comment by naturecodevoid** [comment]
Please be more specific and follow the issue template instructions. What action causes this error?

**Comment by Jaythegamer29** [comment]
Also it's says that I'm using a old anisette server

**Comment by Jaythegamer29** [comment]
https://github.com/SideStore/SideStore/assets/134325229/5b5bc934-1092-47f0-89a1-bf07356c91af

**Comment by Jaythegamer29** [comment]
Also this happened “GJ_LaunchSheet-hd.plist” couldn’t be copied because you don’t have permission to access “GeometryDashSubZero.app”.

To view or change permissions, select the item in the Finder and choose File > Get Info.

**Comment by An-Unnamed-Developer** [comment]
This is a problem with the apps compilation procedure. This app was most likely compiled on a Windows machine which has a different file and permissions format, this isn’t a SideStore issue.

**Comment by An-Unnamed-Developer** [comment]
I’m assuming you’re trying to download and install the GDPS 2.2 editor, if so, download from the discord.

**Comment by minecraftliu** [comment]
> This is a problem with the apps compilation procedure. This app was most likely compiled on a Windows machine which has a different file and permissions format, this isn’t a SideStore issue.

It is my case! I was trying to sideload an app too but when i opened the file using a zip extractor app, it showed that this file is a NTFS format. Thus, the error of no permissions occurred. I can’t install it through other methods like Altserver as well, as the error says “App not found”. Is there a solution to such apps(apps compiled with Windows)? I do not have a version of the ipa that is complied on a Mac.

**Comment by An-Unnamed-Developer** [comment]
You can get an Apple device, rename the file to *.zip unpack it, and repack it then rename it to *.ipa, I think as that’ll fix the permissions

**Comment by minecraftliu** [comment]
No unzipping it and rezipping it does not work


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by An-Unnamed-Developer** [comment]
Ah, you could open it on a Mac, cd into the directory on Terminal and do `chown -r` and repack it

**Comment by minecraftliu** [comment]
I don't have a Mac :(
________________________________

**Comment by Spidy123222** [comment]
This is related to altsign and when creating an ipa should have permissions be for all users.

**Comment by junepark678** [comment]
This is a problem with the iPA. SideStore doesn't like apps meant to be distributed via the App Store in my experience.
