### ISSUE TITLE
minimuxer.MinimuxerError error 16

### ISSUE THREAD

**Issue by kasperkoek** [SideStore/SideStore#449]
### Describe the bug

Wehen I want to install app I het this Message. On my Homepage the app is there but gray out behause it doesnt have permision.

### Instructions to reproduce

Everytime I sideload or try install app in store

### What version of SideStore are you using?

0.5.0

**Comment by naturecodevoid** [comment]
Please provide more information. There should be a message with the error. And what about minimuxer logs?

**Comment by kasperkoek** [comment]
This is the error code: minimuxer.MinimuxerError error 16

This is the error Message: The operation couldn’t be completed. Unable to install the app from the staging directory

**Comment by naturecodevoid** [comment]
Duplicate of staging error

**Comment by kasperkoek** [comment]
So how to get this fixed? I dont have this app twice on my device. I get also this message when installing New apps

**Comment by gadour97** [comment]
Same here any fixes?

**Comment by quangtrung090790** [comment]
It same this. I cant refresh sidestore. 
![IMG_1105](https://github.com/SideStore/SideStore/assets/5866145/48dc63e7-318c-4693-9fed-66041c800f67)

**Comment by pvrzz** [comment]
Just had this issue, and the fix for me was to reset and recreate my pairing file.
instructions on tab #3 for creating a pairing file: https://sidestore.io/#get-started

**Comment by hkpD** [comment]
I believe I Fixed mine by turning on my Wi-Fi, because it was turned off.
