### ISSUE TITLE
[BUG] Fail to refresh

### ISSUE THREAD

**Issue by xhfpsxm** [SideStore/SideStore#450]
### Describe the bug

https://github.com/SideStore/SideStore/assets/60850613/80448837-695e-4910-92e2-e8e13db468aa

I failed to log in for several days for unknown reasons. Then today I was able to log in by accident. But I have a different problem. Sidestore is failing to refresh. Other apps are refreshing successfully, but only sidestore is failing to refresh.

![IMG_1799](https://github.com/SideStore/SideStore/assets/60850613/809f5f41-352c-4479-92c4-e5a43a73a515)

### Instructions to reproduce

Try to refresh.

### What version of SideStore are you using?

0.5.0

**Comment by abhishekgi** [comment]
Use altstore to install sidestore then this error will not appear

**Comment by RandomModderJDK** [comment]
Did you use SideServer for Windows to flash SideStore?

**Comment by xhfpsxm** [comment]
> 
OMG!! I succeeded with the method you suggest first. Thank you!!

**Comment by xhfpsxm** [comment]
> Did you use SideServer for Windows to flash SideStore? If so you could try this nightly test build: https://nightly.link/SideStore/SideServer-Windows/actions/artifacts/845829266.zip
> If this does not fix your issue you would probably need to uninstall SideStore, sideload SideStore with AltServer and then generate a pairing file, which you then select in SideStore. If you need a bit more detail look here: https://wiki.sidestore.io/guides/install#install-via-altserver-windowsmac

OMG!! I succeeded with the method you suggest first. Thank you!!

**Comment by xhfpsxm** [comment]
> Did you use SideServer for Windows to flash SideStore? If so you could try this nightly test build: https://nightly.link/SideStore/SideServer-Windows/actions/artifacts/845829266.zip
> If this does not fix your issue you would probably need to uninstall SideStore, sideload SideStore with AltServer and then generate a pairing file, which you then select in SideStore. If you need a bit more detail look here: https://wiki.sidestore.io/guides/install#install-via-altserver-windowsmac

And I want to know the path to access this adress(https://nightly.link~). Where do I have to go?
