### ISSUE TITLE
[BUG] SideStore Lock Screen widget not updating

### ISSUE THREAD

**Issue by Fox595676** [SideStore/SideStore#451]
### Describe the bug

The SideStore widget 
![IMG_3990](https://github.com/SideStore/SideStore/assets/81087203/143a800f-afd9-420c-93cf-fe3404327f8d)
does not update sometimes, the most prominent cases being after a restart. It sits at zero, and the only ways I know how to fix it is either by switching to a different wallpaper then switching back, or waiting for ages for it to update (it takes like over ten minutes for me - and I’ve reinstalled SideStore many times)
![IMG_3987](https://github.com/SideStore/SideStore/assets/81087203/5f27b206-357d-446a-a2ee-f2d435805640)

How to fix:
1.  Hold down on your wallpaper
2. Switch to a different wallpaper
3. Switch back
4. It should be fixed now :)

### Instructions to reproduce

Simply restart your phone with the SideStore widget loaded on your Lock Screen. 

### What version of SideStore are you using?

SideStore 0.5.0

### Other info

It happens whether you’re on Wifi, Cellular data, or no connection, and it’s always at zero. 

Also, this is my first SideStore bug report, tell me how I can improve!

**Comment by Spidy123222** [comment]
This is how widgets work it kinda just updates when it wants to. Usually takes a while.
