### ISSUE TITLE
[BUG] Shortcuts has two ”Refresh All apps” actions

### ISSUE THREAD

**Issue by Fox595676** [SideStore/SideStore#452]
### Describe the bug

When making a shortcut manually using SideStore actions, if you went to click on it in the apps section

![IMG_3994](https://github.com/SideStore/SideStore/assets/81087203/05b112ee-0a09-451f-a843-3d6edb073f83)

Then it will bring up the menu, it SOMETIMES has two of the same action. I thought it was always two, but I found out today that it’s inconsistent, and sometimes only has one??

![IMG_3991](https://github.com/SideStore/SideStore/assets/81087203/6b456a5a-b3c8-422c-997b-294c5cb578b1)
Clicking on it the first time

![IMG_3996](https://github.com/SideStore/SideStore/assets/81087203/4e3e5f6a-d4a0-4d60-837b-a3c149b16f7c)
Clicking on it the second time SOMETIMES causes it to disappear, and putting Shortcuts in the background makes it ALWAYS disappear. 

### Instructions to reproduce

Open shortcuts and find SideStore in the apps section of the actions, then there could be two. 

### What version of SideStore are you using?

0.5.0 and 0.4.~

### Other info

The top one seems to be the actual one, having the “favourite” option. 

![IMG_3992](https://github.com/SideStore/SideStore/assets/81087203/ebd01879-14e3-45fe-807f-80d6b38c83f9)

And the second one seems broken

![IMG_3993](https://github.com/SideStore/SideStore/assets/81087203/63379f30-107e-4655-87d8-549df238b33f)

They both seem to function however. 

Searching for “Refresh all apps” gives only one result.

**Comment by preland** [comment]
Is this issue still present on 0.5.2?

**Comment by Spidy123222** [comment]
This doesn't seem to be an issue now
