### ISSUE TITLE
Give me an anisette asia region.

### ISSUE THREAD

**Issue by Pogzhsd2** [SideStore/SideStore#453]
### Describe the feature

It's not a feature but, is there an asia anisette server? i cant use render right now and i really want to use sidestore without harm. (List all anisette's here and the regions here)

### Use cases

none

**Comment by Spidy123222** [comment]
The current anisette servers in preferred servers are from us developers. Though I think some are not up to date but doing any v3 anisette server will not do locking which is just a forced password reset. Sidestore, macley (DE and US) uses v3 anisette. Location issue was from multiple accounts associating with a non existent mac which now doesn’t happen in v3 as it’s a unique Mac and the calls that server wants to apple goes through the app making it look like your asking stuff from your idevice.

**Comment by naturecodevoid** [comment]
Also, please use GitHub discussions or discord next time
