### ISSUE TITLE
[BUG] Unable to manage profiles on the device 

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#456]
### Describe the bug

Any time I attempt to refresh any currently installed apps or install apps I keep getting an error message that pops up and says "Unable to manage profiles on the device". It's always that one or the one that says "unable to install the app from the staging directory". If I press the refresh button enough times eventually it will succeed but it's a bit annoying. Also, any time I refresh an app the SideStore app crashes for some reason. 

### Instructions to reproduce

1. Attempt to refresh a currently installed app
2. Error message should have popped up 

### What version of SideStore are you using?

0.5.0

**Comment by naturecodevoid** [comment]
Duplicate

**Comment by chippoman** [comment]
What is this a duplicate of? Searching for "unable to manage profile" only returns this issue.

**Comment by naturecodevoid** [comment]
Staging error and general connectivity (probably em_proxy) issues that are very known and probably what causes this

**Comment by benswolo** [comment]
How does one fix this issue? Issue persists on 0.5.1
