### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HECKER1235778** [SideStore/SideStore#458]
### Describe the bug

It not letting me download ipa flies

### Instructions to reproduce

Please fix

### What version of SideStore are you using?

New one

**Comment by naturecodevoid** [comment]
You are still being very vague and I have no idea what you mean. Was there an error? Does it happen with all apps?

**Comment by HECKER1235778** [comment]
Ok so what I mean it not let me Sideloading app it keeps on saying Unable to install the app from the staging directory

**Comment by naturecodevoid** [comment]
There are already many many issues for that.
