### ISSUE TITLE
[BUG] Sidestore refreshes all apps, but crashes before it can refresh itself

### ISSUE THREAD

**Issue by benswolo** [SideStore/SideStore#459]
### Describe the bug

iPhone 8, ios 15.7.1

There is another issue where the app crashes after it is refreshed, but for me Sidestore doesn't refresh and the day till expiry keeps ticking down. Error logs and refresh attempts are blank. 

### Instructions to reproduce

download sidestore website (0.5.0) and sideload using altserver
use mobiledevicepairing file
download vpn from website
attempt to refresh sidestore

### What version of SideStore are you using?

0.5.0

### Other info

I have had a previous install of altstore, which i deleted. After I installed sidestore, I reinstalled apps through sidestore so that the apps would be tied to sidestore.

**Comment by mBowl** [comment]
Same here, iPhone 8, iOS 15.6 rc1

**Comment by abhishekgi** [comment]
Just remove the sidestore widget from Home Screen , after that it will work fine

**Comment by abhishekgi** [comment]
If removing widget doesn’t work then try installing the sidestore using altserver instead of sideserver

**Comment by benswolo** [comment]
I don't have any widgets on my home screen. I did see another github issue but at least the altstore instance is refreshing. I installed sidestore from altserver after seeing the other issue.

**Comment by abhishekgi** [comment]
Try a fresh installation

**Comment by benswolo** [comment]
Okay, I think I figured out what was going on. I had 10 app IDs total, with two different sidestore version app IDs (0.4.0 and 0.5.0). Refreshing the app may have been "targeting" the wrong version. After some app IDs disappeared and the app IDs went down to 6, I was able to refresh sidestore (although it did crash upon refresh, which has been brought up in a previous issue).
