### ISSUE TITLE
[BUG] ImgPlay-IOSGods.com crashes when installed with sidestore

### ISSUE THREAD

**Issue by ryanhuang10** [SideStore/SideStore#461]
### Describe the bug

First in iOSGods.com I downloaded ImgPlay hacked and then used sidestore to install that ipa but when I open ImgPlay hacked it crashed.

### Instructions to reproduce

Maybe just fix some sideloaded apps crashing error

### What version of SideStore are you using?

0.5.0

**Comment by naturecodevoid** [comment]
This is most likely an ImgPlay issue.

**Comment by ryanhuang10** [comment]
but when I sideload it with sideloady, it works

**Comment by naturecodevoid** [comment]
Maybe they only want you to use Sideloadly, since iOSGods made it. Please ask on their forum or whatever
