### ISSUE TITLE
[FEATURE REQUEST] Add SideServer to Homebrew Casks

### ISSUE THREAD

**Issue by arjpar** [SideStore/SideStore#462]
### Describe the feature

It would be useful to have SideServer installable via homebrew casks. You could install it by using:
```
brew install --cask sideserver
```

### Use cases

It would ease the user experience by allowing a single command to install SideServer and also utilises the most used package manager for macOS. You can also install altserver via homebrew (but can't for sideserver) so this would close the gap.

**Comment by Spidy123222** [comment]
In this case a windows one using winget should likely exist.

**Comment by WesleyBryie** [comment]
> In this case a windows one using winget should likely exist.

you can just add apps to winget?

**Comment by nythepegasus** [comment]
I do agree that this would be useful, but may I request you make this issue on the respective repositories for SideServer [macOS](https://github.com/SideStore/SideServer-macOS) / [Windows](https://github.com/SideStore/SideServer-Windows) / [Linux](https://github.com/SideStore/SideServer-Linux)? Thanks!
