### ISSUE TITLE
[BUG] “Unable to install from staging directory“ error while trying to refresh SideStore

### ISSUE THREAD

**Issue by BlazeBoruto** [SideStore/SideStore#465]
### Describe the bug

So it's my first time trying to use SideStore and I did reset my phone recently while it had AltStore and 2 other sideloaded apps on it. I did get SideStore successfully installed on my phone as well as the WireGuard VPN tunnel (which was on when I tried to refresh SideStore) but the issue is, as written on title, when I connected myself and tried to refresh SideStore, it gave me the “Unable to install from staging directory“ error as seen on the picture. Error code: minimuxer.MinimuxerError error 16

![KqsjMD0a3y2Ii4EKIiyzs5k8LHK1qUyJQFvhUJgLApw](https://github.com/SideStore/SideStore/assets/65187201/e9e4692f-33c7-4a04-8c21-3139a436cfc4)

### Instructions to reproduce

1. Turn on SideStore's VPN Tunnel on WireGuard 
2. Open a fresh new installation of SideStore
3. Tap the refresh button
4. Connect your iCloud account
5. Wait for it to give you the error

### What version of SideStore are you using?

0.5

**Comment by BlazeBoruto** [comment]
21:46:39 [INFO] Logger initialized!!
21:46:39 [INFO] minimuxer has started!
21:46:39 [INFO] Starting image mounter
21:46:39 [INFO] Starting listener
21:46:39 [INFO] Starting heartbeat thread
21:46:44 [INFO] Trying to mount dev image
21:46:44 [ERROR] Failed to create heartbeat client: UnknownError
21:46:49 [ERROR] Unable to start mobile image mounter: UnknownError
21:46:49 [ERROR] Failed to create heartbeat client: UnknownError
21:46:54 [INFO] Trying to mount dev image
21:46:54 [ERROR] Failed to create heartbeat client: UnknownError
21:46:59 [ERROR] Unable to start mobile image mounter: UnknownError
21:46:59 [ERROR] Failed to create heartbeat client: UnknownError
21:47:04 [INFO] Trying to mount dev image
21:47:05 [ERROR] Failed to create heartbeat client: UnknownError
21:47:09 [ERROR] Unable to start mobile image mounter: UnknownError
21:47:10 [ERROR] Failed to create heartbeat client: UnknownError
21:47:14 [INFO] Trying to mount dev image
21:47:15 [ERROR] Failed to create heartbeat client: UnknownError
21:47:19 [ERROR] Unable to start mobile image mounter: UnknownError
21:47:20 [ERROR] Failed to create heartbeat client: UnknownError
21:47:24 [INFO] Trying to mount dev image
21:47:25 [ERROR] Failed to create heartbeat client: UnknownError
21:47:29 [ERROR] Unable to start mobile image mounter: UnknownError
21:47:30 [ERROR] Failed to create heartbeat client: UnknownError
21:47:34 [INFO] Trying to mount dev image
21:47:35 [ERROR] Failed to create heartbeat client: UnknownError
21:47:56 [ERROR] Unable to start mobile image mounter: UnknownError
21:47:56 [ERROR] Failed to create heartbeat client: UnknownError
21:48:01 [INFO] Trying to mount dev image
21:48:50 [ERROR] Failed to create heartbeat client: UnknownError
21:48:50 [ERROR] Unable to start mobile image mounter: UnknownError
21:49:10 [ERROR] Failed to create heartbeat client: UnknownError
21:49:10 [INFO] Trying to mount dev image
21:49:15 [ERROR] Unable to start mobile image mounter: UnknownError
21:49:15 [ERROR] Failed to create heartbeat client: UnknownError
21:49:20 [INFO] Trying to mount dev image
21:49:20 [ERROR] Failed to create heartbeat client: UnknownError
21:49:25 [ERROR] Unable to start mobile image mounter: UnknownError

**Comment by abhishekgi** [comment]
Use altserver for installing sidestore

**Comment by naturecodevoid** [comment]
Duplicate

**Comment by BlazeBoruto** [comment]
> Duplicate

from which one ?

**Comment by naturecodevoid** [comment]
Search staging error
