### ISSUE TITLE
[BUG]  failed to login with apple id

### ISSUE THREAD

**Issue by wormprty** [SideStore/SideStore#466]
### Describe the bug

trying to use sidestore. can’t sign in with apple id. getting an error that says server may be down(image attached). tried different anisettes and nothing is working. it said to report on github so here i am :)

### Instructions to reproduce

open aidestore, try and sign in with apple id on any anisette. get the error

### What version of SideStore are you using?

0.4.0

### Other info

![IMG_3121](https://github.com/SideStore/SideStore/assets/144492490/172873f3-ff38-4b69-9d7f-9f323efb0115)

**Comment by naturecodevoid** [comment]
It might be an issue with your internet. It could also be a temporary issue with the server.
