### ISSUE TITLE
[FEATURE REQUEST] Ability to customise IP for signing server

### ISSUE THREAD

**Issue by simonfalke-01** [SideStore/SideStore#475]
### Describe the feature

From what I know, the WireGuard config is just a loopback to the localhost to bypass iOS restrictions. However, since on iOS only one VPN profile can be active at a time, and I need to use Tailscale for my work, I won't be able to be connected to the WireGuard profile usually. 

Hence, the ability to customise this IP for the signing server would be good, as I can simply change it to my device Tailscale IP, which should achieve the same effect of a loopback with WireGuard.

Thank you.

### Use cases

- Usage of SideStore with Tailscale
- When there are multiple VPN configs on device (the user cannot connect to more than one at a time, because of limitations of iOS)

### Alternatives

- Another alternative is to add Tailscale integration directly. However, this would be much more difficult and elaborate than if the IP was just user-customisable.

**Comment by naturecodevoid** [comment]
This isn't that simple to implement. SideStore's inner workings are made for WireGuard; a special WireGuard server (em_proxy) is required for loopback to work.

**Comment by preland** [comment]
Would it be possible to have SideStore switch the VPN profile on when it is needed, and then switch back to whatever was present before after it isn’t needed? That could also potentially address false issues derived from users forgetting to turn on the VPN profile when installing, or other issues relating to the VPN not being present.

**Comment by preland** [comment]
More on topic for the issue; it would be technically possible to add this functionality, but it would require a rework of the current loopback model.

**Comment by puellaexmachina** [comment]
This is sort of why I wish the proxy service had more documentation. I'm more curious how the SideStore developers accomplished _anything_ related to multicast DNS or Bonjour without a TAP device (which iOS doesn't support; this is why ZeroTier's Bonjour features don't work with iPhone). 

Regardless, Tailscale or ZeroTier implementation may be hard for them -- but technically, they are both WireGuard under the hood.

**Comment by DwifteJB** [comment]
Bump, I would love tailscale with sidestore.

**Comment by jkcoxson** [comment]
For people seeing this thread after the fact:
No, Tailscale will not work. Unless you have a special server to bump packets like em_proxy does on device, a regular VPN connected to whatever server won't work.

em_proxy functions as a wireguard 'server' and takes over all traffic on the interface.

**Comment by dvtkrlbs** [comment]
> For people seeing this thread after the fact: No, Tailscale will not work. Unless you have a special server to bump packets like em_proxy does on device, a regular VPN connected to whatever server won't work.
> 
> em_proxy functions as a wireguard 'server' and takes over all traffic on the interface.

Wait I am actually confused on why exactly Tailscale Subnet routers would not work. I am not knowledgeable on the inner workings of `em_proxy` but I should be possible for that server to publish it packets on the specified subnet no ?

**Comment by jkcoxson** [comment]
No. em_proxy functions as a peer itself.

**Comment by dvtkrlbs** [comment]
I would love to read some more about it but I don't see the reason why it has to capture the loopback wouldn't defining a subnet on othe server side and make the client talk in that subnet is enough for this? How this piece is handled by the client and the server?
