### ISSUE TITLE
Can't start instproxy server on this device

### ISSUE THREAD

**Issue by Vercixx** [SideStore/SideStore#476]
### Describe the bug

When I try install .ipa file it says "Cannot start instproxy server on this device". Wireguard VPN enabled and I connected to fast WiFi.

### Instructions to reproduce

1. Open SideStore
2. Open "My apps" tab
3. Click on + and select .ipa file
4. Wait
5. Failed to install with error

### What version of SideStore are you using?

0.5.1

**Comment by henryglends** [comment]
Have you tried resetting your pairing file?

**Comment by Vercixx** [comment]
Not yet, let me try.

**Comment by Laotigona** [comment]
I'm also having this issue. Installed SideStore via a Windows 10 machine, with iTunes and iCloud from Apple and not the Microsoft Store.  Connected wireguard via Sidestore.conf, added LitRitt repo in Sources to install Ignited.

While connected to only the Wireguard VPN based on the provided Sidestore.conf file, I get this error:
"The operation couldn't be completed. Cannot start a instproxy server on the device."
minimuxer.MinimuxerError error 5

Device:
iPhone 14 Pro on iOS 16.6.1

**Comment by ordzy** [comment]
Same issue for me, I've reset pairing file and reset the adi.pb.
