### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by henryglends** [SideStore/SideStore#477]
### Describe the bug

I have recently encountered this issue on Version 0.5.1, when trying to de-activate an app. 

AltBackup.BackupError error 1
Unable to create backup directory. The AltStore app group could not be found.

I am not the only user to have this issue, another user on discord (sniper1239408) claims when they went back to version 0.5.0, this issue no longer persists.

### Instructions to reproduce

Install SideStore Version 0.5.1
Install an app (sideloaded)
Try to de-activate

### What version of SideStore are you using?

0.5.1

**Comment by naturecodevoid** [comment]
I know why this happens. You might have to use 0.5.0 for now

**Comment by naturecodevoid** [comment]
Duplicate

**Comment by aaronliu0130** [comment]
Of which issue?

**Comment by naturecodevoid** [comment]
The app group one

**Comment by aaronliu0130** [comment]
I am on iOS 16 if you're talking about #488, it doesn't apply to me. Refreshing also works fine.

**Comment by aaronliu0130** [comment]
@naturecodevoid

**Comment by naturecodevoid** [comment]
Yes it does

**Comment by aaronliu0130** [comment]
Hmm, so the pairing file doesn't need to be extracted from iOS17, just your current OS?

**Comment by naturecodevoid** [comment]
What do you mean?

**Comment by aaronliu0130** [comment]
>Found a workaround
>Use AltServer to sideload SideStore IPA > use a new jitterbug pairing file that you extracted from iOS17
