### ISSUE TITLE
[BUG] "JIT could not be enabled for SideStore."

### ISSUE THREAD

**Issue by cottontails2** [SideStore/SideStore#478]
### Describe the bug

I followed the instructions for the Windows install on the official website, after i installed SideStore, when i go to "Enable JIT" > "my iPhone" > "SideStore" i get this error message?

"JIT could not be enabled for SideStore."

"The URL to download the Developer disk image could not be determined."

I have developer mode enabled and the app loads just fine, i don't know if i've done something wrong?

### Instructions to reproduce

Happens every time even after restarting both my PC and iPhone.

### What version of SideStore are you using?

0.5.1

**Comment by naturecodevoid** [comment]
What iOS version?

**Comment by cottontails2** [comment]
IOS 17 public release

**Comment by naturecodevoid** [comment]
This is a duplicate, search for the other iOS 17 JIT issue for why it isn't supported
