### ISSUE TITLE
[FEATURE REQUEST] Apple ID Switcher

### ISSUE THREAD

**Issue by VSS-Vintorez** [SideStore/SideStore#479]
### Describe the feature

There would be an area to add, or remove Apple IDS, and when installing an app, There can be a mode where you can choose which Apple ID to sign the app on, and another mode to switch Apple IDs based on how many free App IDS there are and switch Apple IDs if the app being installed exceeds the amount of App IDS allowed on 1 Apple ID.

### Use cases

The ability to bypass needing a paid Developer Account to install more apps at 1 time. This would work even better with MDC.

**Comment by nythepegasus** [comment]
I'll close this in favor of #274
