### ISSUE TITLE
[BUG]  SideStore not refreshing

### ISSUE THREAD

**Issue by RazvanTL** [SideStore/SideStore#480]
### Describe the bug

Hello!
Sorry for my bad English.
I encounter a bug when I try to refresh the SideStore. Other apps works great when I refresh.
I aleardy try another server, reinstall the app thought pc, reset pairing file, reset Adi.pb
I have iOS 17 iPhone 14 pro max

### Instructions to reproduce

Enter the SideStore with the VPN on and try to refresh the Sideapp I encounter this error
![IMG_1985](https://github.com/SideStore/SideStore/assets/145559283/1ff97e7b-4018-40e1-8d59-865d2f6be6e4)

### What version of SideStore are you using?

Latest

**Comment by AceCommander09** [comment]
I have this error too. So until it gets fixed I just go onto my PC and reinstall SideStore but without deleting it off my iPhone.

**Comment by EricThunder** [comment]
Also having the same issue. Just installed Sidestore and custom Anisette Server (also tried default but same result)

**Comment by RazvanTL** [comment]
Search on google for SideStore versions and download 0.5.0 should solve the issue. Now when I downgrade I can refresh SideStore.

I have one my problem I cannot install gta San Andreas, papers please, alien isolation etc (game ipa) just loading and crash. After crash my cache memory goes up and i cannot free until I reinstall the SideStore app.

Please solve this, we are so greatfull for your work and you are a master.

**Comment by tkien931** [comment]
Same issue as #488 https://github.com/SideStore/SideStore/issues/488
Refer to that issue for workaround
