### ISSUE TITLE
[BUG] Cannot start a instproxy server on this device

### ISSUE THREAD

**Issue by Laotigona** [SideStore/SideStore#482]
### Describe the bug

When downloading any app from any Source (repo), the app installation fails with error "Cannot start a instproxy server on this device."

### Instructions to reproduce

1. Open SideStore.
2. Click 'Browse' in tab bar.
3. Click the "FREE" button for any app (e.g., "Ignited" from LitRitt Source/repo).
4. Installation fails and error message displays: "Cannot start a instproxy server on this device."

### What version of SideStore are you using?

0.5.1

### Other info

Background Info:
- For installation, I used a Windows 10 computer with both iTunes and iCloud sourced from the Apple web site, and not the embedded Microsoft Store.
- WireGuard has been set up correctly on the device, using the SideStore.conf file.
- Installation is attempted only while connected to the WireGuard VPN.

Troubleshooting Attempted:
- Restarted devices
- Reinstalled SideStore
- 'Reset Pairing File' in SideStore Settings

Device Info:
- iPhone 14 Pro on iOS 16.6.1

**Comment by ordzy** [comment]
Exact same issue on iPhone SE (2020) iOS 16.6.

**Comment by fuomag9** [comment]
Same issue on iPadOS 17 on an iPad air 5th gen

**Comment by Astrior** [comment]
Same issure here, hope it gets patched!

**Comment by naturecodevoid** [comment]
Regenerate your pairing file

**Comment by fuomag9** [comment]
> Regenerate your pairing file

Regenerating did not change anything

**Comment by naturecodevoid** [comment]
You may need to rename it to `ALTPairingFile.mobiledevicepairing` and then put it in the SideStore directory in the Files app

**Comment by hrz6976** [comment]
Same issue here on iOS 17. Success with regerating the pairing file:
1. follow https://wiki.sidestore.io/guides/install#pairing-file

**Comment by squishy9876** [comment]
> Same issue here on iOS 17. Success with regerating the pairing file:
> 
> 1. follow https://wiki.sidestore.io/guides/install#pairing-file
> 
> 2. rename the .mobilepairing file under ~/ to `ALTPairingFile.mobiledevicepairing`
> 
> 3. drag and drop the file to SideStore's storage on iPhone

this worked for me

**Comment by ShrekLoveer69** [comment]
> Same issue here on iOS 17. Success with regerating the pairing file:
> 
> 1. follow https://wiki.sidestore.io/guides/install#pairing-file
> 2. rename the .mobilepairing file under ~/ to `ALTPairingFile.mobiledevicepairing`
> 3. drag and drop the file to SideStore's storage on iPhone

It still doesn’t work

**Comment by peterge1998** [comment]
https://wiki.sidestore.io/guides/install#pairing-file gives this:
404
Page not found. Check the URL or try using the search bar.

I am facing "Cannot start a instproxy server on this device." too, iPhone 12

**Comment by peterge1998** [comment]
I was able to create 00008101-000D29A62646001E.mobiledevicepairing using this option of the Enable JIT option of SideServer.
I renamed it to ALTPairingFile.mobiledevicepairing, as suggested by @hrz6976. Now the SideStore Storage looks like this:
![image](https://github.com/SideStore/SideStore/assets/47355238/2f9d32af-f038-456e-8561-19b97698a3ea)
But it does still not work for me, the error is still showing up

**Comment by peterge1998** [comment]
Tried it again today, and magically it worked! I didnt change anything, the files are still the same as in my last screenshot :)

**Comment by hrz6976** [comment]
Sorry for commenting under a closed issue, but the problem keeps occurring from time to time. I'm running the latest sidestore on iOS 17.0.3 (iPhone 15 Pro), and 4 out of 5 refreshes sidestore complains about "unable to manage profiles on this device", or "can not start instproxy"). The regenerating the pairing file (or click "reset pairing file" under the settings tab) workaround can get it to work for merely a day or two, but it will probably fail afterwards. I can definitely replicate this issue with the stock

**Comment by ryan11280** [comment]
I have the same issue from @peterge1998, after duplicated and renamed the "ALTPairingFile" file, instaproxy error gones, thank u!

**Comment by peterge1998** [comment]
> I have the same issue from @peterge1998, after duplicated and renamed the "ALTPairingFile" file, instaproxy error gones, thank u!
> 
> device: iPhone15Pro on 17.0.3

One more user facing this problem, in my opinion this justifys a new issue...
