### ISSUE TITLE
[BUG]  Crash when installing game ipa

### ISSUE THREAD

**Issue by RazvanTL** [SideStore/SideStore#483]
### Describe the bug

Hello!
I encounter another bug.
When I try to install an game ipa ( gta San Andreas, alien isolation, paper please) crash and exit the app, I tried many ipa files from different websites but didn’t work.

Another issue is cache memory. When the app crash, file remains in memory and take so much memory on every try.

I use the 0.5.0 version because I cannot refresh the SideStore app on the newer versions.

please solve this issue and thanks for your great work. Without you we cannot be free on iOS.

I only post this bugs only to help you I don’t have and expectations from a beta app and I give you many thanks. I know it’s a hard work behind and your team did this for us free.

### Instructions to reproduce

Download an ipa file game like gta San Andreas and  will crash when instalation (vpn on and other apps work)

### What version of SideStore are you using?

0.5.0

**Comment by eeshankeni** [comment]
Can confirm this issue still exists

**Comment by nythepegasus** [comment]
Hello! We do not condone piracy of any kind, please just buy the games off the App Store.

**Comment by eeshankeni** [comment]
@nythepegasus why does this bug need to be limited to piracy? Any app above 500 mb seems to cause the crash.

**Comment by nythepegasus** [comment]
@eeshankeni The OP mentioned apps specifically from the App Store, and we have other issues for tracking the 500MB+ issue.
