### ISSUE TITLE
[BUG] Refresh SideStore Failed

### ISSUE THREAD

**Issue by fard83** [SideStore/SideStore#484]
### Describe the bug

WireGuard is enabled, tried plugged in and not plugged in, both didnt work, connected to wifi, sideserver and altserver are both running, no other apps sideloaded.

### Instructions to reproduce

i dont know

### What version of SideStore are you using?

0.5.1

**Comment by RazvanTL** [comment]
Downgrade to 0.5.0 
Search SideStore versions
Enter the official GitHub versions and download 0.5.0 ipa.
After this install thought sideapp and you’re done it will refresh and work

**Comment by RazvanTL** [comment]
You don’t need a pc or something just install downgraded SideStore ipa file thought SideStore basic app

**Comment by fard83** [comment]
cant sideload either

**Comment by RazvanTL** [comment]
> cant sideload either

Mine works on this method. 
you should do a clean install and first step downgrade thought official SideStore GitHub page. Refresh and after this install other side apps.

**Comment by RazvanTL** [comment]
> cant sideload either

We should wait a response from developer. Its an beta app, we should be happy to get this for free

**Comment by fard83** [comment]
ok

**Comment by ordzy** [comment]
was i the only one that got the instaproxy error?

**Comment by naturecodevoid** [comment]
At least send the error message. I have no way of knowing what this is caused by
