### ISSUE TITLE
[BUG] Two-factor authentication

### ISSUE THREAD

**Issue by xhfpsxm** [SideStore/SideStore#485]
### Describe the bug

Since I've been using my custom server (xxx~.onrender.com), I've been experiencing the phenomenon of being asked for two factor authentication quite often. But sidestore works fine.

Is this normal?

### Instructions to reproduce

1. Create custom server
2. Fill in anisette url

### What version of SideStore are you using?

0.5.1

**Comment by naturecodevoid** [comment]
Use official Anisette, render servers will ask for 2fa a lot

Official Anisette will not lock your account
