### ISSUE TITLE
[BUG] refresh sidestore itself

### ISSUE THREAD

**Issue by saeidselfjoor** [SideStore/SideStore#491]
### Describe the bug

Can’t refresh sidestore itself don’t know why other apps refresh ok

### Instructions to reproduce

https://ibb.co/YyGHxKP

### What version of SideStore are you using?

Last version

**Comment by saeidselfjoor** [comment]
Another picture 
https://postimg.cc/9DbZxrsD

**Comment by SARankDirector-Minecraft** [comment]
Try reinstalling SideStore ipa in SideStore and selecting yes in "remove app extensions"

**Comment by saeidselfjoor** [comment]
Thank you so much

**Comment by naturecodevoid** [comment]
No error info, probably duplicate
