### ISSUE TITLE
[BUG] Sidestore 0.5.1 MDC Always Crashes when attempting self-refresh or update

### ISSUE THREAD

**Issue by VIXIVIXIV** [SideStore/SideStore#492]
### Describe the bug

When trying to self-refresh or update sidestore on this version, the app always crashes before refreshing completes. Other apps can be refreshed, but Sidestore itself specifically doesn't refresh.

Interestingly, the mislabeled "Obsolete" build of 0.5.1 with MDC works just fine

Will upload error log, but I don't think it'll be of much help, crash occurs very early in the process

### Instructions to reproduce

1) Install sidestore
 (Optional) confirm installing and refreshing other apps works
2) Attempt to refresh sidestore

### What version of SideStore are you using?

0.5.1-nightly.2023.09.18.1+44125a5

**Comment by VIXIVIXIV** [comment]
[minimuxer.log](https://github.com/SideStore/SideStore/files/12733284/minimuxer.log)

**Comment by naturecodevoid** [comment]
Need crash report from settings -> privacy -> analytics -> data then search for the one with the most recent date

**Comment by naturecodevoid** [comment]
This was already fixed. Please use normal SideStore for now since the MDC build doesn't seem to have the fix

**Comment by naturecodevoid** [comment]
You can try this MDC build: https://github.com/preland/SideStore/actions/runs/6235658607
