### ISSUE TITLE
[BUG] Having sidestore widget on home screen causes Sidestore to crash after successful first refresh of any non-sidestore app 

### ISSUE THREAD

**Issue by VIXIVIXIV** [SideStore/SideStore#493]
### Describe the bug

When the widget is on the home screen and apps are being refreshed (either refresh all or refresh a single app), as soon as one app finishes refreshing the app immediately crashes. Sometimes, when refresh all is called from shortcuts or automations, you'll get lucky and everything will refresh, but on most attempts it just refreshes no more than one and crashes.

Refreshing sidestore itself does exit normally, it correctly does the thing where it kicks you out to the home screen while showing the notification.

This bug seems to have been present for a decent amount of time, it was mentioned in the comments of another issue in early August, but I was able to reproduce it on the latest public 0.5.1 MDC build

### Instructions to reproduce

1. install sidestore
2. install some other app
3. add widget to home screen
4. attempt to refresh 

### What version of SideStore are you using?

0.5.1-nightly.2023.09.18.1+44125a5

**Comment by VIXIVIXIV** [comment]
Edit: entered the latest version because the crashing behavior for other apps is the same, but NB that in the latest MDC release, the sidestore self-refresh is also broken, but for seemingly unrelated reasons

**Comment by nythepegasus** [comment]
Hello! Does 0.5.2 fix this issue? Make sure to use AltServer to install it, or install SideStore.ipa inside SideStore.
