### ISSUE TITLE
[BUG] Unable to manage profiles

### ISSUE THREAD

**Issue by aaronliu0130** [SideStore/SideStore#494]
### Describe the bug

No toasts appear when this occurs, so I'm not sure which error this is. I took a guess
![A bunch of refreshing failures](https://media.discordapp.net/attachments/942016116530745375/1156721126987288606/IMG_2146.png)
Additionally, the main tab's remaining days are inconsistent with those in the App IDs tab.
![In the main tab all shows 7 days but in manage app IDs a bunch of 1 day and 6 day](https://github.com/SideStore/SideStore/assets/11874211/486bb981-de2d-446c-a8b7-97fb3f7b71f8)
I have tried shutting wireguard down and up again. I am connected.

### Instructions to reproduce

1. install app
2. wait at least 1 day
3. refresh

### What version of SideStore are you using?

Both 0.5.1 and 0.5.2-nightly.2023.09.18.1+0deae92 have this problem. Media taken on 0.5.2...。

### Other info

Suspiciously, installing new apps still works

Also, SideStore 0.5.1 isn't in the official listing when you click on "SideStore" yet

**Comment by Decidueye344** [comment]
When this happens i usually retry to refresh the app or try to re open the app and it fixes interestingly

**Comment by aaronliu0130** [comment]
Doesn’t for me

**Comment by naturecodevoid** [comment]
Refresh pairing file

**Comment by aaronliu0130** [comment]
Ah, ok. Could "Try refreshing your pairing file" be added to the log?

**Comment by aaronliu0130** [comment]
Also, the past tense of "reset" is "reset", the app shouldn't say "resetted". I'm pretty sure it refreshed correctly now and there are no error logs but the app ID display is still off. Discord truncates the extension to `.mobiledevicepair`, could that extension be recognized as well?
