### ISSUE TITLE
[FEATURE REQUEST] Additional Sources

### ISSUE THREAD

**Issue by SirDank** [SideStore/SideStore#495]
### Describe the feature

Add the following sources:
- https://github.com/qnblackcat/uYouPlus
- https://github.com/SpotCompiled/SpotC-Plus-Plus
- https://github.com/SerenaKit/Santander

### Use cases

Easier to install directly!

**Comment by nythepegasus** [comment]
We probably won't be adding these sources as trusted sources as they house tweaked applications of App Store apps like Youtube and Spotify (which have their own premium subscriptions these tweaks circumvent). If the sources didn't have that, then we could approve them. For now users will have to manually add these sources if they would like to use them.

**Comment by SirDank** [comment]
understandable! yeah, Santander is great, check it out!
