### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KombatGod7** [SideStore/SideStore#498]
### Describe the bug

Whenever I try to enable JIT on an application, (specifically DolphiniOS) it comes up with the error: Can not start a Debug Server on the device.

### Instructions to reproduce

Download an emulator that requires JIT on Side Store. Long press on the application inside side store and press “Enable JIT”.

### What version of SideStore are you using?

0.5.1

### Other info

I am on iOS 17 iPhone 13 mini.

**Comment by naturecodevoid** [comment]
JIT is not supported on iOS 17 yet, duplicate issue

**Comment by KombatGod7** [comment]
Okay thank you. Sorry, didn’t notice duplicate.
