### ISSUE TITLE
[BUG] Cannot Deactivate Apps

### ISSUE THREAD

**Issue by AryxPlayz** [SideStore/SideStore#499]
### Describe the bug

[BUG] Cannot Deactivate Apps; discovered it when trying to deactivate Delta or any other app

### Instructions to reproduce

1. Install Sidestore + PojavLauncher + Delta
2. try and deactivate one

### What version of SideStore are you using?

0.5.1

### Other info

I tried to activate delta and i can't do it and i've tried pojavlauncher and nothing works, have to delete the apps. here is a screenshot of what i see:
![IMG_5838](https://github.com/SideStore/SideStore/assets/102956046/6c28293f-9fda-4550-b03c-03249503ea9b)

**Comment by Decidueye344** [comment]
You need to use 5.0 for now

**Comment by naturecodevoid** [comment]
Duplicate issue
