### ISSUE TITLE
[BUG] SideStore crashes while VPN is on

### ISSUE THREAD

**Issue by Yan-Jobs** [SideStore/SideStore#500]
### Describe the bug

SideStore freezes/crashes after some time while on the app. Like, its not on.y when sideloading its every time, scrolling between packages, etc. ITS ONLY WHEN THE VPN IS ON

### Instructions to reproduce

Just open SideStore & VPN and wait, now it’s frozen

### What version of SideStore are you using?

0.5.1

### Other info

[SideStore-2023-10-04-094727.txt](https://github.com/SideStore/SideStore/files/12800795/SideStore-2023-10-04-094727.txt)

**Comment by kaanaaas** [comment]
Yeah im struggling with that error too. Did you find anything about that?

**Comment by Yan-Jobs** [comment]
> Yeah im struggling with that error too. Did you find anything about that?

nope sorry

**Comment by kaanaaas** [comment]
Bro i found a way to use it i think. Just install 5.0 and you should be good to go

**Comment by Spidy123222** [comment]
0.5.2 should be good by now.

**Comment by nythepegasus** [comment]
Closing as stale for now, let me know otherwise!

**Comment by aabd-1** [comment]
Anyone found a solution?
