### ISSUE TITLE
[BUG] SideStore Crashes when trying to refresh 

### ISSUE THREAD

**Issue by cody2sicc** [SideStore/SideStore#501]
### Describe the bug

When I go to try and refresh all of my apps (or any one of them individually) it starts, and the progression bar seems to be acting normal, but then SideStore crashes. I tried reinstalling SideStore a few times but no avail. Nothing shows up on “Refresh attempts”, nor does anything show up in the error log.

### Instructions to reproduce

I would jus try to refresh the apps like you normally would

### What version of SideStore are you using?

0.5.1

**Comment by Spidy123222** [comment]
This was fixed by exiting the app before it installs the app.
