### ISSUE TITLE
[BUG] unable to get 2FA from v3 anisette servers

### ISSUE THREAD

**Issue by BrianMak94** [SideStore/SideStore#503]
### Describe the bug

iOS version: iPadOS 17 (beta1-latest), on iPad Pro 12.9 2018
SideStore version: all

When I select SideStore or Macley as my anisette server, SideStore will prompt me to enter the 2FA, but none of my devices will get them. Though it works perfectly with Provision, it’s just more annoying getting asked for 2FA every time I need to use SideStore. 

This problem seems to only occur in this device, on my iPhone SE 1st gen, iOS 15.7.9, this problem never occurs. 

### Instructions to reproduce

Select SideStore / Macley server as anisette, log in or refresh. There will be a SideStrore prompt asking for 2FA but no 2FA will be received from Apple. 

### What version of SideStore are you using?

All, since the introduction of V3 anisette

**Comment by naturecodevoid** [comment]
Not much we can do about this. You can try hosting your own provision server (however, the SideStore anisette server uses provision anyway so I don't see what would be different except it being a v1 server)
