### ISSUE TITLE
[BUG] Unable to create backup directory. The AltStore app group could not be found. (Deactivation)

### ISSUE THREAD

**Issue by aaronliu0130** [SideStore/SideStore#505]
### Describe the bug

I cannot deactivate apps because apparently AltStore is needed to backup it?
![IMG_2291](https://github.com/SideStore/SideStore/assets/11874211/0fcc9031-8eeb-4d96-97e1-8a4ceca49986)

### Instructions to reproduce

1. Install app
2. Deactivate app

### What version of SideStore are you using?

SideStore0.5.2-nightly.2023.09.18.1+0deae92

**Comment by naturecodevoid** [comment]
Duplicate

**Comment by aaronliu0130** [comment]
Of what?

**Comment by aaronliu0130** [comment]
Ah, #477. Could a title be added for that?
