### ISSUE TITLE
[BUG] Cannot start a instproxy server on this device.

### ISSUE THREAD

**Issue by peterge1998** [SideStore/SideStore#511]
### Describe the bug

After receiving the error "Cannot start a instproxy server on this device.", I was able to create 00008101-000D29A62646001E.mobiledevicepairing using the "Enable JIT" option of SideServer.
I renamed it to ALTPairingFile.mobiledevicepairing, as suggested by @hrz6976. Now the SideStore Storage looks like this:

![image](https://github.com/SideStore/SideStore/assets/47355238/2f9d32af-f038-456e-8561-19b97698a3ea)

I found these steps on https://wiki.sidestore.io/guides/getting-started/#pairing-file.

Can you fix this? Or add it to the Getting started menu if this needs to be done before using SideStore?
![image](https://github.com/SideStore/SideStore/assets/47355238/9e72eb44-0846-4542-851c-2850802e05f8)

### Instructions to reproduce

Follow getting started, launch the app, see this error

### What version of SideStore are you using?

1.4.2

### Other info

iPhone 12 iOS 16.6

**Comment by peterge1998** [comment]
See https://github.com/SideStore/SideStore/issues/482 for more details

**Comment by Konngitas** [comment]
I am also facing this issue. Installed SideStore using SideServer. Have not done any steps besides whats listed on the SideStore getting started page.

iPhone 15 Pro Max, ios 17.0.3

**Comment by naturecodevoid** [comment]
Duplicate

**Comment by peterge1998** [comment]
> Duplicate

Duplicate to which issue? I cant find another with the same error, just closed ones

**Comment by naturecodevoid** [comment]
There are probably 10 instproxy issues at this point. Refresh pairing file, ensure vpn is on, ask in discord for more help
