### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HamBam100** [SideStore/SideStore#512]
### Describe the bug

I can’t seem to refresh SideStore ipa

### Instructions to reproduce

Whenever clicking the refresh button I am faced with the large error message “ The operation couldn’t be completed. Unable to install the app: Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.5C7M5883UM.com.SideStore.SideStore" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.5C7M5883UM.com.SideStore.SideStore, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=884, NSUnderlyingError=0x9d8e1ea20 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.5C7M5883UM.AltWidget that does not match required prefix of com.5C7M5883UM.com.SideStore.SideStore. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.5C7M5883UM.AltWidget that does not match required prefix of com.5C7M5883UM.com.SideStore.SideStore. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1392, NSLocalizedFailureReason=Mismatched bundle IDs.}}}”

### What version of SideStore are you using?

0.5.1

**Comment by naturecodevoid** [comment]
Should be fixed in 0.5.2, see discord
