### ISSUE TITLE
[BUG] Cannot refresh SideStore: The provided app group is invalid.

### ISSUE THREAD

**Issue by aaronliu0130** [SideStore/SideStore#513]
### Describe the bug

I’ve updated my pairing file to resolve messages about an inability to manage profiles. Now I can refresh other apps but not SideStore, which gives an error code of com.rileytestut.ALTAppleAPI error 14
![IMG_2370](https://github.com/SideStore/SideStore/assets/11874211/c0ed79db-803a-4899-8f9d-7277aa009848)
I put in the new pairing file around 9:20.

### Instructions to reproduce

Try to refresh SideStore

### What version of SideStore are you using?

SideStore 0.5.2-nightly.2023.10.17.1+766fb89

**Comment by milankkk** [comment]
#509

**Comment by aaronliu0130** [comment]
That issue is a duplicate of another which I can't find

**Comment by naturecodevoid** [comment]
Duplicate and fixed in 0.5.2
