### ISSUE TITLE
[BUG] Refresh Sidestore failed

### ISSUE THREAD

**Issue by BiobaTiry** [SideStore/SideStore#516]
### Describe the bug

When i try to refresh the app, i’ve got this error:

23:09:08 [INFO] minimuxer::muxer: Logger initialized!!
23:09:08 [INFO] minimuxer::muxer: minimuxer has started!
23:09:08 [INFO] minimuxer::muxer: Starting listener
23:09:08 [INFO] minimuxer::heartbeat: Starting heartbeat thread
23:09:11 [INFO] minimuxer::heartbeat: Heartbeat success!
23:09:20 [INFO] minimuxer: minimuxer is ready!
23:09:21 [INFO] minimuxer::heartbeat: Heartbeat success!
23:09:24 [INFO] minimuxer::provision: Installing provisioning profile
23:09:24 [INFO] minimuxer::provision: Successfully installed provisioning profile!
23:09:24 [INFO] minimuxer::provision: Installing provisioning profile
23:09:24 [INFO] minimuxer::provision: Successfully installed provisioning profile!
23:09:29 [INFO] minimuxer::install: Yeeting IPA for bundle ID: com.SideStore.SideStore
23:09:29 [INFO] minimuxer::install: Created PublicStaging directory
23:09:29 [INFO] minimuxer::install: Created bundle ID directory
23:09:29 [INFO] minimuxer::install: Sending bytes of ipa
23:09:29 [INFO] minimuxer::install: Success
23:09:29 [INFO] minimuxer::install: Installing app for bundle ID: com.SideStore.SideStore
23:09:29 [INFO] minimuxer::install: Installing
23:09:29 [ERROR] rusty_libimobiledevice::services::instproxy: Instproxy install: InvalidArg (APIInternalError): Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.2T5M4WZG79.com.SideStore.SideStore" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.2T5M4WZG79.com.SideStore.SideStore, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=869, NSUnderlyingError=0x668f1fd80 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.2T5M4WZG79.AltWidget that does not match required prefix of com.2T5M4WZG79.com.SideStore.SideStore. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.2T5M4WZG79.AltWidget that does not match required prefix of com.2T5M4WZG79.com.SideStore.SideStore. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1382, NSLocalizedFailureReason=Mismatched bundle IDs.}}}
23:09:32 [INFO] minimuxer::heartbeat: Heartbeat success!
23:09:43 [INFO] minimuxer::heartbeat: Heartbeat success!
23:09:53 [INFO] minimuxer::heartbeat: Heartbeat success!
23:10:23 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
23:10:23 [INFO] minimuxer::heartbeat: Heartbeat success!
23:10:33 [INFO] minimuxer::heartbeat: Heartbeat success!
23:10:53 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
23:10:53 [INFO] minimuxer::heartbeat: Heartbeat success!
23:13:27 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
23:13:32 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
23:13:32 [INFO] minimuxer::heartbeat: Heartbeat success!
23:13:42 [INFO] minimuxer::heartbeat: Heartbeat success!
23:13:53 [INFO] minimuxer::heartbeat: Heartbeat success!
23:14:04 [INFO] minimuxer::heartbeat: Heartbeat success!
23:14:14 [INFO] minimuxer::heartbeat: Heartbeat success!
23:16:39 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
23:16:39 [INFO] minimuxer::heartbeat: Heartbeat success!
23:16:50 [INFO] minimuxer::heartbeat: Heartbeat success!
23:17:37 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
23:17:37 [INFO] minimuxer::heartbeat: Heartbeat success!
23:17:51 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
23:17:51 [INFO] minimuxer::heartbeat: Heartbeat success!
23:18:52 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
23:18:52 [INFO] minimuxer::heartbeat: Heartbeat success!

### Instructions to reproduce

Press “refresh all” button or refresh Sidestore only

### What version of SideStore are you using?

0.5.2

**Comment by naturecodevoid** [comment]
Duplicate
