### ISSUE TITLE
[BUG] SideStore doesn’t open on 17.1

### ISSUE THREAD

**Issue by peterge1998** [SideStore/SideStore#518]
### Describe the bug

When I tap the app the opening animation plays, but before I can see anything inside the app closes again and I am back in app gallery…

### Instructions to reproduce

Tap on app on iOS 17.1

### What version of SideStore are you using?

0.5.2

**Comment by naturecodevoid** [comment]
SideStore expired, you need to reinstall. Make sure to refresh SideStore asap about reinstalling it

**Comment by peterge1998** [comment]
Got it working. I switched the Apple ID account which lead to SideStore being untrusted on my device
