### ISSUE TITLE
Unable to connect to the device, make sure Wireguard is enabled and you're connected to WiFi

### ISSUE THREAD

**Issue by Zgm1020** [SideStore/SideStore#519]
### Describe the bug

iOS 16.3.1 This problem occurs when the newly installed SideStore is opened. Both wifi and WireGuard are turned on and cannot be connected.

### Instructions to reproduce

05:22:23 [INFO] minimuxer::muxer: Logger initialized!!
05:22:23 [INFO] minimuxer::muxer: minimuxer has started!
05:22:23 [INFO] minimuxer::muxer: Starting listener
05:22:23 [INFO] minimuxer::mounter: Starting image mounter
05:22:23 [INFO] minimuxer::heartbeat: Starting heartbeat thread
05:22:26 [INFO] minimuxer: minimuxer is not ready. device connection succeeded: false; at least 1 device exists: true; last heartbeat was a success: false; developer disk image is mounted (not counted): false; started: true
05:22:28 [INFO] minimuxer::mounter: Trying to mount dev image
05:22:28 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:32 [INFO] minimuxer: minimuxer is not ready. device connection succeeded: true; at least 1 device exists: true; last heartbeat was a success: false; developer disk image is mounted (not counted): false; started: true
05:22:33 [ERROR] minimuxer::mounter: Unable to start mobile image mounter: UnknownError
05:22:33 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:33 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:33 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:33 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:33 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:33 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:34 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
05:22:34 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError

### What version of SideStore are you using?

0.5.2

**Comment by xzrvr** [comment]
same issue, using ios 17.1

**Comment by Zgm1020** [comment]
> same issue, using ios 17.1

I've tried it a few times and it still doesn't work

**Comment by naturecodevoid** [comment]
refresh pairing file, make sure VPN is on

**Comment by sumanth-culli** [comment]
Why is this closed? I'm still facing this issue. using ios 17.1

**Comment by naturecodevoid** [comment]
Refresh your pairing file and turn VPN off and on

**Comment by banang** [comment]
> Refresh your pairing file and turn VPN off and on

i'm noob, what does  refreshing pairing file mean?

**Comment by Zgm1020** [comment]
> > Refresh your pairing file and turn VPN off and on
> 
> i'm noob, what does refreshing pairing file mean?

Make sure your network can connect to sidestore's servers

**Comment by yugansh77** [comment]
> > > Refresh your pairing file and turn VPN off and on
> > 
> > 
> > i'm noob, what does refreshing pairing file mean?
> 
> Make sure your network can connect to sidestore's servers

Hello, we are noobs in this area here! Could you please be more specific on how to make this work? Any specific steps?

**Comment by dimaszulfa** [comment]
you should reset/refreshing pairing file. 
1. go to side store website, https://sidestore.io/#get-started
2. click **just want the downloads instead**
3. Choose jitterbug for windows
4. Extract it.
5. Connect your device
6. Open CMD on that extract folder location.
7. Drag jitterbugpair to your CMD
8. Give permission on your device
9. Drag again jitterbugpair to your device
10. Then, see on your extract folder. If there is a new file, copy that file to your device
11. Go to your sidestore application on device
12. if there is a new popup, click on it and you can pair that file.
13. close side store & wireguard
14. Reconnect wireguard
15. Try again, goodluck

Hope it will work, it's works for me.
IOS 17.1 Device IP 11

**Comment by yugansh77** [comment]
> you should reset/refreshing pairing file.
> 
> 1. go to side store website, https://sidestore.io/#get-started
> 2. click **just want the downloads instead**
> 3. Choose jitterbug for windows
> 4. Extract it.
> 5. Connect your device
> 6. Open CMD on that extract folder location.
> 7. Drag jitterbugpair to your CMD
> 8. Give permission on your device
> 9. Drag again jitterbugpair to your device
> 10. Then, see on your extract folder. If there is a new file, copy that file to your device
> 11. Go to your sidestore application on device
> 12. if there is a new popup, click on it and you can pair that file.
> 13. close side store & wireguard
> 14. Reconnect wireguard
> 15. Try again, goodluck
> 
> Hope it will work, it's works for me. IOS 17.1 Device IP 11

Thanks for providing the detailed steps
I was able to follow till step 11 but am not seeing any popups when i open sidestore after step 11
So how do we use the file created by jitterbugpair and give it to sidestore?

Thanks again!

**Comment by amrpyt** [comment]
@dimaszulfa 
What do u mean by copying the file to my device? How can it from my pc to my iPhone?
I have try to move it to the CMD but it didn't work!

Plz explain more

**Comment by yugansh77** [comment]
> > you should reset/refreshing pairing file.
> > 
> > 1. go to side store website, https://sidestore.io/#get-started
> > 2. click **just want the downloads instead**
> > 3. Choose jitterbug for windows
> > 4. Extract it.
> > 5. Connect your device
> > 6. Open CMD on that extract folder location.
> > 7. Drag jitterbugpair to your CMD
> > 8. Give permission on your device
> > 9. Drag again jitterbugpair to your device
> > 10. Then, see on your extract folder. If there is a new file, copy that file to your device
> > 11. Go to your sidestore application on device
> > 12. if there is a new popup, click on it and you can pair that file.
> > 13. close side store & wireguard
> > 14. Reconnect wireguard
> > 15. Try again, goodluck
> > 
> > Hope it will work, it's works for me. IOS 17.1 Device IP 11
> 
> Thanks for providing the detailed steps I was able to follow till step 11 but am not seeing any popups when i open sidestore after step 11 So how do we use the file created by jitterbugpair and give it to sidestore?
> 
> Thanks again!

Hello, i tried refreshing it a couple of days later.
Now it does start to refresh but then i get the following error:

“Unable to install the app: Error Domain=IXError Domain Code=2 "Failed to set app extension placeholders for com.X7D8QJ6D9.com. SideStore.SideStore" Userinfo=(NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.X7D8QJ6D9.com.SideStore. SideStore, FunctionName=+[IXPlaceholder_placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:],SourceFileLine=884, NSUnderlyingError=Oxb84a0f00 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com. SideStore. SideStore.X7D8QVJ6D9.AltWidget that does not match required prefix of com.X7D8QVJ6D9.com. SideStore. SideStore. for parent" UserInfo=<NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore. SideStore. X7D8QVJ6D9.AltWidget that does not match required prefix of com. X7D8QVJ6D9.com.SideStore. SideStore. for parent, FunctionName=-[XPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1392, NSLocalizedFailureReason=Mismatched bundle IDs. }}”


So what does it mean?
Is there still an issue with pairing file or is it something else now?

**Comment by baobaodu** [comment]
same ios17.3

**Comment by TradeDraft** [comment]
> > > you should reset/refreshing pairing file.
> > > 
> > > 1. go to side store website, https://sidestore.io/#get-started
> > > 2. click **just want the downloads instead**
> > > 3. Choose jitterbug for windows
> > > 4. Extract it.
> > > 5. Connect your device
> > > 6. Open CMD on that extract folder location.
> > > 7. Drag jitterbugpair to your CMD
> > > 8. Give permission on your device
> > > 9. Drag again jitterbugpair to your device
> > > 10. Then, see on your extract folder. If there is a new file, copy that file to your device
> > > 11. Go to your sidestore application on device
> > > 12. if there is a new popup, click on it and you can pair that file.
> > > 13. close side store & wireguard
> > > 14. Reconnect wireguard
> > > 15. Try again, goodluck
> > > 
> > > Hope it will work, it's works for me. IOS 17.1 Device IP 11
> > 
> > 
> > Thanks for providing the detailed steps I was able to follow till step 11 but am not seeing any popups when i open sidestore after step 11 So how do we use the file created by jitterbugpair and give it to sidestore?
> > Thanks again!
> 
> Hello, i tried refreshing it a couple of days later. Now it does start to refresh but then i get the following error:
> 
> “Unable to install the app: Error Domain=IXError Domain Code=2 "Failed to set app extension placeholders for com.X7D8QJ6D9.com. SideStore.SideStore" Userinfo=(NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.X7D8QJ6D9.com.SideStore. SideStore, FunctionName=+[IXPlaceholder_placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:],SourceFileLine=884, NSUnderlyingError=Oxb84a0f00 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com. SideStore. SideStore.X7D8QVJ6D9.AltWidget that does not match required prefix of com.X7D8QVJ6D9.com. SideStore. SideStore. for parent" UserInfo=<NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore. SideStore. X7D8QVJ6D9.AltWidget that does not match required prefix of com. X7D8QVJ6D9.com.SideStore. SideStore. for parent, FunctionName=-[XPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1392, NSLocalizedFailureReason=Mismatched bundle IDs. }}”
> 
> So what does it mean? Is there still an issue with pairing file or is it something else now?

I have same issue SideStore 5.5 beta version

**Comment by zebogan** [comment]
deleting apps installed from a previous sidestore install fixed it for me, no idea if this is a solution or if it was unrelated

**Comment by wojtassonek** [comment]
> you should reset/refreshing pairing file.
> 
> 1. go to side store website, https://sidestore.io/#get-started
> 2. click **just want the downloads instead**
> 3. Choose jitterbug for windows
> 4. Extract it.
> 5. Connect your device
> 6. Open CMD on that extract folder location.
> 7. Drag jitterbugpair to your CMD
> 8. Give permission on your device
> 9. Drag again jitterbugpair to your device
> 10. Then, see on your extract folder. If there is a new file, copy that file to your device
> 11. Go to your sidestore application on device
> 12. if there is a new popup, click on it and you can pair that file.
> 13. close side store & wireguard
> 14. Reconnect wireguard
> 15. Try again, goodluck
> 
> Hope it will work, it's works for me. IOS 17.1 Device IP 11

tysm u helped me soooo much thank you. Man
