### ISSUE TITLE
[BUG] Refresh SideStore or installing a new app

### ISSUE THREAD

**Issue by soulmatelh** [SideStore/SideStore#520]
### Describe the bug

I am unable to refresh SideStore or install a new app successfully

### Instructions to reproduce

21:09:38 [INFO] minimuxer::muxer: Logger initialized!!
21:09:38 [INFO] minimuxer::muxer: minimuxer has started!
21:09:38 [INFO] minimuxer::muxer: Starting listener
21:09:38 [INFO] minimuxer::heartbeat: Starting heartbeat thread
21:09:40 [INFO] minimuxer::heartbeat: Heartbeat success!
21:09:40 [INFO] minimuxer: minimuxer is ready!
21:09:51 [INFO] minimuxer::heartbeat: Heartbeat success!
21:10:01 [INFO] minimuxer::heartbeat: Heartbeat success!
21:10:11 [INFO] minimuxer::install: Yeeting IPA for bundle ID: com.firecore.infuse
21:10:11 [INFO] minimuxer::install: Created PublicStaging directory
21:10:11 [INFO] minimuxer::install: Created bundle ID directory
21:10:11 [INFO] minimuxer::install: Sending bytes of ipa
21:10:11 [INFO] minimuxer::install: Success
21:10:12 [INFO] minimuxer::install: Installing app for bundle ID: com.firecore.infuse
21:10:12 [INFO] minimuxer::install: Installing
21:10:12 [INFO] minimuxer::heartbeat: Heartbeat success!
21:10:20 [ERROR] rusty_libimobiledevice::services::instproxy: Instproxy install: InvalidArg (ApplicationVerificationFailed): This device has reached the maximum number of installed apps using a free developer profile: {(
    "M89P43525B.com.M89P43525B.com.SideStore.SideStore",
    "UKY2U96652.com.firecore.infuse.UKY2U96652",
    "UKY2U96652.person.youniaogu.MangaReader.UKY2U96652"
)}
21:10:22 [INFO] minimuxer::heartbeat: Heartbeat success!
21:10:25 [INFO] minimuxer: minimuxer is ready!
21:10:33 [INFO] minimuxer::heartbeat: Heartbeat success!
21:10:44 [INFO] minimuxer::heartbeat: Heartbeat success!
21:10:45 [INFO] minimuxer::install: Yeeting IPA for bundle ID: com.SideStore.SideStore
21:10:45 [INFO] minimuxer::install: Created PublicStaging directory
21:10:45 [INFO] minimuxer::install: Created bundle ID directory
21:10:45 [INFO] minimuxer::install: Sending bytes of ipa
21:10:45 [INFO] minimuxer::install: Success
21:10:45 [INFO] minimuxer::install: Installing app for bundle ID: com.SideStore.SideStore
21:10:45 [INFO] minimuxer::install: Installing
21:10:45 [ERROR] rusty_libimobiledevice::services::instproxy: Instproxy install: InvalidArg (APIInternalError): Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.M89P43525B.com.SideStore.SideStore" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.M89P43525B.com.SideStore.SideStore, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=869, NSUnderlyingError=0xc1ae24730 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.M89P43525B.AltWidget that does not match required prefix of com.M89P43525B.com.SideStore.SideStore. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.M89P43525B.AltWidget that does not match required prefix of com.M89P43525B.com.SideStore.SideStore. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1382, NSLocalizedFailureReason=Mismatched bundle IDs.}}}
21:10:54 [INFO] minimuxer::heartbeat: Heartbeat success!
21:11:41 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
21:11:42 [INFO] minimuxer::heartbeat: Heartbeat success!
21:11:52 [INFO] minimuxer::heartbeat: Heartbeat success!
21:12:00 [INFO] minimuxer: minimuxer is ready!
21:12:03 [INFO] minimuxer::heartbeat: Heartbeat success!
21:12:14 [INFO] minimuxer::heartbeat: Heartbeat success!
21:12:24 [INFO] minimuxer::heartbeat: Heartbeat success!
21:12:29 [INFO] minimuxer::install: Yeeting IPA for bundle ID: com.firecore.infuse
21:12:29 [INFO] minimuxer::install: Created PublicStaging directory
21:12:29 [INFO] minimuxer::install: Created bundle ID directory
21:12:29 [INFO] minimuxer::install: Sending bytes of ipa
21:12:30 [INFO] minimuxer::install: Success
21:12:30 [INFO] minimuxer::install: Installing app for bundle ID: com.firecore.infuse
21:12:30 [INFO] minimuxer::install: Installing
21:12:34 [INFO] minimuxer::heartbeat: Heartbeat success!
21:12:37 [ERROR] rusty_libimobiledevice::services::instproxy: Instproxy install: InvalidArg (ApplicationVerificationFailed): This device has reached the maximum number of installed apps using a free developer profile: {(
    "M89P43525B.com.M89P43525B.com.SideStore.SideStore",
    "UKY2U96652.com.firecore.infuse.UKY2U96652",
    "UKY2U96652.person.youniaogu.MangaReader.UKY2U96652"
)}
21:12:45 [INFO] minimuxer::heartbeat: Heartbeat success!
21:15:23 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
21:15:36 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
21:15:41 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
21:15:47 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
21:16:00 [ERROR] minimuxer::heartbeat: Failed to create heartbeat client: UnknownError
21:16:01 [INFO] minimuxer::heartbeat: Heartbeat success!
21:16:02 [INFO] minimuxer: minimuxer is ready!
21:16:11 [INFO] minimuxer::heartbeat: Heartbeat success!
21:16:21 [INFO] minimuxer::install: Yeeting IPA for bundle ID: com.SideStore.SideStore
21:16:21 [INFO] minimuxer::heartbeat: Heartbeat success!
21:16:21 [INFO] minimuxer::install: Created PublicStaging directory
21:16:21 [INFO] minimuxer::install: Created bundle ID directory
21:16:21 [INFO] minimuxer::install: Sending bytes of ipa
21:16:22 [INFO] minimuxer::install: Success
21:16:22 [INFO] minimuxer::install: Installing app for bundle ID: com.SideStore.SideStore
21:16:22 [INFO] minimuxer::install: Installing
21:16:22 [ERROR] rusty_libimobiledevice::services::instproxy: Instproxy install: InvalidArg (APIInternalError): Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.M89P43525B.com.SideStore.SideStore" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.M89P43525B.com.SideStore.SideStore, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=869, NSUnderlyingError=0xc1ae1df90 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.M89P43525B.AltWidget that does not match required prefix of com.M89P43525B.com.SideStore.SideStore. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.M89P43525B.AltWidget that does not match required prefix of com.M89P43525B.com.SideStore.SideStore. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1382, NSLocalizedFailureReason=Mismatched bundle IDs.}}}
21:16:32 [INFO] minimuxer::heartbeat: Heartbeat success!
21:16:47 [ERROR] minimuxer::heartbeat: Heartbeat recv failed: MuxError
21:16:47 [INFO] minimuxer::heartbeat: Heartbeat success!

### What version of SideStore are you using?

0.5.2

### Other info

iOS 17.1 iPhone 14 Pro

**Comment by soulmatelh** [comment]
install a new app successfully is ok，but I am unable to refresh SideStore

**Comment by xzrvr** [comment]
same issue, iphone 11, ios 17.1

**Comment by xzrvr** [comment]
found a workaround in the discord:
get latest sidestore ipa, install with sidestore, click remove extension and refresh will work

**Comment by soulmatelh** [comment]
> 在不和谐中找到了解决方法： 获取最新的 sidestore ipa，使用 sidestore 安装，单击删除扩展并刷新即可工作

Okay, thank you.

**Comment by 3TaeTae** [comment]
same issue on iPhone 15 Pro Max, ios 17.1 version

**Comment by naturecodevoid** [comment]
Duplicate
