### ISSUE TITLE
[BUG] Apps not verified despite 6 days remaining

### ISSUE THREAD

**Issue by peterge1998** [SideStore/SideStore#522]
### Describe the bug

I installed them yesterday. They still had 7 day’s remaining. Why aren’t they verified anymore?
![image](https://github.com/SideStore/SideStore/assets/47355238/3e90c187-63dc-4782-ae8c-063152f1cdf5)

### Instructions to reproduce

Install
Wait

### What version of SideStore are you using?

0.5.2

**Comment by Spidy123222** [comment]
When installing sidestore you need to refresh right after you install it. Otherwise it will expire early.

**Comment by peterge1998** [comment]
> When installing sidestore you need to refresh right after you install it. Otherwise it will expire early.

Reinstalled and refreshed it right now like u suggested :)

**Comment by peterge1998** [comment]
And they are not verified again. I installed them this morning with 7 days remaining :(
I don’t know what’s causing this, but there seems to be an error on iOS 17.1 & 15 PM…

**Comment by naturecodevoid** [comment]
Probably another signing service / app

**Comment by peterge1998** [comment]
What do you mean? I did not use any other solution. 
Or do you mean I should try another one than SideStore?

**Comment by naturecodevoid** [comment]
Oh, well it that case it's probably SideStore revoking its own certificate which is a known issue

**Comment by Spidy123222** [comment]
We have instructions now to fix this by refreshing after the install

**Comment by alfianfid** [comment]
I have the same problem after 3 days have passed sidestore cannot be opened and other apps can still be opened is there a solution to this problem I have the same problem after 3 days have passed sidestore cannot be opened and other apps can still be opened is there a solution to this problem

**Comment by MervisDiamonds** [comment]
I have the same issue as well.  I refresh immediately as well.  Does it have something to do with altstore still using some of my app IDs?  I don't have altstore installed.
