### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Tapelessbus2122** [SideStore/SideStore#523]
### Describe the feature

Add an option to allow us to manually install the dmg files and disable the auto download for dmg files.

### Use cases

When the cannot start debug servers bug happen becuz of not being able to download the dmg file.

**Comment by Spidy123222** [comment]
> ### Describe the feature
> 
> Add an option to allow us to manually install the dmg files and disable the auto download for dmg files.
> 
> ### Use cases
> 
> When the cannot start debug servers bug happen becuz of not being able to download the dmg file.
> 
> ### Alternatives
> 
> _No response_

You already can. Just name your dmg files the exact version you have on the device. Only reason it fails is either your internet is slow or cannot access the GitHub download. This is where it's described. https://wiki.sidestore.io/faq/#cannot-start-debugserver
