### ISSUE TITLE
Unable to install the app: Error

### ISSUE THREAD

**Issue by GiampietroCinque** [SideStore/SideStore#524]
### Describe the bug

Sidestore succesfully installed on iPhone 12 with iOS 17. I am able to install and refresh ipa files, but I get this error when I try to update SideStore.
![Immagine WhatsApp 2023-10-30 ore 15 20 57_bd5338e4](https://github.com/SideStore/SideStore/assets/74005347/edd08b0d-9b93-44c0-8aa0-cf76f3d46ebc)

### Instructions to reproduce

The AppleID used for SideStore is different from the one used on the the phone.

### What version of SideStore are you using?

0.5.2

**Comment by m4xolotl** [comment]
I manged to install it by removing app extensions

Not sure if this will bite my ass in the future though

**Comment by naturecodevoid** [comment]
Duplicate
