### ISSUE TITLE
[BUG] IXDomain????

### ISSUE THREAD

**Issue by TheBeeBoi** [SideStore/SideStore#525]
### Describe the bug

I tried to refresh sidestore to test out if it’s working, and and error popped up.

### Instructions to reproduce

Install sidestore using sideserver on windows.

Try refreshing it from the app.

Get a popup about an error (logs attached)

### What version of SideStore are you using?

0.5.2

### Other info

I’m on an iPhone 11, iOS 17.0 (not 17.1).
I tried restarting. Didn’t work.
I installed it from windows.
I tried disconnecting and reconnecting from the VPN profile on wireguard.

I also tried resetting my pairing file and adi.pb. I think it’s an issue with the VPN?

Log:
The operation couldn’t be completed. Unable to install the app: Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.CHVA5DCMJB.com.SideStore.SideStore" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.CHVA5DCMJB.com.SideStore.SideStore, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=869, NSUnderlyingError=0x7ace0fc20 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.CHVA5DCMJB.AltWidget that does not match required prefix of com.CHVA5DCMJB.com.SideStore.SideStore. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.CHVA5DCMJB.AltWidget that does not match required prefix of com.CHVA5DCMJB.com.SideStore.SideStore. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1382, NSLocalizedFailureReason=Mismatched bundle IDs.}}}

**Comment by quindariousgooch** [comment]
same here. iPhone 12 iOS 17.1.

**Comment by naturecodevoid** [comment]
Duplicate
