### ISSUE TITLE
I can't refresh sidestore

### ISSUE THREAD

**Issue by iiLynn** [SideStore/SideStore#529]
### Describe the bug

After starting WireGuard I am going to refresh the applications but the SideStore application is the only one that gives me the following error: `Unable to install the app: Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.YRKH4JAMFG.com.SideStore.SideStore"
UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for
com.YRKH4JAMFG.com.SideStore.SideStore,
FunctionName=+[IXPlaceholder _placeholderForBundle:client: withParent:installType:m etadata:placeholderType:mayBeDeltaPackage:error:],
SourceFileLine=869, NSUnderlyingError=0×76ee04740 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.Y RKH4JAMFG.AltWidget that
does not match required prefix of
com.Y RKH4JAMFG.com.SideStore.SideStore. for
parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle
ID com.SideStore.SideStore.Y RKH4JAMFG.AltWidget
that does not match required prefix of com.YRKH4JAMFG.com.SideStore.SideStore. for
parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:],
SourceFileLine=1382,
NSLocalizedFailureReason=Mismatched bundle IDs.}}} `

### Instructions to reproduce

-Start WireGuard 
-Open SideStore
-Refresh SideStore

### What version of SideStore are you using?

0.5.2

### Other info

I'm on an iPhone 13 Pro with iOS 17.1.1

**Comment by EricThunder** [comment]
Same over here on 15 Pro with iOS 17.1.1 and SideStore 0.5.2

**Comment by KarlosV266** [comment]
I have the same problem here on my Ipad Pro with ios 17.1.1 and sidestore 0.5.2 also with my iphone ios 16.7.2 and sidestore 0.5.2

**Comment by nythepegasus** [comment]
@iiLynn @EricThunder @KarlosV266 This is a duplicate issue, you guys need to use AltServer initially or install SideStore.ipa from inside SideStore to refresh SideStore.

**Comment by KarlosV266** [comment]
> @iiLynn @EricThunder @KarlosV266 This is a duplicate issue, you guys need to use AltServer initially or install SideStore.ipa from inside SideStore to refresh SideStore.

ohh I see, gonna try it. thank u for ur gentle and fast response :)

**Comment by EricThunder** [comment]
> @iiLynn @EricThunder @KarlosV266 This is a duplicate issue, you guys need to use AltServer initially or install SideStore.ipa from inside SideStore to refresh SideStore.

I tried installing it with altstore and it worked! Thank you so much :)

**Comment by reyland44** [comment]
Tried installing the sidestore .ipa from the app itself but I got the same error as when refreshing.

Turns out you need to select yes in "remove app extensions". All is working now!
