### ISSUE TITLE
[BUG] Can’t update apps

### ISSUE THREAD

**Issue by peterge1998** [SideStore/SideStore#530]
### Describe the bug

When I press refresh all Uyou shows as available update. But then SideStore closes to reinstall before you is updated. I would like to have a dedicated check for updates button. 
![IMG_0062](https://github.com/SideStore/SideStore/assets/47355238/774796de-a6d3-400f-bc13-0aece1008f70)

### Instructions to reproduce

Install uyou
Wait for update
Press refresh all

### What version of SideStore are you using?

0.5.2

**Comment by nythepegasus** [comment]
I'll mark this as a duplicate of #472

**Comment by peterge1998** [comment]
Today it showed up as an available update without clicking refresh all
