### ISSUE TITLE
Can't create developer disk for iOS 17

### ISSUE THREAD

**Issue by Vercixx** [SideStore/SideStore#532]
### Describe the bug

So, when I trying to create developer disk using Jitterbugpair, it just shows command prompt for a second, and closes, without creating developer disk. 

### Instructions to reproduce

1. Download jitterbugpair for Windows.
2. Extract all files from zip archive.
3. Connect iPhone to PC (iTunes is installed) 
4. Start jitterbugpair executable.
5. Developer disk didn't created.

### What version of SideStore are you using?

Not installed

### Other info

Is there any way to install SideStore without developer disk?

**Comment by nythepegasus** [comment]
That's not how jitterbugpair works. iOS 17 also completely changed how Developer Disks work, there's a base one at https://github.com/doronz88/DeveloperDiskImage but you will need something like https://github.com/doronz88/pymobiledevice3 to make a Personalized one. 

jitterbugpair is only meant for creating pairing files, and your device has to be plugged in to initiate the pairing process.
