### ISSUE TITLE
[BUG] AFC was unable to manage files on the device

### ISSUE THREAD

**Issue by AryxPlayz** [SideStore/SideStore#533]
### Describe the bug

When I am trying to install or refresh any app on my iphone 6S running iOS 15.8, it gives the error The operation couldn't be completed. AFC was unable to manage files on the device on a stock version of the app.

### Instructions to reproduce

1. Use SideServer on Windows
2. Install it to the device
3. try to install any app

### What version of SideStore are you using?

0.5.2

**Comment by mak448a** [comment]
Just go to setting and reset pairing file

**Comment by Max-Sum** [comment]
This issue happens everytime I trigger refresh from Shortcut App. I could fix this by reset pairing file but it just happens the next time.

**Comment by chadwoodhead** [comment]
I am facing the same error. Resetting the pairing file does not resolve the issue for me.

**Comment by Max-Sum** [comment]
Let me explain why I use Shortcut to refresh.
My device is connected to a VPN permanently because of security policy. So I set a shortcut to switch to WireGuard and trigger refresh every night.
This issue has caused SideStore to expire many times.

**Comment by junepark678** [comment]
AFC errors are usually pairing file errors, please try a new pairing. Closing this issue, please reopen if the issue persists
