### ISSUE TITLE
[FEATURE REQUEST] FIX NEEDING TO REINSTALL APP TO CLEAR APP CACHE

### ISSUE THREAD

**Issue by SourCandy80** [SideStore/SideStore#541]
### Describe the feature

Currently sidestore can start taking space 10+ GB due to failed app installs in its cache. Either a button or automatic clearing of this so-called "cache" would be amazing.

### Use cases

Not taking multiple GB of space :D

**Comment by naturecodevoid** [comment]
Duplicate
