### ISSUE TITLE
Sometime SideStore takes too much space

### ISSUE THREAD

**Issue by abhishekgi** [SideStore/SideStore#543]
### Describe the bug

SideStore is taking too much storage space

### Instructions to reproduce

Don’t know 

### What version of SideStore are you using?

Latest nightly ( I am lazy to tell the exact )

**Comment by abhishekgi** [comment]
![Uploading IMG_0009.png…]()

**Comment by abhishekgi** [comment]
![IMG_0009](https://github.com/SideStore/SideStore/assets/84626229/4083aceb-c9a5-43bd-ba89-a4c575263ce5)

**Comment by SternXD** [comment]
Wait for the next stable release (0.5.3) we have fixes planned for this.

**Comment by abhishekgi** [comment]
> Wait for the next stable release (0.5.3) we have fixes planned for this.

Okay bro
