### ISSUE TITLE
[BUG] Unable to connect to the device, make sure Wireguard is enabled and youre connected to WIFI

### ISSUE THREAD

**Issue by Michuxle** [SideStore/SideStore#544]
### Describe the bug

I have this bug and idk how to fix it. Ive tried installing thru sideserver, altserver, lpm disabled, rebooting my device, making sure that the vpn and wifi enabled, everything! 

### Instructions to reproduce

did it using altstore, regenerated my pairing file twice (iphone 11 ios 17.0.3)

### What version of SideStore are you using?

0.5.2

**Comment by xhfpsxm** [comment]
Same (0.5.2). And I reinstalled to version 0.5.4, with the same result.

**Comment by mak448a** [comment]
It fixes for me if you spam the plus button on the sideload page enough times

**Comment by Michuxle** [comment]
FIXED! Installed 0.5.4 and it finally works! :D

**Comment by KusakabeShi** [comment]
iOS17.2, same issue. custom anisette-v3-server installed and configured but no help
