### ISSUE TITLE
Sidestore crashes when I try to sideload a very big ipa of size 1.93 gb

### ISSUE THREAD

**Issue by abhishekgi** [SideStore/SideStore#546]
### Describe the bug

When I was trying to side load a very big ipa file , it was crashing

### Instructions to reproduce

Open sidestore
Click on my apps section
Click on plus icon 
Select a very big ipa file

### What version of SideStore are you using?

Latest nightly (I am lazy too tell the exact version , I will tell )

### Other info

iPad 9 wifi

**Comment by junepark678** [comment]
Duplicate of #170
