### ISSUE TITLE
[BUG] sidestore0.53 can't resign sidestore

### ISSUE THREAD

**Issue by rgvsp** [SideStore/SideStore#547]
### Describe the bug

![bug](https://github.com/SideStore/SideStore/assets/152142028/1340b113-eb13-4698-a04b-735fd621728a)
![bug](https://github.com/SideStore/SideStore/assets/152142028/b7b02382-cee6-4000-b019-bebf0155f28f)

### Instructions to reproduce

![bug](https://github.com/SideStore/SideStore/assets/152142028/e363d4c0-ae2a-415c-b7a5-f09b3ea76665)

### What version of SideStore are you using?

0.53

**Comment by junepark678** [comment]
Don't use SideServer for Windows
