### ISSUE TITLE
[BUG] crashing on app ids

### ISSUE THREAD

**Issue by sharks90** [SideStore/SideStore#552]
### Describe the bug

Clicking on app ids crashes SideStore 

### Instructions to reproduce

Using iOS 17.0.3 iPhone 13

### What version of SideStore are you using?

SideStore 0.5.4

**Comment by DoIoco** [comment]
This only stable build, I was using the exact same version but with a iPhone SE 2020 (2nd Generation) and the same crashed happened to me so i switched to nightly and didn't have any issues after that :)

**Comment by thren47** [comment]
metoo

**Comment by jimmysofat6864** [comment]
Same issue pressing "View app ID's" causes an instant crash.

**Comment by treatmeniceplz** [comment]
I am also experiencing this on my IPhone 12

**Comment by LouShy** [comment]
Same thing, i've tried reinstalling, nothing changed.

**Comment by junepark678** [comment]
Update SideStore from fake 0.5.4 (some versions of 0.5.3 show as 0.5.4) to real 0.5.4 in releases

**Comment by treatmeniceplz** [comment]
Nah I’m not done yet
