### ISSUE TITLE
SSL ERROR[BUG] 

### ISSUE THREAD

**Issue by mnfari** [SideStore/SideStore#555]
### Describe the bug

ssl error winhttp_callback_status_flag_cert_REV_failed failed to check revocation status
I tried restarting my computer but it didn't work and when I looked at it in altstore reddit, they said I should do a proxy but idk how.
![286828546-ad1c3a95-519a-4178-a130-308032578405](https://github.com/SideStore/SideStore/assets/84629171/f2b170e8-f7ff-44e0-a944-282ea0d83116)

### Instructions to reproduce

When trying to install sidestore for the first time

### What version of SideStore are you using?

1.0.0.2

**Comment by enragedsweat** [comment]
Had the same issues, solved it. Go to VPN and device management, delete all profiles (dns). should work when trying again

**Comment by Spidy123222** [comment]
Looks like you could be blocking Apple servers to prevent revoking of enterprise certificates? Probably a profile like above

**Comment by junepark678** [comment]
this isn't an issue with SideStore but an error with AltServer

**Comment by BlobTheKat** [comment]
> Had the same issues, solved it. Go to VPN and device management, delete all profiles (dns). should work when trying again

This was it!
