### ISSUE TITLE
[BUG] NoIdle timeout not working while sideloading apps in low power mode

### ISSUE THREAD

**Issue by quoctrile8** [SideStore/SideStore#556]
### Describe the bug

NoIdle timeout not working while sideloading apps in low power mode ios 16.6.1

### Instructions to reproduce

Checking NoIdle timeout enabled.
Sideloading ipa.
Screen turns off after 30s.
Tested on iPhone 8 (iOS 16.6.1) and iPhone XS (iOS 16.6.1)

### What version of SideStore are you using?

SideStore 0.5.4

**Comment by junepark678** [comment]
nothing we can do about this, iOS power management makes me want to pull my hair
