### ISSUE TITLE
[BUG] Crashes when trying to View App ID's

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#557]
### Describe the bug

When I press the "View App ID's" button under the My Apps tab in sidestore, the app crashes immediately. I can confirm that I am on the latest stable release as that is what I installed. I downloaded version 0.5.4 in the releases tab so I know it's not an issue of a fake version number. 

### Instructions to reproduce

1. Install SideStore
2. Press the "View App ID's" button under the My Apps tab in sidestore
3. App should crash and go to home screen

### What version of SideStore are you using?

0.5.4

**Comment by jimmysofat6864** [comment]
Screen recording attached showing the issue. Old version didn’t have this issue. 


https://github.com/SideStore/SideStore/assets/69532417/52979122-71c2-4488-b2c7-669b2192e50d

**Comment by BullsEye34** [comment]
I agree

I face the same issue

**Comment by Spidy123222** [comment]
No longer an issue
