### ISSUE TITLE
[BUG] "Failed to set app extension placeholders for com.L9Q796KU79.com.SideStore.SideStore"

### ISSUE THREAD

**Issue by Amazon90** [SideStore/SideStore#558]
### Describe the bug

![75fb2b55-4cbf-4a9f-8979-7d60db4ea59f](https://github.com/SideStore/SideStore/assets/72290820/5250f2db-7149-4ccd-af50-ffb9b7d8fa6c)

https://github.com/SideStore/SideStore/assets/72290820/3db98879-60a0-405d-97a4-9b0b23f4f948

### Instructions to reproduce

1.Open wireguard (Use the conf file provided by "sidestore.io")
2.Refresh application

### What version of SideStore are you using?

v0.5.4

**Comment by pakboy221** [comment]
![image](https://github.com/SideStore/SideStore/assets/152096285/0a0f65e9-cc52-437d-bb60-1345770232f3)

How to fix this error I'm trying to download Watusi 3 plz help me

**Comment by Rehpotsirhc-z** [comment]
The issue was mentioned in #488. The solution is [here](https://github.com/SideStore/SideStore/issues/488#issuecomment-1793372143).

**Comment by Amazon90** [comment]
> The issue was mentioned in #488. The solution is [here](https://github.com/SideStore/SideStore/issues/488#issuecomment-1793372143).

Great!Thank you so much.
