### ISSUE TITLE
[BUG] “AltStore will expire in 24 hours…”

### ISSUE THREAD

**Issue by cootshk** [SideStore/SideStore#559]
### Describe the bug

SideStore calls itself altstore in the 24 hours until expiry notification 

### Instructions to reproduce

1. Install SideStore
2. Wait 6 days

### What version of SideStore are you using?

0.5.2

### Other info

There are like three other dialogues that still stay altstore

All of them are in the news tag

**Comment by Spidy123222** [comment]
This was now changed thanks for the issue. Sorry for the time it took.
