### ISSUE TITLE
[BUG] SideStore not being able to refresh SideStore

### ISSUE THREAD

**Issue by Magicraptor5114** [SideStore/SideStore#560]
### Describe the bug

When i go to refresh apps on sidestore, the only app i cant refresh is sidestore. I get this error:
![image](https://github.com/SideStore/SideStore/assets/64968845/c0c1c51e-c340-413e-a430-8bebcc7ec13c)

### Instructions to reproduce

1. Install sidestore
2. Wait a week
3. Try to refresh sidestore

### What version of SideStore are you using?

0.5.4

**Comment by nextDNSconfig** [comment]
I have this bug also

Fix= Every time you want to refresh you have to re-enable WireGuard

Or install the beta, this fixed it for me

**Comment by Amazon90** [comment]
https://github.com/SideStore/SideStore/issues/558

**Comment by Spidy123222** [comment]
This was fixed
