### ISSUE TITLE
[BUG] The app could not be found.

### ISSUE THREAD

**Issue by fish12352** [SideStore/SideStore#562]
### Describe the bug

I encountered "the app could not be found" when installing with Aitstore, I used almost everything that could be used and it still won't install. The devices are iPhone14 Pro and Windows. 

### Instructions to reproduce

1.Shift+Left Click the altstore
2.Click on sidestore.ipa
3.Enter Apple ID
4.Select Sidestore.ipa
5.You can see it

### What version of SideStore are you using?

0.5.4 and latest Altstore

**Comment by junepark678** [comment]
can't repro

**Comment by allstarsshining** [comment]
同样的14pro+windows，我也遇到了这个问题“the app could not be found”

**Comment by ghost** [comment]
Are there any non-English characters in the file (folder) location, try and copying it onto the C:\

**Comment by ZoewAk1212** [comment]
修改成全英文路径成功解决了问题
