### ISSUE TITLE
[BUG] This app is invalid

### ISSUE THREAD

**Issue by Amazon90** [SideStore/SideStore#563]
### Describe the bug

https://github.com/SideStore/SideStore/assets/72290820/69253fec-e232-4fe1-8e12-30455f3d373c

### Instructions to reproduce

I downloaded GTA SA Definitive from iphonecake, but when I used sidestore sideloading, I got the error "This app is invalid".

### What version of SideStore are you using?

v0.5.4

**Comment by junepark678** [comment]
piracy not allowed here
