### ISSUE TITLE
[BUG] Can't add external source

### ISSUE THREAD

**Issue by KusakabeShi** [SideStore/SideStore#564]
### Describe the bug

```
The data couldn't be read because it isn't in the correct format.
E downloadURL:String or downloadURLs [[Platform:URL]] key required.
```

### Instructions to reproduce

1. add this source to sidestore which works on altstore: https://alt.getutm.app/
2. get the error above

### What version of SideStore are you using?

0.5.4

### Other info

iOS 17.2.1

**Comment by sirbaconyt** [comment]
same thing

**Comment by timescam** [comment]
#314 

> No, there's a lot of AltStore additions we haven't cherry picked

**Comment by Spidy123222** [comment]
Should be resolved

**Comment by roberthawdon** [comment]
Still having the same issue on 0.5.8
