### ISSUE TITLE
[BUG] Sidestore cannot be refreshed unless "Sync via WiFi" is check on iTunes.

### ISSUE THREAD

**Issue by KaitoMaster** [SideStore/SideStore#565]
https://github.com/SideStore/SideStore/assets/154982584/78cd7f2f-4585-40ac-ac36-b8422c66626e

 Describe the bug

It doesn't work on iOS 17.2.1

### Instructions to reproduce

Turn on WireGuard Sidestore tunnel
Open Sidestore
Hit Refresh
A text box appears saying Unable to connect to the device, make sure Wireguard is enabled and you're connected to WiFI.
I wait 10 seconds and pressed refresh multiple times, it reappears.

UPDATE: IT WAS FIXED BY ENABLING "Sync device via Wi-Fi" on iTunes Windows/Mac Finder. It was working on 17.2 beta 2 without that checked. It stopped working on 17.2.1 when it isn't checked so "Sync this device with Wi-Fi" has to be checked in the iTunes/Finder.

Again it worked when the Wi-Fi sync is enabled, so this is an issue.

### What version of SideStore are you using?

0.5.4

**Comment by falk4243** [comment]
If you hit the "Refresh" button often enough (sometimes 10x), it works eventually. The exact error message is "Unable to connect to the device, make sure Wireguard is enabled and you're connected to WiFi".

**Comment by KaitoMaster** [comment]
Thanks, I tired hitting it even 50 times and still doesn't work. WireGuard tunnel is enabled... can you guys fix this?

**Comment by Amazon90** [comment]
https://github.com/SideStore/SideStore/issues/558

Maybe you have encountered the issue I encountered before.

**Comment by falk4243** [comment]
Would probably be helpful to confirm the exact error message so the devs know what we're dealing with herr. If it's the one I listed above, killing the app via the task switcher, restarting and spamming the refresh button also helped in my case.

**Comment by KaitoMaster** [comment]
I tried that and it didn't work the link above didn't help must
 Be an outdated anisette server or something

**Comment by Amazon90** [comment]
> I tried that and it didn't work the link above didn't help must
> 
>  Be an outdated anisette server or something

I think you need to give a detailed error code for the developer team to analyze this issue.

**Comment by KaitoMaster** [comment]
Fixed. I did the required steps Amazon90 linked, and it is confirmed working. It was also side loaded with passcode on and it worked. Maybe passcode was off when installing it or something....

**Comment by Nevotic** [comment]
Was trying to figure out why it wasn't working for me. After turning on Wifi sync, it worked instantly. Very weird.

**Comment by WesleyBryie** [comment]
> Was trying to figure out why it wasn't working for me. After turning on Wifi sync, it worked instantly. Very weird.

It is weird, especially considering that SideStore should not be communicating with the computer when refreshing.
