### ISSUE TITLE
WARNING: Outdated anisette server

### ISSUE THREAD

**Issue by Amazon90** [SideStore/SideStore#567]
### Describe the bug

WARNING: Outdated anisette server
We've detected you are using an older anisette server. Using this server has a higher likelihood of locking your account and causing other issues. Are you sure you want to continue?
![IMG_0532](https://github.com/SideStore/SideStore/assets/72290820/93f50954-0e1e-49db-8ebc-05169ee40a1d)

### Instructions to reproduce

1.open wireguard 
2.open sidestore 

### What version of SideStore are you using?

v0.5.4

**Comment by nextDNSconfig** [comment]
Fix: use these settings. https://ani.sidestore.io/ ![image](https://github.com/SideStore/SideStore/assets/86489640/582b047d-da28-40c3-9156-a15fbf5023bd)

**Comment by Amazon90** [comment]
> Fix: use these settings. https://ani.sidestore.io/ ![image](https://github.com/SideStore/SideStore/assets/86489640/582b047d-da28-40c3-9156-a15fbf5023bd)

The issue is still there after setting up.

**Comment by nextDNSconfig** [comment]
You have to re-enable the VPN and restart the SideStore app

**Comment by Amazon90** [comment]
> You have to re-enable the VPN and restart the SideStore app

Yes, restarted and still the same issue.

**Comment by nextDNSconfig** [comment]
Oké clear, for further information please check this discord server: https://discord.gg/sidestore-949183273383395328

**Comment by Amazon90** [comment]
> Oké clear, for further information please check this discord server: https://discord.gg/sidestore-949183273383395328

This is an invitation link to join the discord server, and I didn't find a way to solve the problem.

**Comment by Amazon90** [comment]
Here’s a step by step guide on how to host your own anisette server
1. Open <https://github.com/dadoum/anisette-v3-server> or <https://github.com/SideStore/omnisette-server> in your browser
2. Sign up/sign in to GitHub.com
3. Click/tap fork to copy the repository to your account
4. Go to render.com and sign in/create an account
5. Press new and make a web service
6. Connect your GitHub account if it isn’t already
7. Select connect on the repo you forked
8. Fill out the form: Set the region to whatever’s closest to you and the name to anything you’d like. The rest can be left as is
9. Scroll down to the bottom and select **Create Web Service**
10. Wait for render to finish building. It may take a moment
11. Once it’s done building, copy the url of your anisette server. It’ll be near the top of the page, highlighted blue
12. Open sidestore, go to the settings tab, and then press **Advanced Settings**
13. Paste the url into **Anisette URL** and disable **Use Preferred Servers.**

**Comment by Spidy123222** [comment]
The server they have likely is being blocked in this case if nothing is working while the server is working for others.

**Comment by samuelc02** [comment]
> I also had the same error, but I solved it for the following reasons.
> 
> 
> 
> 1. Open SideStore.
> 
> 2. Connect the iPhone to Windows where altserver is installed. (iTunes must also be installed.)
> 
> 3. If you refresh or separately register your Apple ID in SideStore, you will be prompted to enter a 6-digit authentication code. Cancel everything and wait for it to be renewed.

Sorry but wdym by refresh or separately register your Apple ID in SideStore? Like sign out and sign back in?

**Comment by WesleyBryie** [comment]
# Users who are experiencing anisette issues should temporarily switch to a different server by going to the Settings App -> SideStore. Thank you for your patience.

**Comment by Steppen-wolf** [comment]
> Here’s a step by step guide on how to host your own anisette server
> 
> 1. Open https://github.com/dadoum/anisette-v3-server or https://github.com/SideStore/omnisette-server in your browser
> 2. Sign up/sign in to GitHub.com
> 3. Click/tap fork to copy the repository to your account
> 4. Go to render.com and sign in/create an account
> 5. Press new and make a web service
> 6. Connect your GitHub account if it isn’t already
> 7. Select connect on the repo you forked
> 8. Fill out the form: Set the region to whatever’s closest to you and the name to anything you’d like. The rest can be left as is
> 9. Scroll down to the bottom and select **Create Web Service**
> 10. Wait for render to finish building. It may take a moment
> 11. Once it’s done building, copy the url of your anisette server. It’ll be near the top of the page, highlighted blue
> 12. Open sidestore, go to the settings tab, and then press **Advanced Settings**
> 13. Paste the url into **Anisette URL** and disable **Use Preferred Servers.**





This worked for me. Thanks!

**Comment by WesleyBryie** [comment]
Please don't use omnisette, as it has a risk of locking your account. Anisette V3 Server does not have this issue.

**Comment by Steppen-wolf** [comment]
Txs 
I will change immediately!

**Comment by Rubik7357** [comment]
> Here’s a step by step guide on how to host your own anisette server
> 
> 1. Open https://github.com/dadoum/anisette-v3-server or https://github.com/SideStore/omnisette-server in your browser
> 2. Sign up/sign in to GitHub.com
> 3. Click/tap fork to copy the repository to your account
> 4. Go to render.com and sign in/create an account
> 5. Press new and make a web service
> 6. Connect your GitHub account if it isn’t already
> 7. Select connect on the repo you forked
> 8. Fill out the form: Set the region to whatever’s closest to you and the name to anything you’d like. The rest can be left as is
> 9. Scroll down to the bottom and select **Create Web Service**
> 10. Wait for render to finish building. It may take a moment
> 11. Once it’s done building, copy the url of your anisette server. It’ll be near the top of the page, highlighted blue
> 12. Open sidestore, go to the settings tab, and then press **Advanced Settings**
> 13. Paste the url into **Anisette URL** and disable **Use Preferred Servers.**

Thanks for easy description! This process literally DELETED my sidestore app's warning.

**Comment by badhabit7** [comment]
> Here’s a step by step guide on how to host your own anisette server
> 
> 1. Open https://github.com/dadoum/anisette-v3-server or https://github.com/SideStore/omnisette-server in your browser
> 2. Sign up/sign in to GitHub.com
> 3. Click/tap fork to copy the repository to your account
> 4. Go to render.com and sign in/create an account
> 5. Press new and make a web service
> 6. Connect your GitHub account if it isn’t already
> 7. Select connect on the repo you forked
> 8. Fill out the form: Set the region to whatever’s closest to you and the name to anything you’d like. The rest can be left as is
> 9. Scroll down to the bottom and select **Create Web Service**
> 10. Wait for render to finish building. It may take a moment
> 11. Once it’s done building, copy the url of your anisette server. It’ll be near the top of the page, highlighted blue
> 12. Open sidestore, go to the settings tab, and then press **Advanced Settings**
> 13. Paste the url into **Anisette URL** and disable **Use Preferred Servers.**

Works for me thanks 😇
