### ISSUE TITLE
New browse tab like Altstore 

### ISSUE THREAD

**Issue by nextDNSconfig** [SideStore/SideStore#568]
### Describe the feature

An extra page like altstore
![IMG_1821](https://github.com/SideStore/SideStore/assets/86489640/d172f6c8-5482-4720-a010-aa5e6c9b1c97)

### Use cases

Better overview

**Comment by Spidy123222** [comment]
Yeah this requires merging new changes. Will take time. We will likely rewrite sidestore and do our own thing.
