### ISSUE TITLE
[BUG] Cannon refresh SideStore on Wi-fi

### ISSUE THREAD

**Issue by grimind-tech** [SideStore/SideStore#569]
### Describe the bug

Hi,
I’m unable to refresh SideStore without computer directly from iPhone.

Model : iPhone XS 64 GB, MT9E2CN/A
iOS version: iOS 17.3 (21D5026f)

### Instructions to reproduce

Connect to VPN with WireGuard
Open SideStore
Go to My Apps 
Refresh all apps
All third party apps are refreshed but whenever I try to refresh SideStore then this error will come
Before that I tried to sign in to the first one Apple ID, then because there is an max 3 apps restriction, I tried to sign out and sign in with other Apple ID to overcome this issue. After that I tried to also remove SideStore completely from computer and also from iPhone but it stays the same problem.

### What version of SideStore are you using?

SideStore 0.5.4

**Comment by KusakabeShi** [comment]
Install sidestore.ipa from sidestore itself with **Remove app extension** , then refresh it again will resolve this issue.
I guess there are some bug in the extension to prevent the refreshing. Anyway, **Remove app extension** fixed the issue.

**Comment by Spidy123222** [comment]
You cannot swap between account to get for 3 app limit. Whatever you installed SideStore with is what you should use in the app.
