### ISSUE TITLE
[FEATURE REQUEST] Make these value configureable instead of hard coded

### ISSUE THREAD

**Issue by KusakabeShi** [SideStore/SideStore#570]
### Describe the feature

I want an option to customize the IPs and private keys for both sidestore side and wireguard side.

Add 3 new items in the Sidestore settings:
|  Name                                   | Name2     | Default Value                                                                         |
|--------------------------------|-----|------------------------------------------------------------------|
| em_proxy server_privatekey  | Sidestore Wireguard Key    |  UI+sCDEketXDq6vOAidLe0mYiHogMh1TA2zg3CqlxEA=   |
| em_proxy client_publickey    | Device Wireguard  Key    |  ow01dGyrgRSrjln9bGb6fx0FwY5XKSVMTaoKQ2GDSkM=   |
| em_proxy server_ip               |   Sidestore IP    | 10.0.7.1                                                                                   |

make these value customizable instead of hardcoded in em_prixy
![image](https://github.com/SideStore/SideStore/assets/73118488/46e194d7-307c-446f-a427-4fefe9776b44)
![image](https://github.com/SideStore/SideStore/assets/73118488/8a9eab65-d77a-42c2-9419-5cd48b4f650a)

### Use cases

1. For security reason
6. For personal VPN. I want to use sidestore and connect to my home VPN simultaneously. I can setup multiple peers in same wireguard config. One peer is sidestore and another peer is my home VPN. But with this setup, the private key in my iOS side is published in the internet which is very insecure.

So that I want an option to customize the private keys for the VPN connection, and both sidestore side and wireguard side are custimizeable.

By the way, em_proxy client_ip seems like automatic detected in the em_proxy, so we doesn't need to make it configureable.

![image](https://github.com/jkcoxson/em_proxy/assets/73118488/e678c9fa-1454-4f0e-aaa0-682b3b770bd5)

**Comment by yur1xpp** [comment]
> I want to use sidestore and connect to my home VPN simultaneously.

Could this work for commercial VPN too, say Mullvad+SideStore?

**Comment by KusakabeShi** [comment]
> > I want to use sidestore and connect to my home VPN simultaneously.
> 
> Could this work for commercial VPN too, say Mullvad+SideStore?

No, iOS only allows one VPN only at same time. But wireguard allows us create multiple peers in one VPN config as long as the subnet of each peer are not overlapped. 

The sidestore uses 10.7.0.10/24 and the VPN at my home uses 192.168.15.0/24 which is not overlapped, so that I can connect them simultaneously.

It would be better if we can customize the subnet and the wireguard keys for the sidestore.

**Comment by yur1xpp** [comment]
That's very interesting. I've been looking way to use sidestore with mullvad. By different subnet, does it have to be two different class (10.x.x.x vs 192.168.x.x)? 10.7.0.1/32 (sidestore) and 10.143.x.x wouldn't work?

**Comment by KusakabeShi** [comment]
> mullvad

iOS can’t run multiple vpn simultaneously. Multiple server in single config, it’s a wireguard feature. You have to export the wireguard key from mullvad and combine with sidestore config to a single config than we can use it. But this requires sidestore has the function to customize wireguard keys and subnet prefix.

**Comment by yur1xpp** [comment]
> You have to export the wireguard key from mullvad and combine with sidestore config to a single config than we can use it.

I believe most commercial vpn including Mullvad can do this (native WireGuard).

I search the issue, seems like this might be similar case with https://github.com/SideStore/SideStore/issues/475

**Comment by Spidy123222** [comment]
> 6. For personal VPN. I want to use sidestore and connect to my home VPN simultaneously. I can setup multiple peers in same wireguard config. One peer is sidestore and another peer is my home VPN. But with this setup, the private key in my iOS side is published in the internet which is very insecure.
> 
So this message is in tandem with point 1. Because your trying to using it in tandem with your on WireGuard vpn. You're using the key for ours on your server. 

> So that I want an option to customize the private keys for the VPN connection, and both sidestore side and wireguard side are custimizeable.


I do feel we could add an option to use a custom key in sidestore app. You already have half the work done by using WireGuard key on your server. If we have ability to change the key then you can use your own which does make sense.

> By the way, em_proxy client_ip seems like automatic detected in the em_proxy, so we doesn't need to make it configureable.
> 

From what it seems like to me is that you just need a custom key option only than changing the ip. Sidestore shouldn't need to interact with your network unnecessarily via the real vpn tunnel you have unless we implement a remote vpn thing for some reason. In that case we could give option to interact with the specified ip for whatever that is if we ever do that.

**Comment by KusakabeShi** [comment]
> So this message is in tandem with point 1. Because your trying to using it in tandem with your on WireGuard vpn. You're using the key for ours on your server.
Exactly!

The scenario of changeable IP is the IP used by em_proxy( 10.0.7.1 ) may conflict with the real VPN.
In most case it won't be an issue but make it changeable to give us a chance to avoid the conflict would be better.

And all this three value are hardcoded in `https://github.com/jkcoxson/em_proxy/blob/master/src/lib.rs` currently, make it configurable to users is reasonable I think.

**Comment by Spidy123222** [comment]
> > So this message is in tandem with point 1. Because your trying to using it in tandem with your on WireGuard vpn. You're using the key for ours on your server.
> 
> 
> 
> Exactly!
> 
> 
> 
> The scenario of changeable IP is the IP used by em_proxy( 10.0.7.1 ) may conflict with the real VPN.
> 
> In most case it won't be an issue but make it changeable to give us a chance to avoid the conflict would be better.
> 
> 
> 
> And all this three value are hardcoded in `https://github.com/jkcoxson/em_proxy/blob/master/src/lib.rs` currently, make it configurable to users is reasonable I think.
> 
> 
> 
> server_privatekey: https://github.com/jkcoxson/em_proxy/blob/c8a280e54c93be130b7087c41eba83b1c15f96be/src/lib.rs#L25  
> 
> client_publickey: https://github.com/jkcoxson/em_proxy/blob/c8a280e54c93be130b7087c41eba83b1c15f96be/src/lib.rs#L26  
> 
> server_ip: https://github.com/jkcoxson/em_proxy/blob/c8a280e54c93be130b7087c41eba83b1c15f96be/src/lib.rs#L329

I'm sure we can do something like this, might be a thing for SideStore rewrite (next) if current code is causing trouble. Probably not something soon however. Will see how it goes. I kinda want to try this out with a real vpn with the loopback.

**Comment by yodaluca23** [comment]
> > I want to use sidestore and connect to my home VPN simultaneously.
> 
> 
> 
> Could this work for commercial VPN too, say Mullvad+SideStore?

Idk if Mullvad supports it, but SurfShark has IKEv2 VPN support which Apple considers a "Personal" VPN instead of a "Device" VPN no idea why, but anyways... And iOS lets you have a Device and Personal VPN both on and connected at the same time. I've been doing it with the SideStore WireGuard VPN and SurfShark IKEv2 VPN. I think windscribe supports IKEv2, too...
