### ISSUE TITLE
[BUG] unable to refresh

### ISSUE THREAD

**Issue by crceck123** [SideStore/SideStore#571]
### Describe the bug

Cannot refresh and install apps on ios 15.8
iphone 7

https://github.com/SideStore/SideStore/assets/100026828/f1f7e4de-0061-4b27-9cd1-29809161e323
anisette server is up

### Instructions to reproduce

idk

### What version of SideStore are you using?

0.5.4

**Comment by KusakabeShi** [comment]
Try to run jitterbug https://github.com/osy/Jitterbug/releases/tag/v1.3.1 which should trigger “Trust this computer” on iOS, than install sidestore from pc again may fix this issue.

**Comment by crceck123** [comment]
I installed sidestore using altstore and created pairing file via jitbugpair and it's working now.
![D730234B-2220-44A3-BA18-8006F470B237](https://github.com/SideStore/SideStore/assets/100026828/3b2fe303-1b42-49f1-b843-dda3f6ec2fac)
![DEA0E9EC-8306-4B25-B982-A368EC366E0E](https://github.com/SideStore/SideStore/assets/100026828/4d05057a-734f-4325-8dbc-98f3121be7d0)
![B5D64C80-643A-4389-8976-4A56111D64CF](https://github.com/SideStore/SideStore/assets/100026828/5c36db29-f103-4249-a1e9-07b2403f5d38)
