### ISSUE TITLE
ALTPairingFile expiring after restart

### ISSUE THREAD

**Issue by mrbonkerz** [SideStore/SideStore#572]
### Describe the bug

I used JitterbugPair on macOS to create the "ALTPairingFile.mobiledevicepairing". Then, I moved the file to the document folder of SideStore. 

The process of refreshing and installing the app was successful while using WireGuard and having Wi-Fi enabled. 

However, the next day, the refresh stopped working and I had to generate a new "ALTPairingFile.mobiledevicepairing" to get it working again.

### Instructions to reproduce

1) generate ALTPairingFile.mobiledevicepairing using jitterbugpair
2) place file in documents folder of SideStore 
3) refresh app using wideguard connection 
4) wait for the next day and repeat step 4

### What version of SideStore are you using?

0.5.4

**Comment by Spidy123222** [comment]
> ### Describe the bug
> 
> I used JitterbugPair on macOS to create the "ALTPairingFile.mobiledevicepairing". Then, I moved the file to the document folder of SideStore. 
> 
> 
> 
> The process of refreshing and installing the app was successful while using WireGuard and having Wi-Fi enabled. 
> 
> 
> 
> However, the next day, the refresh stopped working and I had to generate a new "ALTPairingFile.mobiledevicepairing" to get it working again.
> 
> ### Instructions to reproduce
> 
> 1) generate ALTPairingFile.mobiledevicepairing using jitterbugpair
> 
> 2) place file in documents folder of SideStore 
> 
> 3) refresh app using wideguard connection 
> 
> 4) wait for the next day and repeat step 4
> 
> ### What version of SideStore are you using?
> 
> 0.5.4
> 
> ### Other info
> 
> _No response_

We have zero control over Apple expiring a pairing record. It's usually the Apple devices that do it. Happens commonly when updating iOS.

**Comment by mrbonkerz** [comment]
> > ### Describe the bug
> > 
> > I used JitterbugPair on macOS to create the "ALTPairingFile.mobiledevicepairing". Then, I moved the file to the document folder of SideStore. 
> > 
> > 
> > 
> > The process of refreshing and installing the app was successful while using WireGuard and having Wi-Fi enabled. 
> > 
> > 
> > 
> > However, the next day, the refresh stopped working and I had to generate a new "ALTPairingFile.mobiledevicepairing" to get it working again.
> > 
> > ### Instructions to reproduce
> > 
> > 1) generate ALTPairingFile.mobiledevicepairing using jitterbugpair
> > 
> > 2) place file in documents folder of SideStore 
> > 
> > 3) refresh app using wideguard connection 
> > 
> > 4) wait for the next day and repeat step 4
> > 
> > ### What version of SideStore are you using?
> > 
> > 0.5.4
> > 
> > ### Other info
> > 
> > _No response_
> 
> We have zero control over Apple expiring a pairing record. It's usually the Apple devices that do it. Happens commonly when updating iOS.

So the idea of SideStore using WireGuard to refresh SideStore and Apps without the use of a computer is not reliable? Will this be improved in future builds?

**Comment by mrbonkerz** [comment]
> > ### Describe the bug
> > I used JitterbugPair on macOS to create the "ALTPairingFile.mobiledevicepairing". Then, I moved the file to the document folder of SideStore.
> > The process of refreshing and installing the app was successful while using WireGuard and having Wi-Fi enabled.
> > However, the next day, the refresh stopped working and I had to generate a new "ALTPairingFile.mobiledevicepairing" to get it working again.
> > ### Instructions to reproduce
> > 
> > 1. generate ALTPairingFile.mobiledevicepairing using jitterbugpair
> > 2. place file in documents folder of SideStore
> > 3. refresh app using wideguard connection
> > 4. wait for the next day and repeat step 4
> > 
> > ### What version of SideStore are you using?
> > 0.5.4
> > ### Other info
> > _No response_
> 
> We have zero control over Apple expiring a pairing record. It's usually the Apple devices that do it. Happens commonly when updating iOS.

So the idea of SideStore using WireGuard VPN to refresh SideStore and Apps without the use of a computer is not reliable? Will this be improved in future builds?
