### ISSUE TITLE
[FEATURE REQUEST] Auto Enable JIT

### ISSUE THREAD

**Issue by Francisc0422** [SideStore/SideStore#573]
### Describe the feature

Something I would like to see is the option to use the shortcuts app in iOS to add a function to open an app with JIT enabled.

### Use cases

In emulators or other application such as the Pojav Launcher, they need JIT to function correctly and it would make it’s just a slight bit easier to enable it.

**Comment by Spidy123222** [comment]
Duplicate of https://github.com/SideStore/SideStore/issues/166
