### ISSUE TITLE
[BUG] Failed to Log In An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.). Please try again. If the issue persists, report it on GitHub Issues!

### ISSUE THREAD

**Issue by amrpyt** [SideStore/SideStore#574]
### Describe the bug

**im Sure that my apple email and password are correct, i try to turn off the vpn, connect to the pc, nothing work. and i got this error:**

Failed to Log In
An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.).
Please try again. If the issue persists, report it on GitHub Issues!

![IMG_0902](https://github.com/SideStore/SideStore/assets/77219001/cfebb5fd-3bfb-4daa-9c3b-8c7cb087b5cb)

### What version of SideStore are you using?

0.5.4

**Comment by 3xMMike** [comment]
I have the same problem, I don't know what to do about it

**Comment by Spidy123222** [comment]
This is related to not able to connect to server. This was a while ago and hasn't been an issue anymore.
