### ISSUE TITLE
[BUG] my sidestore isn’t sidestoring

### ISSUE THREAD

**Issue by MusicBoiJBoy** [SideStore/SideStore#575]
### Describe the bug

I dont know why but my sidestore isn’t refreshing or downloading anything onto my phone even when I play with the wifi and wiregaurd. Idk what to do anymore

The operation couldn’t be completed. An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (The request timed out.). Please try again. If the issue persists, report it on GitHub Issues!

### Instructions to reproduce

Just press the download button or the refresh button.

### What version of SideStore are you using?

SideStore 0.5.5-nightly.2023.11.28.1+dae813d

**Comment by MusicBoiJBoy** [comment]
(Update)

nvm i fixed my problem lol

**Comment by mukeshydv** [comment]
@MusicBoiJBoy Can you add how did you fix it? I'm also getting same error
