### ISSUE TITLE
Cant select pair file[BUG] 

### ISSUE THREAD

**Issue by crceck123** [SideStore/SideStore#578]
### Describe the bug

Clicking on pair file in sidestore does nothing.
installed with scarlet

https://github.com/SideStore/SideStore/assets/100026828/b1ceb8bb-7886-429f-bb14-a66dccf6428f

### Instructions to reproduce

Install sidestore with scarlet and use old pair file

### What version of SideStore are you using?

0.54 nightly(works on stable too)

### Other info

Iphone 7 ios 15.8

**Comment by Montivillon** [comment]
If you updated your iOS version, you have to redo the jitterbug pair process again, i also faced this issue and that was because I sideloaded with an enterprise certificate which failed to activate so you can sideload the ipa with sideloadly to allow it to work properly

**Comment by arandomidiot2** [comment]
You first have to go to files location/of/the/pairing/file and click on the file (In my opinion Id share the file to an app like ES file Explorer) and it will say you received a file that ends with .mobliepairingfile move the .mobilepairingfile to somewhere on my iPhone and go back into SideStore and open it. Hope this helps!

**Comment by abdcef** [comment]
I am facing the same issue. Sidestore spa signed and installed but cannot select the pair file.

**Comment by Spidy123222** [comment]
You can't use scarlet for installing SideStore. Please use altserver or sideserver.
