### ISSUE TITLE
Error while refresh SideStore 

### ISSUE THREAD

**Issue by wesamdev** [SideStore/SideStore#579]
### Describe the bug

.

### Instructions to reproduce

,

### What version of SideStore are you using?

0.5.4

### Other info

The operation couldn’t be completed. Unable to install the app: Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.D9B839WZ25.com.SideStore.SideStore" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.D9B839WZ25.com.SideStore.SideStore, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:error:], SourceFileLine=869, NSUnderlyingError=0xdb8e08d10 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.D9B839WZ25.AltWidget that does not match required prefix of com.D9B839WZ25.com.SideStore.SideStore. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.SideStore.SideStore.D9B839WZ25.AltWidget that does not match required prefix of com.D9B839WZ25.com.SideStore.SideStore. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1382, NSLocalizedFailureReason=Mismatched bundle IDs.}}}

**Comment by Spidy123222** [comment]
Have to use sideserver/altserver or sideloader (this is not sideloady) not anything else
