### ISSUE TITLE
Can’t refresh since iOS 17.4 

### ISSUE THREAD

**Issue by tonysprenk** [SideStore/SideStore#580]
### Describe the bug

After updating to 17.4 I get an error when refreshing: “unable to connect to the device”

### Instructions to reproduce

Refresh any app. Inhale downloaded a new von config but this hasn’t helped. 

### What version of SideStore are you using?

0.5.4

**Comment by BoogieHasFun** [comment]
cannot reproduce (yes i am running iOS 17.4 beta), maybe you can reset the pairing file?

**Comment by Futuremappermydud** [comment]
I can reproduce this. Been going crazy haha

**Comment by tonysprenk** [comment]
After reinstalling SideStore everything is working fine. Thanks!
