### ISSUE TITLE
Cant sideload ipa

### ISSUE THREAD

**Issue by FrigidTM** [SideStore/SideStore#581]
### Describe the bug

When trying to sideload gta San Andreas ipa I get this message: 
![IMG_0533](https://github.com/SideStore/SideStore/assets/152236476/98738f13-3593-456e-9b34-465b3f04bcaa)

### Instructions to reproduce

Look up gta San Andreas ipa on your iPhone, install from first link, after installing go into SideStore, my apps, click the plus, choose the ipa from files saved on device, wait for it to load, get error message that file can’t be saved to folder

### What version of SideStore are you using?

0.5.4

### Other info

Running iOS 17.1.1 on iPhone SE

**Comment by WesleyBryie** [comment]
You are attempting to sideload a pirated game. The SideStore team will not provide support to those using pirated apps and games.
