### ISSUE TITLE
Cant side load gta San Andreas from iosgods

### ISSUE THREAD

**Issue by FrigidTM** [SideStore/SideStore#582]
### Describe the bug

Gta San Andreas ipa finishes all the way installing and then says an unexpected error occurred with error code 0 and uninstalls

### Instructions to reproduce

Download free iosgodsapp for jailed then search gta San Andreas  and click the 3 dots then install via altstore 

### What version of SideStore are you using?

0.5.4

**Comment by SternXD** [comment]
We do not support pirated applications.
