### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Salzman-Software** [SideStore/SideStore#583]
### Describe the bug

App reports that vpn is not connected when all 3 apps are installed and the development team is full.

### Instructions to reproduce

Install SideStore on numerous devices until it reports that the development team has reached the limit of devices you can install the app on. Then, install two more apps on a device. They won’t be able to be refreshed as SideStore erroneously reports that the vpn is not connected.

### What version of SideStore are you using?

0.5.4

### Other info

Workaround: delete one of the apps to be able to refresh the other two.

**Comment by junepark678** [comment]
set a title, read the FAQ, this isn't a bug
