### ISSUE TITLE
[BUG] Refresh All Apps action in shortcuts is broken.

### ISSUE THREAD

**Issue by elisha1099** [SideStore/SideStore#584]
### Describe the bug

Just as the title says, trying to use the “refresh all apps” command in shortcuts throws an error.

### Instructions to reproduce

 Make new shortcut, add “refresh all apps” action, run shortcut.

### What version of SideStore are you using?

0.5.4

### Other info

The request was denied by service delegate (SBMainWorkspace) for reason: Security ("Unable to launch
com.8F6D567X63.com.ri-
leytestut.AltStore because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user").
The request to open
"com.8F6D567X63.com.rileytestut.Alt-
Store" failed.

**Comment by seankzw** [comment]
Facing the same issue here in Version 0.5.4

**Comment by shaunkoh** [comment]
Same issue here in 0.5.6

**Comment by shaunkoh** [comment]
Found a fix: just needed to delete the AltStore app from my device.

**Comment by junepark678** [comment]
Don't have both SideStore and AltStore installed on one device, it's unnecessary and a waste :)
