### ISSUE TITLE
[BUG] issue make sure wire guard is connected with your wifi

### ISSUE THREAD

**Issue by Botokk** [SideStore/SideStore#585]
### Describe the bug

I keep trying to add a file but it won’t let me and it says that and I have wireguard configured with SideStore but it keeps saying that.

### Instructions to reproduce

I don’t know what you have to do to fix it

### What version of SideStore are you using?

Just downloaded it today 2/8/24

**Comment by WesleyBryie** [comment]
Try regenerating your pairing file using directions at [the wiki](https://wiki.sidestore.io).

**Comment by WesleyBryie** [comment]
@Botokk Just checking in, was your issue solved?

**Comment by WesleyBryie** [comment]
@Botokk Is this issue solved for you?
