### ISSUE TITLE
[BUG] Unable to connect to device, make sure Wireguard is enabled and you’re connected to wifi

### ISSUE THREAD

**Issue by Procopio28** [SideStore/SideStore#586]
### Describe the bug

I followed the steps in sidestore.io and when i try to refresh the sidestore app, it says Unable to connect to device, make sure Wireguard is enabled and you’re connected to wifi. No matter how many times I turned on and off sidestore vpn it still says the same thing. Pls fix it.

### Instructions to reproduce

I installed sideserver on my windows computer, I also installed iTunes and iCloud, I then plugged in my iPad and installed sidestore using sideserver, I tried to install it again but it did not work, it still says the same thing.

### What version of SideStore are you using?

Sidestore 0.5.4

### Other info

I am using a 5th generation iPad running ios 16.2

**Comment by shylock-wu** [comment]
Me too.It's so bad

**Comment by Kishenpatel99** [comment]
Same issue

**Comment by Kishenpatel99** [comment]
Tried to reinstall twice but no resolution

**Comment by jimmysofat6864** [comment]
I also have the same thing. Sometimes if I open side store then press refresh, watch it fail, then go to wireguard and disable and reenable it then go into sidestore and refresh, it starts working. 

![IMG_1832](https://github.com/SideStore/SideStore/assets/69532417/df317c1d-a401-47eb-a529-0edefe9675d7)
![IMG_1833](https://github.com/SideStore/SideStore/assets/69532417/a1714246-f0e9-47a6-a7b5-cad22033f13d)

**Comment by JusXty9** [comment]
guys I found a workaround in youtube, basically you need to this steps and works for me.
1. disable wifi and enable cellular data
2. try it again if it is still have errors, disable the cellular data and enable wifi again
3. then adding the .ipa file there should be no errors anymore

**Comment by 98khongmin** [comment]
Still doesn't work for me :/

**Comment by Nominel** [comment]
Rebooting my phone seems to fix the issue, but it comes back the next time I need to refresh

**Comment by Procopio28** [comment]
It started working. I don’t know how, I just reinstalled it
