### ISSUE TITLE
[BUG] After four days of software installation, it crashes and cannot be accessed

### ISSUE THREAD

**Issue by ledouer** [SideStore/SideStore#587]
### Describe the bug

After four days of sidestore software installation, it crashes and cannot be accessed.

My iOS system version：17.3.1，IPhome：14Promax and 12Promax

### Instructions to reproduce

My iOS system version：17.3.1，IPhome：14Promax and 12Promax
The sidestore cannot access the software from the the fourth day. The software that has been signed and installed can run normally, but the sidestore cannot run. You can only reinstall the software and renew the signed software.

### What version of SideStore are you using?

0.5.4

**Comment by WesleyBryie** [comment]
# Follow the after-install directions on the wiki.

[The Wiki](https://wiki.sidestore.io) has after-install directions that include refreshing SideStore after setting your pairing file.

Please reinstall SideStore (following the instructions from the wiki), and do those after-install tasks, and your problem will be solved.

**Comment by WesleyBryie** [comment]
@ledouer Just checking in, was your issue solved?

**Comment by ledouer** [comment]
Reinstalling SideStore has been two weeks without any issues.

**Comment by WesleyBryie** [comment]
Great to hear!

**Comment by junepark678** [comment]
refresh SideStore right after install
