### ISSUE TITLE
[BUG] crashes days after install

### ISSUE THREAD

**Issue by zac-massey** [SideStore/SideStore#588]
### Describe the bug

I installed SideStore, the next day it wouldn’t open and would crash. I had reinstalled it and now it’s working but not sure when it’ll crash again. 

### Instructions to reproduce

Install, wait a few darts, crash, reinstall

### What version of SideStore are you using?

0.5.4

**Comment by WesleyBryie** [comment]
This is a known issue and is caused by not refreshing SideStore after install, as mentioned in the wiki. Please reinstall SideStore: using AltServer, following the wiki, and having refreshed SideStore after install.

**Comment by WesleyBryie** [comment]
Please let us know if you have any further issues. For now I'm closing this as this is a well known issue.
