### ISSUE TITLE
Not Work IOS 17.3.1 IPhone 12

### ISSUE THREAD

**Issue by enokseth** [SideStore/SideStore#591]
### Describe the bug

Mot work in IOS 17.3.1 due to unknow developper disk img! VPN and in-app minimuxer not Connect to fine ports with WireGuard.

### Instructions to reproduce

iPhone 12 IOS 17.3.1

### What version of SideStore are you using?

0.5.4

**Comment by WesleyBryie** [comment]
Are you using SideServer to install? If so, use AltServer.

Are you trying to use JIT? If so, it is not supported by SideStore on iOS 17.

Are you using WiFi? If not, connect to WiFi and try again. SideStore requires WiFi for WireGuard to work correctly.

**Comment by enokseth** [comment]
> Are you using SideServer to install? If so, use AltServer.
> 
> Are you trying to use JIT? If so, it is not supported by SideStore on iOS 17.
> 
> Are you using WiFi? If not, connect to WiFi and try again. SideStore requires WiFi for WireGuard to work correctly.

Yes I'm using SideStore with SideServer on iOS 17.3.1, JItterdubbug is Down on IOS 17 ? ^^
have going to try with AltServer Thanks !

**Comment by WesleyBryie** [comment]
Jitterbugpair is not down for iOS 17, all it does in our case is generate a file which is successful.

Wesley Bryie

***@***.***
***@***.***

https://wesbryie.com/
________________________________

**Comment by enokseth** [comment]
Yes ok, i see ;)

**Comment by WesleyBryie** [comment]
@enokseth Just checking in, was your issue solved?

**Comment by enokseth** [comment]
> @enokseth Just checking in, was your issue solved?

yess issue solved tank's ! ^^

laptop water damaged last week I fix it sorry for the times.
