### ISSUE TITLE
[BUG] Sideloaded app can’t refresh because it’s trying to duplicate app ID’s which puts it over the limit. 

### ISSUE THREAD

**Issue by BurgPeterson** [SideStore/SideStore#592]
### Describe the bug

I’m trying to update a sideloaded app where I’ve added the source directly to Sidestore and downloaded it. Upon trying to refresh the app, it fails because the app itself needs 7 App IDs but it’s trying to install 7 new ones as opposed to using the 7 IDs it’s already utilising. 
![IMG_2732](https://github.com/SideStore/SideStore/assets/140428268/1f92bb2d-d276-4bdb-a3ce-3e9a5b480d02)
![IMG_2731](https://github.com/SideStore/SideStore/assets/140428268/189c7add-4dc7-45ff-a749-dd5588bb9383)
![IMG_2736](https://github.com/SideStore/SideStore/assets/140428268/323784ab-df8c-4247-a7a5-bafb7750c551)

### Instructions to reproduce

Just try to refresh the sideloaded app. 

### What version of SideStore are you using?

0.5.4

**Comment by WesleyBryie** [comment]
This seems like an issue with the Apollo variant you are using.

**Comment by BurgPeterson** [comment]
Ok thanks. I’ll manually sideload it after this expires. Haven’t had this issue before this variant

**Comment by enokseth** [comment]
@BurgPeterson 
if I am not mistaken, 
when reinstalling sidestore or alstore on IOS 17.3.1, 
I had the sidestord with a new reset of the parent certificates linked to my icloud account, delete sidestore or alstore and reinstall it wirh server refresh new 10 app ID.

**Comment by WesleyBryie** [comment]
@BurgPeterson Just checking in, do you still think the issue was caused by SideStore or was it the variant?

**Comment by junepark678** [comment]
gone stale, can't repro
