### ISSUE TITLE
[BUG] Apps added via SideStore Repo not detecting new updates 

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#593]
### Describe the bug

I have an app added with a source so it it supposed to be able to check for updates and prompt me to install them but for some reason, the updates only show once I start refreshing an app and not when an update is available. 

### Instructions to reproduce

1. Install older version of an application that supports an altstore repo ex. uYouEnhanced or SideStore 
2. Attempt to refresh an app (doesn't matter which one) 
3. A prompt for the new version of the application will be displayed

![IMG_1827](https://github.com/SideStore/SideStore/assets/69532417/42e20ec2-7f4f-4dcc-a1f6-ca277bc7a893)
![IMG_1829](https://github.com/SideStore/SideStore/assets/69532417/32980164-a7d7-4c5f-86a4-c09880adc063)
![IMG_1828](https://github.com/SideStore/SideStore/assets/69532417/4b9ba7a1-d1ba-4154-b66c-a4c555eb3530)

### What version of SideStore are you using?

0.5.4

**Comment by WesleyBryie** [comment]
Did you install the app using the source, or did you use an IPA?

**Comment by jimmysofat6864** [comment]
> Did you install the app using the source, or did you use an IPA?

@WesleyBryie I installed the app while using the source. Sometimes if I am lucky the update prompt is visible and I can press update and the app will update as normal but most of the time it is usually not there and refreshing other apps will cause it to show up. But once I do that, the SideStore app crashes upon refreshing any app so when I open the app it's gone.

**Comment by Spidy123222** [comment]
This is a bug that we are aware of and will consider. Working on the project is hard because of the altstore codebase so it could take a bit.

**Comment by junepark678** [comment]
can't repro
