### ISSUE TITLE
[New features] Hey guys, I found an app that is easier to use than SideStore

### ISSUE THREAD

**Issue by panderman** [SideStore/SideStore#595]
### Describe the bug

none

### Instructions to reproduce

none

### What version of SideStore are you using?

none

### Other info

Hey guys.

I found an app called NB Pro that is easier to use than SideStore. It can install and update applications without a computer. It is free, does not require Wi-Fi, and can downgrade App Store applications, simply perfect.

The official website is: nbtool8.com.

**Comment by WesleyBryie** [comment]
# Please do not download anything from this website.
- The website is not using HTTPS (its 2024, this should be required by now)
- The website has baseless claims ("first free ipa sign" where is this claim coming from, there has had to have been ipa signers that were free prior to June 2023...)
- This is the first I'm hearing of this, and its a false issue which is an advertisement.

I will be reporting as spam. Again, please do not download anything from this site! Please just use SideStore, or even AltStore.

**Comment by panderman** [comment]
Hey guys, I have been using this app for more than 2 months and have not found any problems. It is a powerful app. The main thing is that you can downgrade the app. This is very convenient. I have always used SideStore before, but I always have to connect to the computer. Updating out-of-date apps bothers me, and until I discovered this app, I have no problem with SideStore, which is also great.

**Comment by Spidy123222** [comment]
> Hey guys, I have been using this app for more than 2 months and have not found any problems. It is a powerful app. The main thing is that you can downgrade the app. This is very convenient. I have always used SideStore before, but I always have to connect to the computer. Updating out-of-date apps bothers me, and until I discovered this app, I have no problem with SideStore, which is also great.

Why do you always have to connect to computer? Also downgrades are easy on sidestore too. Just grab an old ipa of sidestore or other apps and sideload it in app.
