### ISSUE TITLE
JIT SOULTION[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Montivillon** [SideStore/SideStore#596]
### Describe the feature

On my ios 17 device, it creates a message in Sidestore saying that it needs to find a solution. There is a new system of Developer disk images on iOS 17 which is probably why Jit enablers dont work. Luckily, altstore just uses a solution called pymobiledevice3 https://faq.altstore.io/how-to-use-altstore/altjit which helped JIT to work which is what I want to add in Sidestore since im trying to use an app that needs to use Sidestore.

### Use cases

This could be useful for Livecontainer which Ill use when the feature is added

### Alternatives

None

**Comment by WesleyBryie** [comment]
The SideStore team is already well aware of `pymobiledevice3`, and how it will help get JIT to work.

JIT support will come eventually, we don't know when that is. All is asked is that you are patient.

**Comment by gh0sti** [comment]
https://github.com/nythepegasus/SideJITServer

**Comment by WesleyBryie** [comment]
A quick copypasta I made for the above link:

### JIT for iOS and iPadOS 17.0 and higher is currently in the works.

Due to a change implemented by Apple, the current stable methods of enabling JIT for apps on iOS/iPadOS 17 or higher is no longer possible. However, there is a method currently being worked on. You can find the code here: https://github.com/nythepegasus/SideJITServer.

Instructions:

- Ensure you have a recent version of Python 3 installed.
- Install venv and prepare its environment by running `python3 -m venv venv`
    - Note: Any `python3` commands can be substituted with `python` if you are sure it is Python 3.
- Activate venv
    - Mac/linux: `. ./venv/bin/activate`
    - Windows:  `.\venv\Scripts\Activate.ps1` (PowerShell) or `.\venv\Scripts\Activate.bat` (CMD)
- Install SideJITServer by running `pip3 install SideJITServer`
    - You can run `SideJITServer --help` to ensure you can run the program.
- Enjoy!

**Comment by Montivillon** [comment]
Thanks ima close this

**Comment by Montivillon** [comment]
It works but I LiveContainer needs SideStore to already have JIT instead of SideStore just saying that they need a solution because we already have one.

**Comment by WesleyBryie** [comment]
I don't understand what you are asking here. Could you clarify?

**Comment by Montivillon** [comment]
LiveContainer needs to work using SideStore and since SideJITServer already worked for me, I want to see if there is a fix to iOS 17 JIT problems

![IMG_0115](https://github.com/SideStore/SideStore/assets/156731526/c7705d4d-4c3e-4c93-90e3-60b63638c98c)

**Comment by WesleyBryie** [comment]
Right now I believe it is not in the teams interest to include SideJITServer in the current SideStore app due to its complex setup and instability in its current state.

**Comment by Montivillon** [comment]
It’s not that you really need to add it but when SideJITServer enabled JIT for SideStore, SideStore will have the ability to enable JIT through the app if SideStore will have the VPN enabled for SideStore and if not enabled, I want SideStore to say that you need SideJITServer to enable JIT first or put error message

**Comment by WesleyBryie** [comment]
I very well could be wrong here, but I'm pretty sure apps that have JIT enabled, cannot just enable JIT in other apps just because they have JIT.

**Comment by Montivillon** [comment]
I guess that would be very true. I guess you don’t need to have that, at least just change the JIT message to instead use SideJITServer. After that I’ll close the issue

**Comment by WesleyBryie** [comment]
I will get the rest of the team's opinion, and either I will follow up, or they will follow up here.

**Comment by Montivillon** [comment]
Ok I’ll wait here.

**Comment by Montivillon** [comment]
Yes. I will wait here

**Comment by Spidy123222** [comment]
Sidejitserver integration allows to enable jit on ios17+
