### ISSUE TITLE
[BUG] App crashes on startup

### ISSUE THREAD

**Issue by sirlupusdev** [SideStore/SideStore#597]
### Describe the bug

I reinstalled the app yesterday (and refreshed once per instructions). Everything seemed to work perfectly fine after that (including refreshing the apps multiple times to verify). 
However, when starting SideStore now, it crashes almost instantly. All possible reasons given in the FAQs don‘t seem to be applicable here. 
Could this be related to having SideStore installed on multiple devices with the same Apple ID and the two installations overriding their developer certificate? One installation seems to be working fine. However. I‘m not sure which one I refreshed first.

### Instructions to reproduce

The instructions depend on whether the second installation is related or not. I am not sure but I‘ll post those instructions regardless:

1. Install both apps on the device 
2. Refresh one of the installations per instructions
3. Refresh the other app for the first time

### What version of SideStore are you using?

0.5.4

### Other info

This issue was opened after checking the README and also uses that information. I also posted this on the Discord a few hours ago.

**Comment by heysylvester** [comment]
I'm experiencing this issue on 17.4 and it persists on 17.4.1.

**Comment by Spidy123222** [comment]
The instructions specifically ask to refresh SideStore not "Other app". A success refresh should have the icon do the download loop and SideStore closing the app beforehand.

![image](https://github.com/SideStore/SideStore/assets/64176728/6b503196-87b8-47e9-94f7-e2afbb5d4152)

**Comment by sirlupusdev** [comment]
That is indeed what I did - and SideStore worked fine on my first device afterwards.

**Comment by Spidy123222** [comment]
> That is indeed what I did - and SideStore worked fine on my first device afterwards.

SideStore/Altstore doesn't support having multiple devices on one account using it for sideloading atm.

**Comment by sirlupusdev** [comment]
Alright, thank you.
