### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by thedevwhodoescybersecutiy** [SideStore/SideStore#598]
### Describe the bug

i am in the sidestore app when i try to install an app and put my apple id details its stuck on the loading cog matter what i do its still stuck please help

### Instructions to reproduce

make it load

### What version of SideStore are you using?

0.5.4

### Other info

i am on a 17.2 iphone 12 mini

**Comment by junepark678** [comment]
should be fixed, set a title next time
