### ISSUE TITLE
[BUG] jitterbugpair.exe does absoulutely nothing.

### ISSUE THREAD

**Issue by IamBobble** [SideStore/SideStore#599]
### Describe the bug

I open powershell and do the pairing iDevice steps and get no device found.
What is this step even for?

### Instructions to reproduce

Extract Jitterbugpair.zip and make sure your device is still connected to the computer.
Open your device to its home screen. Once done, go into File Explorer and navigate to the folder where jitterbugpair.exe is located.
In the Navigation/Address bar where the folder location is, click an empty spot and type powershell and hit enter.
It should open a blue colored window called PowerShell. From there, type ./jitterbugpair.exe in the powershell window and press enter.

### What version of SideStore are you using?

latest

**Comment by Kuvimello** [comment]
Try opening the exe file as an administrator
That worked for me

**Comment by sadCTNBEH** [comment]
Turn on the passcode, connect your iPhone to your PC, launch jitterbugpair.exe, click “trust” on the iPhone. If it doesn't work the first time, try running jitterbugpair.exe again

**Comment by arandomidiot2** [comment]
Be sure that the passcode is on the the iPhone is UNLOCKED and run the jitterbugpair.exe as administrator

**Comment by santhosh-D-subramani** [comment]
same problem here, how did you fix it? 

```
C:\Users\Admin\Downloads\jitterbugpair-win64> ./jitterbugpair.exe
No device found.
```

i tried it multiple times, it worked fine in iOS 17.1. but Currently, I'm on iOS 17.3

**Comment by mhamzas** [comment]
Same issue with 17.5.1 - running with sudo (admin access) on mac and iPhone is unlocked!

sudo ./jitterbugpair
Password:
No device found.

**Comment by polymo1** [comment]
Both of you please try different cables

**Comment by polymo1** [comment]
Great to hear

**Comment by santhosh-D-subramani** [comment]
i noticed there are no device poping up in device manager, as i usually use wifi to sync my phone.
i guess the culprit is douwan software i used.
i reinstalled the os , its working now

**Comment by kael131** [comment]
I'm getting a successful report from jitterbugpair that it's written a file, yet no file is output. Really can't make heads or tails of it. 
Using jitterbugpair 1.3.1, iOS 17.5.1 macOS 14.5
Provided the phone is unlocked and at the home screen, I see something like: 
`SUCCESS: wrote to 00008030-00112XXXXXXXXXXX.mobiledevicepairing`
but no file. Terminal asks for and has been granted access to write to the same folder where jitterbugpair is located.

**Comment by polymo1** [comment]
Check your homedir
Thank you,

Wesley Bryie
Project Developer at SideStore

**Comment by polymo1** [comment]
Whoops github doesn't send update emails for edits...

**Comment by iRazvan2745** [comment]
im having the same issue, i tried another port, another cable iphone is unlocked, ran as administrator did basicallly everything

trying on an iphone 15 plus

**Comment by Cebahh** [comment]
> Both of you please try different cables

Worked for me!

**Comment by gdnnpc** [comment]
for me it says the device isnt paired with the host
