### ISSUE TITLE
[BUG] 2FA prompt not triggered

### ISSUE THREAD

**Issue by Moulick** [SideStore/SideStore#605]
### Describe the bug

2FA prompt is not triggered. After inputting username/password in the app, the 6 digit code is not being triggered. I have tried with the default `SideStore` and `Macley DE` anisette servers but no dice. 

### Instructions to reproduce

1. Install sidestore following https://sidestore.io/
2. Open sidestore
3. Goto `My Apps`
4. Click the ➕  and select ipa
5. Input username/password
6. Asks for 6 digit code, but this code is not received on any device

### What version of SideStore are you using?

SideStore 0.5.4

### Other info

Also I have a paid Apple developer account if that helps :)

**Comment by evilzinc** [comment]
Manual workaround:

Settings > [your name] > Password & Security OR Sign-in & Security > Two-Factor Authentication.
Tap on Get Verification Code. Note the 6 digit code.

Go back to SideStore > Settings > Sign in again. Input the 6 digit code when it asks for the code. 

You are successful when there is no error shown.

(Check your VPN, if using, is connected)
 Tap + in SideStore and select ipa and it should proceed as usual.

**Comment by Moulick** [comment]
@evilzinc Thanks, this workaround works!

**Comment by Pengwius** [comment]
Hi, I use security keys and I don't have option to get 6 digit code

**Comment by f1shy-dev** [comment]
Not sure if sidestore supports security keys as of now...

**Comment by junepark678** [comment]
SideStore will not support security keys in the foreseeable future as reversing Apple APIs is hard

**Comment by kaoneko** [comment]
I removed my physical security keys from my Apple account to be able to log in to SideStore using the workaround provided by @evilzinc, then re-added them. SideStore stays logged in and keeps working.

Maybe the [list of requirements](https://docs.sidestore.io/docs/getting-started/prerequisites/) should mention:

> **&middot; An Apple ID _not_ protected by physical security keys (can be re-added after login though)** 

Or something like that.

**Comment by dark2git** [comment]
> Hi, I use security keys and I don't have option to get 6 digit code

same here

**Comment by nazar123756** [comment]
> > > I removed my physical security keys from my Apple account to be able to log in to SideStore using the workaround provided by @evilzinc, then re-added them. SideStore stays logged in and keeps working.
> > > Maybe the [list of requirements](https://docs.sidestore.io/docs/getting-started/prerequisites/) should mention:
> > > > **· An Apple ID _not_ protected by physical security keys (can be re-added after login though)**
> > > 
> > > 
> > > Or something like that.
> > 
> > 
> > i do not have security keys (
> 
> Try signing into your iCloud account online It’s gonna ask for verification code and just use that code https://www.icloud.com/

Says that the code is incorr

**Comment by pipix92** [comment]
https://docs.sidestore.io/docs/troubleshooting/#verification-code-not-received-when-signing-in-with-apple-id
