### ISSUE TITLE
[BUG] Update to 0.5.6 not showing up

### ISSUE THREAD

**Issue by deennyy** [SideStore/SideStore#611]
### Describe the bug

I noticed that an update came out a few days ago, so I wanted to update, but no such update is showing up in SideStore, I’ve refreshed the app several times.

### Instructions to reproduce

Open SideStore app
Look for update
App reports “No updates available”

### What version of SideStore are you using?

0.5.4

**Comment by jimmysofat6864** [comment]
Same issue here. I don't know if it's similar to https://github.com/SideStore/SideStore/issues/593 as I've never seen the update show up but when I have sources for other apps, it will show up randomly. Not sure if manually installing the updated iPA file in Sidestore would work.

**Comment by deennyy** [comment]
Manually installing the IPA worked fine for me
