### ISSUE TITLE
[BUG] I accidentally deleted my Sidestore Widget and i can't find it now.

### ISSUE THREAD

**Issue by lcpdguy** [SideStore/SideStore#614]
### Describe the bug

![20240501040248](https://github.com/SideStore/SideStore/assets/40915849/62f96b75-f07e-4475-a240-23b4449c1b0d)
There should be a widget on the screen,but now it gone, i can't even search it.

### Instructions to reproduce

I hope i can put the widget on the screen again.

### What version of SideStore are you using?

0.56

**Comment by Spidy123222** [comment]
You might have to install the SideStore ipa on SideStore itself then just keep extensions and it should come back.

**Comment by noideastowork** [comment]
> You might have to install the SideStore ipa on SideStore itself then just keep extensions and it should come back.

Thanks! This solution worked for me! 

However I had to repeat installation few times for some reason to get widget back. I thought it might be helpful to share.
