### ISSUE TITLE
[BUG] Installed by Sideserver, but requiring pairing file

### ISSUE THREAD

**Issue by name1000000** [SideStore/SideStore#615]
### Describe the bug

I've been using side server since the first couple weeks of launch and never had this issue, just accidentally let sidestore expire and had to refresh sidestore using sideserver on OSX.  Sideserver says it's up to date. ver 1.0.6.

After installing sidestore using sideserver, sidestore opens normally.  Once I refresh sidestore using wireguard VPN, sidestore says it requires the pairing file to do anything.   

### Instructions to reproduce

Install Sidestore using Sideserver on OSX
Open Sidestore
Enable Wireguard VPN tunnel
Refresh Sidestore
Open Sidestore
Sidestore asks for pairing file

### What version of SideStore are you using?

0.5.6

**Comment by dayo05** [comment]
I have same problem.
When I install sidestore via sideserver with MacOS, it works as it.
The problem starts when after sidestore refreshes.
Before refresh application itself, I can still install such applications like uYou+ or refresh other applications. But when I refresh sidestore then it stops working and also crashes when I call refresh from shortcut

**Comment by WesleyBryie** [comment]
# SideServer is currently in a broken state.

Please do not use SideServer. Instead, follow the instructions to use AltServer at [the docs](https://docs.sidestore.io/) or the [website.](https://sidestore.io)
