### ISSUE TITLE
SideStore using up half of my battery life during sleep?

### ISSUE THREAD

**Issue by seulgiism** [SideStore/SideStore#617]
### Describe the bug

Since installing SideStore the battery drains almost half my phone. I think it is due to the Background Refresh not working properly and getting stuck in a loop

![IMG_8523](https://github.com/SideStore/SideStore/assets/103776158/6ba30f10-3a00-4a3b-a687-45f5d02b9aaf)

### Instructions to reproduce

I have a siri automation that puts my battery mode on Low Power Mode at 50%.

i also just put my phone next to me during sleep on a full charge long before it reaches low power mode.

### What version of SideStore are you using?

0.5.6

**Comment by Spidy123222** [comment]
This can happen if the device is locked. Possibly a check got removed some how. To mitigate this use a shortcut on a schedule and disable background refresh.

**Comment by slrgt** [comment]
Can you list the steps on how to make a shortcut for this?

**Comment by Steve2811** [comment]
I'd want to create a shortcut to run max once a day with device unlocked and WiFi connected but I don't know how to do it... :( thanks!

**Comment by slrgt** [comment]
This is what i use and in the shortcuts app i set an automation to run it at 4am so it happens when im sleeping. In the automation setup make it so it “runs immediately” https://routinehub.co/shortcut/21145/

**Comment by Steve2811** [comment]
Thank you very much! Unfortunately is offline: This website routinehub.co/shortcut/21145/ is currently offline. Cloudflare's Always Online™ shows a snapshot of this web page from the Internet Archive's Wayback Machine. To check for the live version, click Refresh.
