### ISSUE TITLE
[BUG] Could not confirm application on iOS 17.4.1 After several attempts it kinda worked.

### ISSUE THREAD

**Issue by andrfgs** [SideStore/SideStore#619]
### Describe the bug

After sideloading SideStore and Approving the developer app, it's impossible to confirm the app due to the error:
```
Unable to Verify App

An internet connection is required to verify the trust of the developer ... 
Until confirmation, this app will remain unavailable.
```

(Note: I had to translate the error message to english, so the actual message may be slightly different)

### Instructions to reproduce

1. Using AltStore server on a computer and holding shift, click on the tray icon
2. Select sideload .ipa
3. Select SideStore.ipa
4. Go to *Settings > General > VPN & Device Management* on the device
5. Approve the App

When trying to also confirm the app, nothing happens

### What version of SideStore are you using?

0.5.6

### Other info

Found this URL that might be related https://forums.developer.apple.com/forums/thread/732495

Do we now all require Macs with XCode and an Apple Developer account in order to use this app?

**Comment by andrfgs** [comment]
I kinda managed to overcome this by:
1. Disabling and re enabling the developer mode
2. Restarting the device, as prompted
3. Remove the application
4. Turn off Focus Mode
5. Sideload the .ipa file again
6. I tried to rerun jitterbugpair but it no longer is generating the pair file. But since I still had an older from my previous attempts, no big problem.
7. Again go to *Settings > General > VPN & Device Management* and confirm the developer
8. The app started working

Im not really sure what is going on here, if it's an iOS bug or an Apple verification bug or whatever.

**Comment by junepark678** [comment]
can't reproduce
