### ISSUE TITLE
[BUG] VPN no longer works, so this has essentially become just like AltStore

### ISSUE THREAD

**Issue by andrfgs** [SideStore/SideStore#620]
### Describe the bug

Despite having Wireguard enabled and having set up SideStore's VPN, when trying to refresh or sideload more .ipa's, the app fails with:
```
Unable to connect to the device, make sure Wireguard is enabled and you're connected to WiFi
```

I am connected to wifi.

### Instructions to reproduce

1. Open SideStore app
2. Either click the + button or Refresh All

### What version of SideStore are you using?

0.5.6

**Comment by PlateProp** [comment]
Running into the same issue

**Comment by singlekeycap** [comment]
Had the same issue, what fixed it was creating a new pairing file with jitterbugpair, then deleting the old one off SideStore and loading the new one. Hope it works for you!

**Comment by nighto** [comment]
This has happened with me for a bit but restarting not only Wireguard but also the iPhone itself fixed the issue.

**Comment by triplehoon** [comment]
I changed sidestore pair file (after hit trust this device before generating pairfile. This could be the issue, it seems the file is different with and without trust this file.) 
After that it is not working.
But as nighto metioned, I restarted iphone, and it works.

**Comment by fabri160122** [comment]
How can I solve this problem?

**Comment by arandomidiot2** [comment]
Yeah the SideStore vpn broke so you have to reinstall SideStore using Altstore

**Comment by SAJI25-CR** [comment]
Removing widget and the app from homescreen did it for me. I am in 0.5.6 tho

**Comment by rakannabale** [comment]
I have this trick

**Comment by rakannabale** [comment]
https://github.com/user-attachments/assets/c2297eb1-fa1c-477a-9714-cf6a343b2411

**Comment by rakannabale** [comment]
i have this trick

https://github.com/user-attachments/assets/4f10aafb-35f7-4526-a83c-875e554c8768

**Comment by HermiG** [comment]
This is still an issue, whether I use WireGuard or StosVPN.

People need to saying the fix is to reset the pairing file - that doesn't fix anything, it just gets you another week where the VPN refresh still won't work. With this bug Sidestore is just a tethered install that pretends to be untethered.
