### ISSUE TITLE
Show count of extensions when installing an app 

### ISSUE THREAD

**Issue by Vrajs16** [SideStore/SideStore#622]
### Describe the feature

When installing an app, I want to be able to see the count of extensions that will be installed in the popup message. The logic is over [here](https://github.com/SideStore/SideStore/blob/50a85be872db0cec9a91e6e42941231dbbbd94f2/AltStore/My%20Apps/MyAppsViewController.swift#L968C10-L968C29).

 Right now it is impossible to tell how many extensions will be installed.

### Use cases

Seeing if I can fit the amount of extensions in the 10 app ids.

### Alternatives

N/A

**Comment by ordzy** [comment]
bump
