### ISSUE TITLE
Crash every time I refresh an app

### ISSUE THREAD

**Issue by darthmooguy** [SideStore/SideStore#623]
### Describe the bug

The app seems to crash on every refresh. Which makes it annoying to refresh all 3 apps, I can’t do them all at once because it crashes after refreshing one app. I have to refresh them all individually. The apps do seem to be refreshed correctly, but SideStore shouldn’t crash.

https://github.com/SideStore/SideStore/assets/10374678/bf52ab03-9237-4dd6-9309-8b39388273ab

### Instructions to reproduce

1. Open SideStore 
2. Navigate to the my apps tab
3. Refresh all (or any) apps
4. Once it’s almost done, crash

### What version of SideStore are you using?

0.5.6

### Other info

iOS 17.4.1
iPhone 14

**Comment by WesleyBryie** [comment]
Did you install SideStore using AltServer, and did you refresh SideStore immediately after installing it?

**Comment by darthmooguy** [comment]
Yes, and yes! The two apps I have sideloaded were already previously installed using AltStore though, maybe that causes some unhandled state or something.

**Comment by WesleyBryie** [comment]
It shouldn't cause issues. My suggestion, if viable since data will be lost, is to reinstall said apps using SideStore.

You are able to refresh SideStore, right?

**Comment by darthmooguy** [comment]
Yup, refreshing SideStore works as expected (see attached video)

https://github.com/SideStore/SideStore/assets/10374678/4236f401-73b6-4d3c-a450-44cfd51c8b0c

I did try to uninstall Apollo and reinstall it fresh from SideStore, however I still get the crash. (Both during the first install and a refresh attempt afterwards)

**Comment by darthmooguy** [comment]
Reinstalling the SideStore ipa from SideStore seems to have fixed the issue! (If it matters, I reinstalled while removing the app extensions to free up some app ids)

**Comment by Harishwarrior** [comment]
> Reinstalling the SideStore ipa from SideStore seems to have fixed the issue! (If it matters, I reinstalled while removing the app extensions to free up some app ids)

You are genius!!. Must be the issue with the extensions. After reinstalling without the extensions for SideStore fixed the issue. Thanks!!

**Comment by Harishwarrior** [comment]
> Reinstalling the SideStore ipa from SideStore seems to have fixed the issue! (If it matters, I reinstalled while removing the app extensions to free up some app ids)

Can confirm this fixed my issue!! :) Thank you so much

**Comment by junepark678** [comment]
fixed
