### ISSUE TITLE
[BUG] I can’t deactivate Spotify

### ISSUE THREAD

**Issue by KHng0284** [SideStore/SideStore#624]
### Describe the bug

The bug’s error code was minimuxer.MinimuxerError error 0; the message was The operation couldn’t be completed. Unable to install the app: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.O5tkBJ/extracted/Payload/App.app : 0xe8008016 (The executable was signed with invalid entitlements.)

### Instructions to reproduce

Step 1: Install Spotify .ipa from whoeevee
Step 2: Deactivate the application

### What version of SideStore are you using?

0.5.6

### Other info

This only happens to the Spotify ipa. Any other ipas can be activated or deactivated normally.

**Comment by Awlexegrecki** [comment]
I have the same error. The app was from the SpotC source, which is no longer available. This may have something to do with the problem.

**Comment by WesleyBryie** [comment]
Install spotify officially through the app store. Anything else is considered piracy, which we will not provide support for.
