### ISSUE TITLE
[BUG] Latest version not available via repo

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#627]
### Describe the bug

In the sources tab, I have an older version of SideStore installed but for some reason the update to 0.5.6 isn't showing up. When will the latest update be pushed to the repo source apps.sidestore.io so it will be available for update? 

### Instructions to reproduce

Open the app and see that there is no update available. 

### What version of SideStore are you using?

0.5.4

**Comment by junepark678** [comment]
fixed
