### ISSUE TITLE
[BUG] App deactivation not working

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#631]
### Describe the bug

I am trying to deactivate an app but for some reason I get the following error message. 

`The operation couldn’t be completed. Unable to install the app: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.KmUT7R/extracted/Payload/App.app : 0xe8008016 (The executable was signed with invalid entitlements.)`

### Instructions to reproduce

1. Install an app
2. Attempt to deactivate it 
3. Error 

You can also refer to the video I have below. 

https://github.com/SideStore/SideStore/assets/69532417/47642504-90af-4a91-bbca-b620b5c9b785

### What version of SideStore are you using?

0.5.6

**Comment by junepark678** [comment]
Pirated apps don't seem to work well with SideStore. This isn't a SideStore bug but rather an iPA issue that exists the scope of our project.
