### ISSUE TITLE
[BUG] Cannot deactivate Spotify

### ISSUE THREAD

**Issue by Skiliflippo** [SideStore/SideStore#632]
### Describe the bug

Reopening this issue because the one that existed got removed for no clear reason and without a solution. 

The bug’s error code is: 

"Unable to install the app: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.RIKIJA/extracted/Payload/App.app : 0xe8008016 (The executable was signed with invalid entitlements.)

### Instructions to reproduce

Step 1: Install Spotify .ipa from whoeevee or SpotilifeC
Step 2: Deactivate the application

### What version of SideStore are you using?

0.5.4

### Other info

This only happens to the Spotify ipa. Any other ipas can be activated or deactivated normally.

**Comment by jimmysofat6864** [comment]
I have same issue with Spotify but I didn't check if it's spotify exclusive or not. 

https://github.com/SideStore/SideStore/issues/631

**Comment by WesleyBryie** [comment]
SideStore tends not to work with pirated applications. This is not a SideStore issue, but rather an issue with the distributed IPAs. Maybe don't pirate ;).
