### ISSUE TITLE
[BUG] "App contains extensions" prompt not visible on apps downloaded from an AltStore source

### ISSUE THREAD

**Issue by jimmysofat6864** [SideStore/SideStore#637]
### Describe the bug

I am essentially describing what is going on in https://github.com/altstoreio/AltStore/issues/929. 

In any case, when I download an app from an AltStore source, a popup is supposed to show up telling me that I can remove app extensions so I don't go over the 10 App ID limit. But when I go to download an app from an AltStore repo, the popup doesn't show up and I get errors about being over my App ID limit when I have 2 App ID's remaining. 

### Instructions to reproduce

1. Get close to your App ID limit but not over. Ex have 2 app ids remaining. 
2. Attempt to install an app from an AltStore source with optional app ID's that can be removed
3. App fails to install 

It's also worth noting that sideloading the iPA directly doesn't result in this issue occurring it is exclusive to apps downloaded from AltStore sources. I believe AltStore has it sorted already as the AltStore issue is marked as resolved. A photo of the error is below. 

![IMG_2089](https://github.com/SideStore/SideStore/assets/69532417/dbae56b9-9bff-47bf-abfe-ed4941eccb4d)

### What version of SideStore are you using?

0.5.6

### Other info

Should have been solved in https://github.com/altstoreio/AltStore/issues/929.

**Comment by afonsofrancof** [comment]
I also need this. The source for Apollo requires 7 App ID's when installing through a source and I only have 4 left.
Any way to remove the extensions?

**Comment by yodaluca23** [comment]
> I also need this. The source for Apollo requires 7 App ID's when installing through a source and I only have 4 left.
> Any way to remove the extensions?

Yes, download the file directly from the source and then upload it to SideStore as a loose .ipa file and it will give you the prompt

**Comment by JayceTheBased** [comment]
I'm not sure if this qualifies as a true bug but I totally agree that this would be a really nice feature to add. If you have a problem with refreshing an app, it's easy to exceed your app extension limit even though you would normally be within it, if you don't sideload the ipa manually. And there are some apps like the modded YouTube and Spotify ones that get updated frequently, so being able to use the sources for those makes things a decent bit smoother and easier.

**Comment by junepark678** [comment]
1397389f95fe47451193ecec9e5f69a8d8fe3135 should fix
