### ISSUE TITLE
Support for banned countries on developer.apple

### ISSUE THREAD

**Issue by Mysteryexe** [SideStore/SideStore#638]
### Describe the bug

Im living in iran and developer.apple website blocks iran ip, With altstore i enable VPN on both devices to change my ip and it works fine, but for sidestore when i enable wireguard my other vpn connection goes off and my iran ip becomes visible thus i cant sign anything. thanks for support

### Instructions to reproduce

requires ip of countries under apple sanctions

### What version of SideStore are you using?

0.5.6

**Comment by f1shy-dev** [comment]
One option could be making a wireguard VPN server and then adding it into the sidestore configuration to have both VPNs at once - can't see any other way this would work.

Would require some manual setup of a VPN server though...

**Comment by WesleyBryie** [comment]
> Would require some manual setup of a VPN server though...

Definitely, @Mysteryexe if you are willing, and have a VPS or paid VPN that gives wireguard configs, you should look into combining the configs and seeing if that works.

**Comment by junepark678** [comment]
As this isn't an issue with SideStore, I'm going to close this issue
