### ISSUE TITLE
[BUG] An error occurred when getting anisette datafrom a V3 server

### ISSUE THREAD

**Issue by ledouer** [SideStore/SideStore#639]
### Describe the bug

![微信图片_20240616085133](https://github.com/SideStore/SideStore/assets/55625341/5fa7928d-180f-4df1-8bc6-e07d5af99011)
I want to sign an error report
An error occurred when getting anisette datafrom a V3 server: Couldn't fetch client info. Theserver may be down (too many HTTP redirects)Please try again.lf the issue persists, report it on GitHub lssues!
How do I fix it？

### Instructions to reproduce

I want to sign an error report

### What version of SideStore are you using?

0.5.6

**Comment by reyland44** [comment]
Sadly this project is basically abandoned at this point. Way too many issues.

**Comment by Spidy123222** [comment]
> Sadly this project is basically abandoned at this point. Way too many issues.

Someone changed something in the server and is being addressed. The project isn't abandoned either, look at how recent pull requests are and how active it is. Many bugs are from being based on altstore app code and how difficult it is to go through. Currently there is still being added but some of us are currently in a rewrite which should address some of the issues.

**Comment by ledouer** [comment]
> > Sadly this project is basically abandoned at this point. Way too many issues.
> 
> Someone changed something in the server setup and is being addressed. The project isn't abandoned either, look at how recent pull requests are and how active it is. Many bugs are from being based on altstore app code and how difficult it is to go through. Currently there is still being added but some of us are currently in a rewrite which should address some of the issues.

Thankes,I change sidestore settings >> advanced settings >> Anisette server ，solve this problem。

**Comment by Gluxo** [comment]
Sadly switching anisette servers no longer resolves the problem

**Comment by moyu955** [comment]
> > > 遗憾的是，这个项目目前基本被放弃了。问题太多了。
> > 
> > 
> > 有人更改了服务器设置中的某些内容，目前正在处理中。该项目也没有被放弃，看看最近的拉取请求和它的活跃程度。许多错误都是基于 altstore 应用程序代码，而且很难解决。目前仍有一些内容正在添加，但我们中的一些人目前正在重写，这应该会解决一些问题。
> 
> 谢谢，我更改了 sidestore 设置 >> 高级设置 >> Anisette 服务器，解决了这个问题。

目前这个方法已经无法解决问题了

**Comment by junepark678** [comment]
@moyu955 please use English, as we aren't skilled outside English.

**Comment by junepark678** [comment]
Fixed by 0.5.7
