### ISSUE TITLE
[BUG] Unverified after ~24h

### ISSUE THREAD

**Issue by alany08** [SideStore/SideStore#640]
### Describe the bug

Yes, I did refresh sidestore immediately after installing. This can be furthered by one occasion where using sidestore to refresh other apps caused them to become unlaunchable. 

Sidestore and other sideloaded apps begin instantly crashing around a day after initial installation, and I have to manually sideload sidestore.ipa with an altserver. I have a paid apple developer account.

### Instructions to reproduce

Sideload sidestore using altserver
Refresh it
Sideload some other apps
Wait ~24 hours or more

Apps start crashing (unverified?)

### What version of SideStore are you using?

0.5.6

**Comment by WesleyBryie** [comment]
Is AltServer prompting you to use your paid account?

If so, try sideloading SideStore with your free account, then use SideStore's built in Paid Dev account functionality. This will show up as a separate instance, follow first install steps for that one (same pairing file should work).

**Comment by junepark678** [comment]
closing because stale
