### ISSUE TITLE
sidestore crashes when trying to sideload a big ipa

### ISSUE THREAD

**Issue by Droopyxv** [SideStore/SideStore#641]
### Describe the bug

i was trying to sideload gta and each time when it gets close to around 70% complete, side store crashes, the sideload isnt complete but an app id is taken. i can sideload other smaller ipas but each time gta fails.

### Instructions to reproduce

sideload gta san andreas ipa

### What version of SideStore are you using?

0.5.6

**Comment by WesleyBryie** [comment]
Known issue, no current fix or workaround.
