### ISSUE TITLE
[BUG] Unable to perform software updates

### ISSUE THREAD

**Issue by angeleoa** [SideStore/SideStore#642]
### Describe the bug

Failed to refresh 2 apps.
An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (too many HTTP redirects).
Please try again. If the issue persists, report it on GitHub Issues!

### Instructions to reproduce

Failed to refresh 2 apps.
An error occurred when getting anisette data from a V3 server: Couldn't fetch client info. The server may be down (too many HTTP redirects).
Please try again. If the issue persists, report it on GitHub Issues!

### What version of SideStore are you using?

0.5.6

**Comment by junepark678** [comment]
I think I was playing with the anisette server around this time, sorry for the downtime :)
