### ISSUE TITLE
[BUG] Unable to connect the device in SideStore 0.5.6 nightly version

### ISSUE THREAD

**Issue by Duy-Thanh** [SideStore/SideStore#644]
### Describe the bug

I have Wi-Fi connection, WireGuard enabled. But I still getting “Unable to connect the device”

Here is a screen recording about error:

https://github.com/SideStore/SideStore/assets/36120800/ab67f4e8-9268-4109-8443-7e0c86819157

### Instructions to reproduce

1. Connect to Wi-Fi
2. Turn on wireguard
3. Start SideStore then Try to install IPA or Refresh app
4. Error appear

### What version of SideStore are you using?

0.5.6-nightly

**Comment by h4rqq** [comment]
Just restart your device and try closing sidestore and turning on and off wireguard until it works

**Comment by h4rqq** [comment]
> I have the same issue. I am using Sidestore for the first time. I followed the steps exactly to install it, but when I clicked refresh, I got this error message. I tried uninstalling, reinstalling, and restarting the device, but it still doesn't work. Is this problem specific to version 0.5.6? I am considering trying an older version.

Seems like the new SideJIT implementation is messing some things up, try re doing your pairing file.

**Comment by Duy-Thanh** [comment]
> Just restart your device and try closing sidestore and turning on and off wireguard until it works

I have tried all of them, nothing works.

And I think I found the problem

When I running `SideJITServer --pair` on computer, pair it to conputer and use SideStore, this error happens. Only uninstall completely application then reinstall SideStore from begin worked. 

I don’t know why this happen. Maybe someone can explain that weird behavior?

**Comment by junepark678** [comment]
Too many variations. Need more specific bug reports
