### ISSUE TITLE
Unable to install an .ipa file

### ISSUE THREAD

**Issue by arandomidiot2** [SideStore/SideStore#646]
### Describe the bug

Upon downloading and trying to install [Paylod.ipa](https://mega.nz/file/xHsgQRrT#LRwYOy93gbRWGCA5csGt3oUQyIV3SW2AAmQ1Uakubrk) with side store I get the error code com.rileytestut.AltSign error 0.

### Instructions to reproduce

Download the [Payload.ipa](https://mega.nz/file/xHsgQRrT#LRwYOy93gbRWGCA5csGt3oUQyIV3SW2AAmQ1Uakubrk) and try and install it with SideStore 

### What version of SideStore are you using?

0.5.6

### Other info

Error code is; /Users/runner/Library/Developer/Xcode/DerivedData/AltStore-dunvejkuqerofjghtqolpzgexuyv/SourcePackages/checkouts/AltSign/Sources/ldid/../ldid-core/ldid.cpp(2435): _assert(): target.sputn(data, writ) == writ
The Payload.ipa installs Eternum

**Comment by junepark678** [comment]
The iPA is faulty.
