### ISSUE TITLE
[BUG] Widget is broken

### ISSUE THREAD

**Issue by Eggslegend** [SideStore/SideStore#647]
### Describe the bug

It shows Please adopt containerbackgroudUI…?
Any solutions?
Ps. I’ve downgraded from alpha to 0.5.6
![IMG_0620](https://github.com/SideStore/SideStore/assets/113283422/e64adc7b-ec30-4960-8e7e-e7933e8f0b74)
![IMG_0621](https://github.com/SideStore/SideStore/assets/113283422/b0294e01-cc83-403d-950a-955d277c0746)

### Instructions to reproduce

Upgrade to newer version and downgrade back

### What version of SideStore are you using?

0.5.6

**Comment by mahee96** [comment]
@SideStore/project-maintainers @Eggslegend @nythepegasus does anyone know when was this last working and if this widget is broken only on ios18 ?

i vaguely remember that in 0.5.6 it used to work not aure in ios 18 though but definitely was working in ios 17

**Comment by mahee96** [comment]
should be fixed in latest nightly
