### ISSUE TITLE
Unable to Deactivate SpotC++

### ISSUE THREAD

**Issue by arandomidiot2** [SideStore/SideStore#649]
### Describe the bug

Upon installing SpotC++ from the repo; [Repo](https://tiny.one/SpotC) and trying to de-activate it I get the error code; _minimuxer.MinimuxerError error 0_

### Instructions to reproduce

Download SideStore add the repo [https://tiny.one/SpotC](https://tiny.one/SpotC)
And download SpotC++ and try to De-Activate it

### What version of SideStore are you using?

0.5.6

### Other info

Error message is; _The operation couldn’t be completed. Unable to install the app: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.fE0eCq/extracted/Payload/App.app : 0xe8008016 (The executable was signed with invalid entitlements.)_

**Comment by polymo1** [comment]
SideStore tends to not work with pirated applications. Please try a different IPA.

**Comment by yodaluca23** [comment]
> SideStore tends to not work with pirated applications. Please try a different IPA.

It's not pirated applications it's tweaked applications that doesn't work well. Any vanilla app that has then had additional tweaks injected and then recompile for use in a jailed environment tend to not work and give the same error...

**Comment by polymo1** [comment]
Any application modified and distributed without the copyright-holders permission is considered piracy. Other jailed and tweaked apps not installing is an issue that could be investigated and potentially fixed, but it is not a priority.

On Jul 13, 2024 13:55, Luca LeBlanc ***@***.***> wrote:

SideStore tends to not work with pirated applications. Please try a different IPA.

It's not pirated applications it's tweaked applications that doesn't work well. Any vanilla app that has then had additional tweaks injected and then recompile for use in a jailed environment tend to not work and give the same error...
