### ISSUE TITLE
[BUG] App is invalid

### ISSUE THREAD

**Issue by Foodie947** [SideStore/SideStore#650]
### Describe the bug

I am getting an error in which sidestore states that the app is "invalid". I believe that this is due to the app that I am attempting to sideload being above 1GB. I do not know if sidestore is supposed to support uploads that large, but it says that the app is invalid. Previous version of the app that are under 1GB do not have the same issue.

### Instructions to reproduce

1: Open sidestore on your device and connect it to wireguard.
2: Attempt to upload an ipa with a filesize over 1GB.
3: App is invalid.
4: Curl up into a ball and cry.

### What version of SideStore are you using?

0.5.6

### Other info

I am on iPadOS 17.5.1, I am not using beta updates on this device.

**Comment by NsCrosu** [comment]
your ipa needs a sign, use ldid to fakesign it

**Comment by junepark678** [comment]
This is a known issue.
