### ISSUE TITLE
[BUG] Unable to Launch SideStore on iPadOS18 beta

### ISSUE THREAD

**Issue by NsCrosu** [SideStore/SideStore#653]
### Describe the bug

updated to iPadOS 18.0 developer beta 3.
unable to launch SideStore, so I used a new pairing file to pair.
but still unable to launch
![HEIF图像](https://github.com/SideStore/SideStore/assets/68761240/3f5b02bb-8a59-43d7-ba8b-a9809655bf94)

by the way, I can't see the whole internal file system when I was asked to select the pairing file for the first launch.
I launch "Files" and make them appear, and then kill SideStore process twice. Then I can see the files.

### Instructions to reproduce

update to iPadOS18.0 developer beta 3

### What version of SideStore are you using?

0.5.6

**Comment by polymo1** [comment]
Don't use Sideloadly to install SideStore. Use AltStore as detailed by the [wiki](https://wiki.sidestore.io).
