### ISSUE TITLE
[BUG] Incorrect wiki URL in "Pairing File" popup when opening SideStore app

### ISSUE THREAD

**Issue by krumble1** [SideStore/SideStore#655]
### Describe the bug

The popup is titled "Pairing File" and states:
"Select the pairing file for your device. For more information, go to https://wiki.sidestore.io/guides/getting-started/#pairing-file"

This URL should be "https://docs.sidestore.io/docs/getting-started/pairing-file" instead.

\([example screenshot](https://github.com/SideStore/SideStore/assets/12228024/7eac91c2-e474-449e-87f0-5fe53efa1549)\)

### Instructions to reproduce

1. Open the SideStore app for the first time (before a pairing file has been selected).
2. Attempt to navigate to the URL given in the popup.

### What version of SideStore are you using?

0.5.6

**Comment by Spidy123222** [comment]
Should be resolved now
