### ISSUE TITLE
[BUG] Unknown error occured

### ISSUE THREAD

**Issue by TeemSucks** [SideStore/SideStore#656]
### Describe the bug

When trying to sideload Spotube I got this error:
```/Users/runner/Library/Developer/Xcode/DerivedData/AltStore-dunvejkuqerofjghtqolpzgexuyv/SourcePackages/checkouts/AltSign/Sources/ldid/../ldid-core/ldid.cpp(1368): _assert(): end >= size - 0x10```

![IMG_0046](https://github.com/user-attachments/assets/d21746ba-7a8d-49be-bfbe-c3479f2706a6)

### Instructions to reproduce

Sideload Spotube
I didn't do anything else related...

### What version of SideStore are you using?

0.5.6

### Other info

- I had one app ID remaining
- I had 2 apps currently active (including sidestore)
- I had one disabled app
- I'm running ios 18 developer beta 3

**Comment by junepark678** [comment]
SideStore seems to not like apps that were meant to be on the app store. A fix is not planned.
