### ISSUE TITLE
[BUG] 0xe8008015 A valid provisioning file for this executable was not found 

### ISSUE THREAD

**Issue by xroneios** [SideStore/SideStore#661]
### Describe the bug

When I trying to install ipa it saying this

### Instructions to reproduce

When I trying to install ipa it says this but with sideloadly it worked

full error: [24160358]
The operation couldn’t be completed. Unable to install the app: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.zfNULE/extracted/Payload/App.app/Frameworks/UnityFramework.framework : 0xe8008015 (A valid provisioning profile for this executable was not found.)

### What version of SideStore are you using?

0.5.6

### Other info

Video here

https://github.com/user-attachments/assets/7a4402ae-7612-4828-ae1c-adf12630e49d

**Comment by junepark678** [comment]
Pirating apps doesn't work well with SideStore.
