### ISSUE TITLE
[FEATURE REQUEST] Asking for combination of SideJITServer and SideStore

### ISSUE THREAD

**Issue by fish4terrisa-MSDSM** [SideStore/SideStore#662]
### Describe the feature

It seems that SideJITServer is very simple, it just connect the device with usbmuxd and launch the app with special parameters.
As the re-signing service is much the same and SideStore succeeded in containing this service inside the app, will it be possible to also contain the SideJITServer in SideStore?(So I dont need another computer to start UTM and some other JIT-related apps)

### Use cases

Just as what I described above, get free of **any** computer dependence.

**Comment by polymo1** [comment]
If you can figure out how to integrate SideJITServer into SideStore in a way that will work without a computer, by all means submit a PR. I don't think it's possible with the current method.

**Comment by fish4terrisa-MSDSM** [comment]
Do you know Jitterbug? It seems that Jitterbug can refresh another device in the same network. As SideStore is using a wireguard vpn to connect the device itself, why we cannot simply import the jitterbug functiob into Sodestore?

**Comment by fish4terrisa-MSDSM** [comment]
As we can use SideJITServer to start an app with JIT, the SideJITSrrver depends on pymobiledevices3, and it depends on libimobiledevice, and finally all of these commands are sent to the ideivce by usbmuxd.
There is minimuxer in SideServer, which works like a usbmuxd, and takes the responsibility to refresh and install new apps. Then why it's not possible to start an app with JIT enabled? 
I'm currently trying to understand what the usbmuxd did when opening an app with JIT. Then we can make minimuxer do the same thing in SideStore.

**Comment by Infinitay** [comment]
> If you can figure out how to integrate SideJITServer into SideStore in a way that will work without a computer, by all means submit a PR. I don't think it's possible with the current method.

Not sure if this helps at all, but LiveContainer supposedly can do this, but I'm not sure exactly how. When you go to the settings there is a button that says "Setup JIT-less certificate" with a description that "JIT-less allows you to use LiveContainer without having to enable JIT. Requires SideStore.", and it ended up launching SideStore whenever you tap the button. I'm not too familiar with running apps with JIT, but could this help?

**Comment by junepark678** [comment]
closed by #674 #630

**Comment by fish4terrisa-MSDSM** [comment]
> closed by #674 #630

I think that's not the same.
It seems possible to just add the function of SideJITServer into SideStore, if we can find out what the usbmuxd did when we use the SodeJITServer to lanuch the app with JIT enabled, and make the minimuxer do the same thing.
That means, we can enable JIT **without** any kinds of PC or othet phones.
And, it seems that Jittetbug can already connect with other phone(However, for the ios 17+ devices, it can't get the Developerimage and will fail to lanuch any app.But the SideJITServer can do it, and SideStore can make the phone connect with itself), so it seems possible to make SideStore really independent with any other devices if we can add the IOS 17 support to Jitterbug and then add the function of Jitterbug into SideStore, or in a more simple way: 
Make the minimuxer do what the SideJITServer make usbmuxd did.

**Comment by junepark678** [comment]
> > closed by #674 #630
> 
> I think that's not the same. It seems possible to just add the function of SideJITServer into SideStore, if we can find out what the usbmuxd did when we use the SodeJITServer to lanuch the app with JIT enabled, and make the minimuxer do the same thing. That means, we can enable JIT **without** any kinds of PC or othet phones. And, it seems that Jittetbug can already connect with other phone(However, for the ios 17+ devices, it can't get the Developerimage and will fail to lanuch any app.But the SideJITServer can do it, and SideStore can make the phone connect with itself), so it seems possible to make SideStore really independent with any other devices if we can add the IOS 17 support to Jitterbug and then add the function of Jitterbug into SideStore, or in a more simple way: Make the minimuxer do what the SideJITServer make usbmuxd did.

why don't you do it yourself if you want it that much :)

**Comment by fish4terrisa-MSDSM** [comment]
> > > closed by #674 #630
> > 
> > 
> > I think that's not the same. It seems possible to just add the function of SideJITServer into SideStore, if we can find out what the usbmuxd did when we use the SodeJITServer to lanuch the app with JIT enabled, and make the minimuxer do the same thing. That means, we can enable JIT **without** any kinds of PC or othet phones. And, it seems that Jittetbug can already connect with other phone(However, for the ios 17+ devices, it can't get the Developerimage and will fail to lanuch any app.But the SideJITServer can do it, and SideStore can make the phone connect with itself), so it seems possible to make SideStore really independent with any other devices if we can add the IOS 17 support to Jitterbug and then add the function of Jitterbug into SideStore, or in a more simple way: Make the minimuxer do what the SideJITServer make usbmuxd did.
> 
> why don't you do it yourself if you want it that much :)

It's so hard for a people like me without deep knowledge about the Apple's ****ing protocol, and have nearly no experience with darwin, macos and ios...... 
And, Sorry for bothering.

**Comment by junepark678** [comment]
> > > > closed by #674 #630
> > > 
> > > 
> > > I think that's not the same. It seems possible to just add the function of SideJITServer into SideStore, if we can find out what the usbmuxd did when we use the SodeJITServer to lanuch the app with JIT enabled, and make the minimuxer do the same thing. That means, we can enable JIT **without** any kinds of PC or othet phones. And, it seems that Jittetbug can already connect with other phone(However, for the ios 17+ devices, it can't get the Developerimage and will fail to lanuch any app.But the SideJITServer can do it, and SideStore can make the phone connect with itself), so it seems possible to make SideStore really independent with any other devices if we can add the IOS 17 support to Jitterbug and then add the function of Jitterbug into SideStore, or in a more simple way: Make the minimuxer do what the SideJITServer make usbmuxd did.
> > 
> > 
> > why don't you do it yourself if you want it that much :)
> 
> It's so hard for a people like me without deep knowledge about the Apple's ****ing protocol, and have nearly no experience with darwin, macos and ios...... And, Sorry for bothering.

if it's so hard for you, don't you think it'd be hard for us?

**Comment by junepark678** [comment]
maybe our knowledge helps (it does)
but that doesn't make our reverse engineering job any easier :)

**Comment by fish4terrisa-MSDSM** [comment]
> maybe our knowledge helps (it does) but that doesn't make our reverse engineering job any easier :)

Ahh... I got it. Sorry for Bothering you. Maybe I'll try to dig into the code and try to find a solution fot this problem later.
