### ISSUE TITLE
[BUG] A Core Data error occurred 

### ISSUE THREAD

**Issue by bluescorpion35** [SideStore/SideStore#665]
### Describe the bug

Error _always_ comes up when I open browse: 

> The data couldn’t be written because it isn’t in the correct format 

### Instructions to reproduce

Go to browse section and the error will pop up

### What version of SideStore are you using?

0.5.6

**Comment by anoraktrend** [comment]
Also happens on 5.7

**Comment by Abateman121** [comment]
can confirm this is happening on 0.5.6 same steps as OP

**Comment by Spidy123222** [comment]
Should be solved. Not quite sure what happened but it's solved.
