### ISSUE TITLE
crashes on launch

### ISSUE THREAD

**Issue by KobuzDev** [SideStore/SideStore#667]
### Describe the bug

hello, i replace altstore by sidestore this week but after the first refresh, i can’t open the app

### Instructions to reproduce

install sidestore
refresh apps
close sidestore
try to open sidestore

### What version of SideStore are you using?

0.5.6

**Comment by KobuzDev** [comment]
https://share.icloud.com/photos/0c0-10NBD_1nIvx-iuTN6EAVA

**Comment by vanhieu1509** [comment]
Me too

**Comment by meechgalhuquot** [comment]
Ditto on 0.5.7, stops working less than a day after install

**Comment by polymo1** [comment]
Make sure you're refreshing **immediately** after install

**Comment by meechgalhuquot** [comment]
> Make sure you're refreshing **immediately** after install

Done that, and it refreshes fine

**Comment by Spidy123222** [comment]
> ### Describe the bug
> 
> hello, i replace altstore by sidestore this week but after the first refresh, i can’t open the app
> 
> ### Instructions to reproduce
> 
> install sidestore
> 
> refresh apps
> 
> close sidestore
> 
> try to open sidestore
> 
> ### What version of SideStore are you using?
> 
> 0.5.6
> 
> ### Other info
> 
> _No response_

Did you refresh the app right after install and not install other apps

**Comment by junepark678** [comment]
@Spidy123222 I think this is fine to just close
