### ISSUE TITLE
[BUG] Refreshing apps works unreliably

### ISSUE THREAD

**Issue by Aerozolic** [SideStore/SideStore#669]
### Describe the bug

After updating to 0.5.7 sometimes refreshing the apps works, sometimes only one app gets refreshed sometimes all apps. Mostly looks to be an issue with refreshing Sidestore itself. Same issue with using "Refresh all apps" shortcut. Doesn't show an error but usually doesn't work.

### Instructions to reproduce

Refresh the apps.

### What version of SideStore are you using?

0.5.7

**Comment by butfr0g** [comment]
I'm having the same problem here, it's able to refresh all apps except SideStore itself and it doesn't give any error, I tried setting the wait action to 60 but it didn't work.

**Comment by Spidy123222** [comment]
I have noticed more crashing in 0.5.7 when refreshing some apps.

**Comment by yodaluca23** [comment]
> I have noticed more crashing in 0.5.7 when refreshing some apps.

I have too, though (at least for me) it only happens when refreshing SideStore, I force quit usually fixes it...

**Comment by hurryman2212** [comment]
For the builds either 0.5.7 or 0.5.8, it just crashes while the app tries to refresh them when Refresh All Apps shortcut action is called.

**Comment by jankkm** [comment]
I think I have the same issue:
- Refresh all shortcut does not refresh SideStore but it does refresh other app (I only have 1)
- Doing refresh only for SideStore from the UI works.
- I always see an update for SideStore even though it is already installed. I suspect the two problems are related.

**Comment by yodaluca23** [comment]
> - I always see an update for SideStore even though it is already installed. I suspect the two problems are related.

https://github.com/SideStore/SideStore/issues/666

**Comment by butfr0g** [comment]
For a temporary fix I went back to version 0.5.6 and it works as always.

**Comment by mahee96** [comment]
Issue has been fixed via PR #743 PR #742 and PR #728

for context refer comments in #718 and #713
