### ISSUE TITLE
[BUG] Sidestore wil never pe aple to instal or refresh applications without WiFi and the WireGuard VPN.

### ISSUE THREAD

**Issue by ledouer** [SideStore/SideStore#680]
### Describe the bug

I want to refresh renew the app.
WireGuard is working properly. 
SideStore report errors：“ No WiFi or VPN!  You do not appear to be connected to WiFi and/or theWireGuard VPN!  Sidestore wil never pe aple to instal or refresh applications without WiFi and the WireGuard VPN。”

### Instructions to reproduce

![微信图片_20240820090100](https://github.com/user-attachments/assets/9f7f613f-5641-4e5d-8f97-3f6816eeaf3a)
![微信图片_20240820090109](https://github.com/user-attachments/assets/22cd0aab-b764-4766-8a87-f3cc21f978c0)

### What version of SideStore are you using?

0.5.7

**Comment by junepark678** [comment]
Issues are not for support :)
