### ISSUE TITLE
[BUG] SideStore makes iPhone files unusable.

### ISSUE THREAD

**Issue by ecoBlackCH** [SideStore/SideStore#685]
### Describe the bug

Once SideStore is installed and used, the stock file application, as well as other tools for viewing files, will no longer be available. The stock file app will get stuck the moment you open it.

### Instructions to reproduce

It may be just me, so I can't be sure of the reproducibility of the problem.
When using the SideStore feature. Example installation

iPhone 15
IOS 17.4.1

### What version of SideStore are you using?

latest

**Comment by polymo1** [comment]
I'm gonna say this isn't a sidestore problem since this has happened consistently on my iPad whether or not sidestore is installed.

Happened since 17.1 ish.
