### ISSUE TITLE
[BUG] constant “no wifi or VPN connected” error even in both are connected

### ISSUE THREAD

**Issue by Adoptat32** [SideStore/SideStore#687]
### Describe the bug

Simple error happens even though it shouldnt 

### Instructions to reproduce

Open SideStore and add App error will appear

### What version of SideStore are you using?

0.5.7

**Comment by leon519h** [comment]
First, try opening wireguard and turning the vpn on and off and see if that fixes it, that fixed it for me, if it doesn't fix it, remember all of the apps you have sideloaded or write them down (if you have any), try deleting sidestore and instaling it again, to make sure all of the apps work and you have no errors, sideload the same apps you had before you deleted sidestore (if you had any), it should work.

**Comment by Hudson1230** [comment]
Same problem, tried force restarting, reinstalling all apps linked to this app. What phone do you have? Let's see if there anything linked to the problem.

**Comment by Leectan** [comment]
Same issue, reinstalled all apps with same result.

**Comment by junepark678** [comment]
the GitHub issue tracker is NOT for support, join our discord for that
