### ISSUE TITLE
[BUG] Can't change anisette server or anisette server list

### ISSUE THREAD

**Issue by bluescorpion35** [SideStore/SideStore#692]
### Describe the bug

You can't change the anisette server outside of the default list, and you can't change the list as of the latest update

### Instructions to reproduce

Change the anisette server list to a custom one and it didn't work. The list is the same

### What version of SideStore are you using?

0.5.8

### Other info

Anisette list page was just changed

**Comment by TreyHam27** [comment]
Yes you can… isn’t this is?
![IMG_0781](https://github.com/user-attachments/assets/139a7058-6a02-4e92-914b-d60326f43ffe)

**Comment by bluescorpion35** [comment]
You can but it doesn't save
https://github.com/user-attachments/assets/d94ea779-1daf-4b1a-8e2a-b1dd10fccc4e

**Comment by LucifersCircle** [comment]
It’s not saving my server either… resets to default server list and selection after typing my normal url and pressing back. I don’t want to use public servers so I’ll probably downgrade for now.

**Comment by davidverified** [comment]
Solution:
1. Create a text file, open it and paste this json code inside:

```
{
    "servers": [
        {
            "name": "Davids Ani Server",
            "address": "https://YOURSERVER.com"
        }
    ]
}
```

Replace "Davids Ani Server" with your server name, you can input anything here.
Replace "https://YOURSERVER.com" with your Anisette Server URL.

Save the file as MyAnisetteServer.json

Upload the .json file to google drive, click the three dots next to it and click share. share the file with anyone who has the link and copy the link.

Look at the copied link. it should look something like this:
https://drive.google.com/file/d/**XXXXXXXXX**/view?usp=sharing
Copy the string between d/ and /view (here marked as XXXXXXXXX)

and paste that string in this link where the XXXXXXXXX is:
https://drive.google.com/uc?export=download&id=XXXXXXXXX

your link should look somethinglike this:
**https://drive.google.com/uc?export=download&id=12XrSFYTOuewIOUBAjsS-x3Gs3cyB4ZQKp**

now just paste this link in sidestore - settings - anisette servers and press refresh. **wait a few seconds** and you should now see your anisette server.
select it and go back. 

if you click on anisette servers again, you wont see your anisette server but it is selected since no other default server is selected. double check by pasting the link again, tapping refresh and see it selected.

![image](https://github.com/user-attachments/assets/7207e62a-6de4-419d-a16f-45e72421e31f)

**Comment by trandrew08** [comment]
Can confirm that you have to make your own list, and it won't show that it "saved" it but it will still use your server.

My nginx logs show it's hitting my server when I refresh the apps:

```
10.0.250.3 - - [10/Sep/2024:13:47:54 +0000] "POST /v3/get_headers HTTP/1.1" 200 210 "-" "SideStore/1 CFNetwork/1498.700.2 Darwin/23.6.0"
10.0.250.3 - - [10/Sep/2024:13:48:13 +0000] "GET /v3/client_info HTTP/1.1" 200 147 "-" "SideStore/1 CFNetwork/1498.700.2 Darwin/23.6.0"
10.0.250.3 - - [10/Sep/2024:13:48:13 +0000] "POST /v3/get_headers HTTP/1.1" 200 210 "-" "SideStore/1 CFNetwork/1498.700.2 Darwin/23.6.0"
10.0.250.3 - - [10/Sep/2024:13:48:14 +0000] "GET /v3/client_info HTTP/1.1" 200 147 "-" "SideStore/1 CFNetwork/1498.700.2 Darwin/23.6.0"
10.0.250.3 - - [10/Sep/2024:13:48:14 +0000] "POST /v3/get_headers HTTP/1.1" 200 210 "-" "SideStore/1 CFNetwork/1498.700.2 Darwin/23.6.0"
```

**Comment by LucifersCircle** [comment]
Is there any way we can have the old functionality of directly typing the url for SideStore to use? I don’t want to host another file just to tell SideStore what my server is, I believe that’s a poor design/solution.

**Comment by nythepegasus** [comment]
@LucifersCircle The idea behind the dynamic lists hosted on websites was so it wasn’t a hardcoded list inside the app anymore. I do plan to eventually add a way to just have specific servers you want to use saved inside SideStore but this was the simplest next step to help users use their own servers. If you have a better idea, a PR would be more than welcome! 

My main idea was that Github Sites/Repos are relatively easy to create or point to, I just haven’t made a template repo for it. Again, another thing we could use PRs on if you think it’s poor design, at least.

**Comment by LucifersCircle** [comment]
@nythepegasus Reading your reasoning behind it I can see now that’s likely a better option for average users, and my perspective is skewed. I have a home server and a tld. The issue being I couldn’t point to the file with my tld from github pages and I’d have to store the new json file in a httpd container when I’m already running the anisette container with its own subdomain. It’s not the biggest issue just kind of a seemingly unnecessary step for people not using a separate storage host and wanting to keep their domain consistent (not typing a GitHub/dropbox/drive link to access services on the site). Also, I’d love to try and look at the code, I likely will to see if I could create a local json it can append to the “default server list” perhaps. My wife and I are expecting a child here early November though and I haven’t had a lot of time to sit down recently so it may take me quite some time to try and get something like that working. Thanks for the reply, I’ll try what I can as soon as I get the chance!

**Comment by nythepegasus** [comment]
You could also look into CNAMEs to host the JSON on Github and still use your own custom domain without having to run an httpd instance yourself. SideStore does for its documentation and main website in fact. I'd definitely appreciate any contributions! If you ever have any questions on the code or ever wanna reach out the [Discord](https://discord.gg/sidestore-949183273383395328) is a pretty good place for that.

**Comment by LucifersCircle** [comment]
Thanks for that, I’ll look into that as a short term solution. I’ll definitely join the discord!

**Comment by SternXD** [comment]
> Yes you can… isn’t this is? ![IMG_0781](https://private-user-images.githubusercontent.com/122413341/365460904-139a7058-6a02-4e92-914b-d60326f43ffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDk4MDYsIm5iZiI6MTcyNjI0OTUwNiwicGF0aCI6Ii8xMjI0MTMzNDEvMzY1NDYwOTA0LTEzOWE3MDU4LTZhMDItNGU5Mi05MTRiLWQ2MDMyNmY0M2ZmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNzQ1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTBiZGNhMGZiY2I3ZjFhNjA5NDE0ZDYxMzM0NWJlMTI3ZmZlZTMzYWZkMzM5Nzc4YWMxYWU4ZDJhYjM0NmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l0ktd3tFEy0xW12ThUiFqh2dOGQynt2nVaBClc13xYI)

That field is only for custom lists you cannot put a server there at this time.

**Comment by 18638715723** [comment]
> Solution:
> 
> 1. Create a text file, open it and paste this json code inside:
> 
> ```
> {
>     "servers": [
>         {
>             "name": "Davids Ani Server",
>             "address": "https://YOURSERVER.com"
>         }
>     ]
> }
> ```
> 
> Replace "Davids Ani Server" with your server name, you can input anything here. Replace "https://YOURSERVER.com" with your Anisette Server URL.
> 
> Save the file as MyAnisetteServer.json
> 
> Upload the .json file to google drive, click the three dots next to it and click share. share the file with anyone who has the link and copy the link.
> 
> Look at the copied link. it should look something like this: https://drive.google.com/file/d/**XXXXXXXXX**/view?usp=sharing Copy the string between d/ and /view (here marked as XXXXXXXXX)
> 
> and paste that string in this link where the XXXXXXXXX is: https://drive.google.com/uc?export=download&id=XXXXXXXXX
> 
> your link should look somethinglike this: **https://drive.google.com/uc?export=download&id=12XrSFYTOuewIOUBAjsS-x3Gs3cyB4ZQKp**
> 
> now just paste this link in sidestore - settings - anisette servers and press refresh. **wait a few seconds** and you should now see your anisette server. select it and go back.
> 
> if you click on anisette servers again, you wont see your anisette server but it is selected since no other default server is selected. double check by pasting the link again, tapping refresh and see it selected.
> 
> I was unsure wether sidestore actually uses your anisette server so i checked my DNS Log after refreshing all apps and it sure uses your anisette server instead of the public ones.
> 
> ![image](https://private-user-images.githubusercontent.com/162368660/365741438-7207e62a-6de4-419d-a16f-45e72421e31f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMzExMjEsIm5iZiI6MTcyNjMzMDgyMSwicGF0aCI6Ii8xNjIzNjg2NjAvMzY1NzQxNDM4LTcyMDdlNjJhLTZkZTQtNDE5ZC1hMTZmLTQ1ZTcyNDIxZTMxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxNjIwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmIxYTc1NmRkMzg2YTUzNmZiZWVmMjRlZWM1ODAzNDJhMmRmYzVmMTM2ODllMDk1MDc1YjE0NTAyNzhkZjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P0dXVHqUBStKcI_FhnNiQgXyhOLr6ONPEPAAQy0VR2Y)

press refresh...No response

**Comment by trandrew08** [comment]
You can also just throw the json list on github gist and use the link with `/raw` added to the end.
