### ISSUE TITLE
[BUG] Refresh All Apps shortcut action doesn’t do anything

### ISSUE THREAD

**Issue by Aerozolic** [SideStore/SideStore#693]
### Describe the bug

Since Sidestore 0.5.7 and now 0.5.8 Refresh All Apps Shortcuts action just says that it’s done but the apps aren’t refreshed. There’s also no error and no refresh attempt logged in Sidestore. Same problem was on iOS 17.6.1 and now iOS 18 as well. Opening Sidestore and refreshing within the app works. Even though there are zero logs under refresh attempts. 

### Instructions to reproduce

Create a shortcut to connect VPN and then run Refresh All Apps and then run the shortcut. 

### What version of SideStore are you using?

0.5.8

**Comment by polymo1** [comment]
Known issue.
