### ISSUE TITLE
[BUG] I turned on vpn but sidestore says 'no wifi or vpn'

### ISSUE THREAD

**Issue by hotdog5785** [SideStore/SideStore#695]
### Describe the bug

I wait for 1 hour with vpn but sidestore still says there is no wifi or vpn
I tried refresh several times.

### Instructions to reproduce

ios 17.6.1
downloaded official vpn configuration file in sidestore homepage
use wireguard
It was working fine but suddenly stopped working one day in 0.5.4. So I updated sidestore to 0.5.8, but still it doesn't work.

### What version of SideStore are you using?

0.5.8

**Comment by xhfpsxm** [comment]
same

**Comment by kevinchristianto** [comment]
I've faced this issue lately, even I'm connected to strong wifi and connected to wireguard VPN. Any ideas?

**Comment by LucifersCircle** [comment]
I’ve had this happen after an update a couple times and the only way I could get it working was to set up SideStore again, staring with re-doing the jitterbug pair.

**Comment by hotdog5785** [comment]
When I installed 0.5.4 last year, I followed instruction from other user's blog. In that instruction, I had to change pairing file from .mobiledevicepairing to .plist... and it worked. But when I download new pairingfile with official website, and use .mobiledevicepairing file, it works! Thanks for your comment!

**Comment by Pepper1234567890** [comment]
I had this problem before, it’s not a vpn problem, it’s your pairing file, make sure you update idevicepair to latest version and recreate a pairing file from it, hope this helps!
