### ISSUE TITLE
SideStore 0.5.8 is not keeping app extensions removed upon refreshing

### ISSUE THREAD

**Issue by KieranBLK** [SideStore/SideStore#696]
### Describe the bug

When refreshing an app, SideStore will register all app extensions despite having removed them all through deselecting them or tapping “Remove All Extensions” when initially installing the app. Now I have to wait a week to install any apps. 😒
![IMG_0019](https://github.com/user-attachments/assets/e1943676-302d-48ca-97d8-215bce60b581)

### Instructions to reproduce

1. Install an app, with all or select extensions removed
2. Refresh the app after it finishes installing

SideStore should’ve registered all of that apps extensions. 

### What version of SideStore are you using?

0.5.8

**Comment by LileAuTresor** [comment]
Same for me

**Comment by ylor** [comment]
Chiming in to add that app extensions get added on both refresh and update. Thanks to the devs for your work!

**Comment by cooldude-91** [comment]
Any fix for this? I think the App ID selection pop up can be improved by adding a confirmation button.

**Comment by xhfpsxm** [comment]
same

**Comment by Ale-su** [comment]
same for me, because of this bug every time it ends up using all 10 app ids. happens both if i remove all the extensions or just select 1 that i want to keep

**Comment by bosskratos** [comment]
Same. Register all app extensions

**Comment by Nominel** [comment]
From commits looks like a fix is being worked on

**Comment by KieranBLK** [comment]
Fixed as of the latest PR. Finally! 🙏😭

**Comment by Nominel** [comment]
Yay! Thank you!

**Comment by ankerek** [comment]
Great news. Does anyone know when we can expect a release that includes this fix?

**Comment by polymo1** [comment]
> Great news. Does anyone know when we can expect a release that includes this fix?

Just use nightly, comparatively it's not that unstable.

**Comment by Nominel** [comment]
Seconded, you can download the ipa from the commit by the way.

**Comment by ankerek** [comment]
I am worried about other unexpected issues. Anyway, I installed the nightly build and tested the issue with app extensions and it's working properly now.
