### ISSUE TITLE
[BUG] Sidestore showing notification for available updates when the app is already updated

### ISSUE THREAD

**Issue by koda-git** [SideStore/SideStore#705]
### Describe the bug

Apps (including sidestore and other apps with a updatable repository) will show an update available notification for a version that is lower than the currently installed version. After going through the update process, the app will install the latest version in the repository but will have a notification showing there is an update available for it. 

### Instructions to reproduce

Installed sidestore with the instructions shown in sidestore.io, with the correct pairing file and anisette server. 
I have sideloaded a couple apps but all of them seem to show that an update is available, the description of the notification shows an older version of the app / description.  (Currently installed app is higher than the update notification version)

Speculation:  Could be because of version numbering calculation bug?

After installing the supposed "latest" update, the app is the latest version but the app still shows a notification about an update being available with an older version.

![image](https://github.com/user-attachments/assets/d37d51e5-d22c-4138-b010-f34bf3beed53)
Shows a notification for a sidestore version released on August 5th.

![image](https://github.com/user-attachments/assets/bba4a151-c101-42ba-939a-c5657144d85f)
Current sidestore version is 0.5.8 which is released on September 7th

![image](https://github.com/user-attachments/assets/0eab46c3-dbb5-417b-8355-7d4343faf2aa)
Sidestore version 0.5.8 (Currently installed) version description

### What version of SideStore are you using?

0.5.8

**Comment by polymo1** [comment]
Known bug.
