### ISSUE TITLE
[BUG] Refreshing apps always installs extensions even when remove app extensions was selected when installing

### ISSUE THREAD

**Issue by Nominel** [SideStore/SideStore#706]
### Describe the bug

If you select remove app extensions to limit the number of App IDs an app installs, when you refresh the app, SideStore will install the app extensions anyways.

### Instructions to reproduce

1. Install an app and select remove app extensions
2. Refresh app
3. SideStore will install the extensions, or the refresh will fail
4. If refresh fails due to not having enough app ids left, for example when you only have one app id left and the app installs 2 app ids, you can instead reinstall the app and select remove app ids and it will work

### What version of SideStore are you using?

0.5.8

**Comment by hellosquishies** [comment]
I constantly have the same issue, at this point I just reinstall my apps every week but that kind of misses the point of a refresh function entirely.

**Comment by Nominel** [comment]
Thankfully it looks like fixes are being worked on based on the commits

**Comment by hellosquishies** [comment]
Good to know since it's been very annoying

**Comment by Nominel** [comment]
Update: sorta fixed on the latest commits, it now just asks you if you want to keep extensions every time you refresh an app, only issue it that if you refresh all apps it only asks you once for all of them.

**Comment by justreportingissues** [comment]
Unfortunately, it's not truly fixed. Because _now_ SideStore itself will no longer refresh via automated shortcuts since it will now ask whether to keep, remove, or choose extensions EVERY SINGLE TIME a refresh is initiated. Who in the world thought that was a solution?

**Comment by Nominel** [comment]
I think you might have a different bug on your hands, try updating to 5.10 to see if the issue persists as I don’t have any popup when refreshing.

**Comment by tristanwagner** [comment]
Can confirm on 0.5.1, Sidestore is not refreshed when trying to use a script through Shortcuts because it prompts for extensions and the Shortcuts script can't bypass/handle it

**Comment by mahee96** [comment]
fixed the issues from stable build 0.5.10 in 0.6.0-nightly
