### ISSUE TITLE
Not receiving the code on SideStore

### ISSUE THREAD

**Issue by MrKhalid77** [SideStore/SideStore#707]
### Describe the bug

After i write my Apple ID and the Password and press Sign in the the 6-digit verification code i don't receive the verification message.

i tried on the AltStore and i sign out and re-sign in and i received the code from Apple!
but when i tried in SideStore it’s Not
![IMG_8831](https://github.com/user-attachments/assets/70dcb8e5-9206-471a-bd44-4e04987d3bac)

### Instructions to reproduce

like i said 👆🏻

### What version of SideStore are you using?

0.5.8 - Xcode 1420 - 14C18

**Comment by kaoneko** [comment]
Workaround: https://github.com/SideStore/SideStore/issues/605#issuecomment-2058173859

When your Apple account uses physical security keys instead of 6-digit verification codes, you'll have to remove them and re-add them later: https://github.com/SideStore/SideStore/issues/605#issuecomment-2293117271

**Comment by MrKhalid77** [comment]
> Workaround: https://github.com/SideStore/SideStore/issues/605#issuecomment-2058173859
> 
> 
> 
> When your Apple account uses physical security keys instead of 6-digit verification codes, you'll have to remove them and re-add them later: https://github.com/SideStore/SideStore/issues/605#issuecomment-2293117271

How?

**Comment by kaoneko** [comment]
Remove them as a 2FA method from your Apple account in the same screen were you once added them. But from your first post I gather you're not using physical security keys for 2FA, so it doesn't apply to you.

**Comment by junepark678** [comment]
duplicate of #605

**Comment by MrKhalid77** [comment]
So, there is no solution, the problem persists.

**Comment by MrKhalid77** [comment]
this's BAD

i will delete it

fuck it

**Comment by junepark678** [comment]
cussing us out is not the way
