### ISSUE TITLE
[BUG] ios18.0.1 when I refresh the sidestore，sidestore no opened

### ISSUE THREAD

**Issue by wangdahua576635956** [SideStore/SideStore#709]
### Describe the bug

I found that it can't be opened when I refresh the sidestore, software version 0.57-0.58 and new bate, ios18.0.1

ios18.0.1 when I refresh the sidestore，sidestore no opened！！！急急急

### Instructions to reproduce

In iOS 18.0.1, the problem can be reproduced by refresh the sidestore

### What version of SideStore are you using?

0.57,0.58,new bate

**Comment by dankozlowski** [comment]
@wangdahua576635956 I'm not associated with this project, but could you give a little more info?  What can't be opened once you refresh the sidestore?  The sidestore app, or the app(s) you've installed with it?

**Comment by wangdahua576635956** [comment]
SideStore app&nbsp;After refreshing, it will crash and cannot be opened

发自我的iPhone


------------------ Original ------------------
From: Dan Kozlowski ***@***.***&gt;
Date: Sat,Oct 12,2024 2:16 AM
To: SideStore/SideStore ***@***.***&gt;
Cc: wangdahua576635956 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [SideStore/SideStore] [BUG]  (Issue #709)





 
@wangdahua576635956 I'm not associated with this project, but could you give a little more info?  What can't be opened once you refresh the sidestore?  The sidestore app, or the app(s) you've installed with it?

**Comment by junepark678** [comment]
this is a support request and not a bug, please use Discord or GitHub Discussions for support.
