### ISSUE TITLE
[BUG] sidestore breaks everytime it is refreshed.

### ISSUE THREAD

**Issue by FilipinoRepo** [SideStore/SideStore#715]
### Describe the bug

whenever I try and refresh sidestore, it just crashes and refuses to open. this is a really annoying bug since i have had to reinstall sidestore around 15 times last week. if there is any solution to this then I would really appreciate it.

### Instructions to reproduce

just refresh sidestore lol

### What version of SideStore are you using?

0.5.8/0.5.9 nightly

**Comment by Creative-Difficulty** [comment]
related to / possible duplicate of #711

**Comment by wangdahua576635956** [comment]
The administrator told me“this is a support request and not a bug, please use Discord or GitHub Discussions for support”, And closed the question.

**Comment by wangdahua576635956** [comment]
The administrator told me“this is a support request and not a bug, please use Discord or GitHub Discussions for support”, And closed the question
