### ISSUE TITLE
Sidestore and other apps pretend to have updated, but they haven't

### ISSUE THREAD

**Issue by bosskratos** [SideStore/SideStore#718]
### Describe the bug

The sidestore itself and other apps seem to be updated, but in App IDs it shows an old update that doesn't correspond to reality

### Instructions to reproduce

https://github.com/user-attachments/assets/80684a6c-20af-4c30-8edc-1a2bf89c293c

https://github.com/user-attachments/assets/48d0fc51-0927-426d-9a4b-ec87c6d98a3f

### What version of SideStore are you using?

0.59

**Comment by bosskratos** [comment]
> App ID is automatically updated. It will not be updated on refresh.
Ok, but sidestore itself after the update still shows 5 days left. Although it should be 7 days

**Comment by bosskratos** [comment]
![IMG_0138](https://github.com/user-attachments/assets/dc885f53-6339-4131-9fdb-6b516e8fe3f7)
After 7 days 😁

**Comment by mahee96** [comment]
@bosskratos @SideStore/project-maintainers  For the “negative hours remaining” bug, please open a new Issue and link it to this for context.

**Comment by mahee96** [comment]
Fix proposed: we can make it say “Expired” instead of showing negative hours
