### ISSUE TITLE
[BUG] Minimuxer fails to create heartbeat

### ISSUE THREAD

**Issue by singlekeycap** [SideStore/SideStore#722]
### Describe the bug

Not sure if this is a known issue already, but I didn't see it in issues. It appears minimuxer is broken on the latest developer betas for iOS 18.1 and 18.2. The debug log is as follows:
```
10:06:26 [INFO] minimuxer::muxer Logger initialized!!
10:06:26 [INFO] minimuxer::muxer minimuxer has started!
10:06:26 [INFO] minimuxer::muxer Starting listener
10:06:26 [INFO] minimuxer::heartbeat Starting heartbeat thread
10:06:29 [ERROR] minimuxer::heartbeat Failed to create heartbeat client: UnknownError
```
This error goes on forever. I have ensured that I am on Wi-Fi and that the VPN is on, and I have waited several minutes without avail.

### Instructions to reproduce

1. Update to iOS 18.1RC (might affect public b5 as well) or 18.2b1
2. Connect to Wi-Fi and WireGuard VPN
3. Launch SideStore
4. Try to install/refresh any app
5. Logs

### What version of SideStore are you using?

5.9.0 (nightly)

### Other info

The developer of Nugget and Nugget Mobile [lemin](https://github.com/leminlimez) apparently knows of this issue already. It also affects Nugget Mobile.

**Comment by Eggslegend** [comment]
Same issue

**Comment by baimour** [comment]
I also had this problem after using CowabungaLite, unable to run bypass

**Comment by mahee96** [comment]
Possibly found the root cause of the issue: **New pairing file is required**

When I had mistakenly unpaired my device in Xcode and then tried to pair it again using USB cable, it got paired in Xcode devices list, however I was using the old pairing file in the device stored in files app. 

So I tried importing the same previously generated pairing file from the files app and ran into the "minimuxer::heartbeat Failed to create heartbeat client: UnknownError" 

So it all boils down to the pairing file if the VPN and WIFI connection are properly enabled. 

NOTE: As others have mentioned, after updating the macOS or iOS on device or Windows(not sure) a new pairing file is expected to be generated using "jitterbugpair" utility if the minimuxer runs into this error.

Try if this works and re-open if these steps doesn't resolve the issue.

**Comment by KieranBLK** [comment]
> Possibly found the root cause of the issue: **New pairing file is required**

I don't believe the pairing file is the root (only) cause. It seemingly stems from CowabungaLite's "Skip Setup" method which Lemin has acknowledged. 

He provided a fix but it doesn't seem to fully fix the problem. 

It appears to not be truly fixable unless the device is fully wiped and set up without any tweaks/modifications. 

Whatever CBL does seems to cause the *selected* file to become corrupted/invalid - maybe certain actions taken on the device causes that as it really appears to be random. Rebooting could also be a trigger, not entirely sure. 

There are times when I run into chronic heartbeat failure and all I do is reset the pairing file in SideStore and apply the same one and it works fine (at least for a while). 

However, minimuxer.. regardless of the paring file being brand new -  will always throw at least 1 heartbeat failure error (for me). It usually succeeds at the 2nd or 3rd attempt. The latter (3rd) being the majority of my experience.

**Comment by baimour** [comment]
> Possibly found the root cause of the issue: **New pairing file is required**
> 
> When I had mistakenly unpaired my device in Xcode and then tried to pair it again using USB cable, it got paired in Xcode devices list, however I was using the old pairing file in the device stored in files app.
> 
> So I tried importing the same previously generated pairing file from the files app and ran into the "minimuxer::heartbeat Failed to create heartbeat client: UnknownError"
> 
> So it all boils down to the pairing file if the VPN and WIFI connection are properly enabled.
> 
> NOTE: As others have mentioned, after updating the macOS or iOS on device or Windows(not sure) a new pairing file is expected to be generated using "jitterbugpair" utility if the minimuxer runs into this error.
> 
> Try if this works and re-open if these steps doesn't resolve the issue.

This has nothing to do with pairfile, and it doesn't help if I generate a new one. I used "Skip Setup" in cowabungalite, which caused the minimuxer to be damaged.

**Comment by basketshoe** [comment]
Used Nugget in the past with "Skip Setup", generating a new pairing file worked for me. Used [idevicepair](https://docs.sidestore.io/docs/installation/pairing-file/) and automatically reinstalled the pairing file after resetting it from SideStore

**Comment by 00scared** [comment]
Still happens for me
