### ISSUE TITLE
[BUG] iOS 18.1 has broken sidestore for me

### ISSUE THREAD

**Issue by Br0des** [SideStore/SideStore#725]
### Describe the bug

After updating I have been getting the "make sure your connected to wifi or wireguard and your pairing file is correct" or whatever and I've done everything possible to fix it

### Instructions to reproduce

- Update to iOS 18.1
- Try and use it after of course new pairing file
- Watch as it gives error
- Try anisette servers, re-login, reinstalling the app, even nightly
- Question Life Choices
- 15 Minutes of regretting updating

### What version of SideStore are you using?

0.5.8

### Other info

Updated to 18.1 yesterday.
Find my is on.

**Comment by Br0des** [comment]
solved

**Comment by polymo1** [comment]
> solved

Its beneficial to the community to explain how.

**Comment by Br0des** [comment]
> > > solved
> > 
> > 
> > Its beneficial to the community to explain how.
> 
> "after restarting my phone the stuff is fixed"

i had restarted it before but yeah it did fix it
