### ISSUE TITLE
[BUG] "The data in not in the correct format"

### ISSUE THREAD

**Issue by aintryuji** [SideStore/SideStore#732]
### Describe the bug

Unable to refresh apps due to the message "The data is not in the correct format".

### Instructions to reproduce

N/A

### What version of SideStore are you using?

0.5.6

**Comment by Cluedo97** [comment]
Yeah same thing here on 0.5.8, hopefully this can be fixed soon.

**Comment by MetalMantis** [comment]
Getting this on 0.5.8 as well, also apps can't UPDATE either.

**Comment by dgorbatko** [comment]
the same, started today. ios 18.1 Iphone 15 pro. Yesterday everything was perfect.

**Comment by darkarmour36** [comment]
> Official server is down, please change Anisette Server to Macley.

How do I do that? sorry I'm new to this
