### ISSUE TITLE
[BUG] Disable App Limit does not work

### ISSUE THREAD

**Issue by dylans509** [SideStore/SideStore#745]
### Describe the bug

I tried to get more than 3 apps and it does not work

https://github.com/user-attachments/assets/e58165f0-bef2-464a-acba-6d40c737af81

![IMG_0284](https://github.com/user-attachments/assets/b0262e25-8076-4d19-b44c-e3457dfbaddc)

### Instructions to reproduce

I try to get another app and it dosent let me sideload another one

### What version of SideStore are you using?

0.5.9

**Comment by polymo1** [comment]
Only works in conjunction with sparsebox

**Comment by dylans509** [comment]
Ok what about my case #744Sent from my iPhoneOn Nov 10, 2024, at 5:04 PM, polymo1 ***@***.***> wrote:﻿
Only works in conjunction with sparsebox
