### ISSUE TITLE
Failed to refresh apps: V3 Error

### ISSUE THREAD

**Issue by AidanNotFunny** [SideStore/SideStore#755]
### Describe the bug

When attempting to refresh apps connected to VPN and school WiFi, I can consistently get the error that it is unable to get data from the annisette server from a V3 server: %@. No idea what that means.

### Instructions to reproduce

Attempt to refresh apps while connected to WiFi and the VPN.

### What version of SideStore are you using?

0.5.8

### Other info

![IMG_5067](https://github.com/user-attachments/assets/619c2d5b-971c-4bbe-9b11-306442e2a344)

**Comment by KieranBLK** [comment]
Very likely means your schools Wi-Fi is blocking the connection to the server. If that's the case - this is not a SideStore issue.

**Comment by HyperrJedi** [comment]
Yeah schools usually block WireGuard connections

**Comment by 0-Blu** [comment]
Use a different anisette server.
