### ISSUE TITLE
[BUG] Unable to log in SideStore

### ISSUE THREAD

**Issue by CodeWorlock** [SideStore/SideStore#761]
### Describe the bug

When i go to confirm my sign in I get this error: Failed to Log In an error occurred when provisioning: %@%@. Please try again. If the issue persists, report it on GitHub Issues!
![Issue_report](https://github.com/user-attachments/assets/c2fc53ab-a327-4ee6-86ef-e5bc1d03de49)

### Instructions to reproduce

Every time i try to log in the app the issue presents itself 

### What version of SideStore are you using?

0.5.8

**Comment by 0-Blu** [comment]
Use a different anisette server.

**Comment by CodeWorlock** [comment]
Fixed! thanks for the help and sorry for if I made you loose time
