### ISSUE TITLE
[BUG] Can not login apple id with self-host anisette server

### ISSUE THREAD

**Issue by lymzzyh** [SideStore/SideStore#767]
### Describe the bug

login process always takes an indefinitely long time.

### Instructions to reproduce

According to the guidance on https://sidestore.io/#get-started, I used AltServer to sideload SideStore, selected the paired mobiledevicepairing file, and attempted to log in using multiple Anisette servers, including a self-hosted server. I also tried switching Apple IDs and repeated the above steps, but the login process always takes an indefinitely long time.

![IMG_5109](https://github.com/user-attachments/assets/5adfb1a7-e085-4bcf-a426-934c9e25276c)

### What version of SideStore are you using?

0.5.8/0.5.7/0.5.9-nightly.2024.11.21.1+66abac8

**Comment by 0-Blu** [comment]
Try the StikTech anisette server.

**Comment by neoarz** [comment]
use alt server to side load side store , **NOT ALTSTORE**. To fix signing in issue change your anisette server to Macley

**Comment by lymzzyh** [comment]
> use alt server to side load side store , **NOT ALTSTORE**. To fix signing in issue change your anisette server to Macley

Sorry, My description was incorrect

**Comment by lymzzyh** [comment]
> Try the StikTech anisette server.

Not Works

**Comment by lymzzyh** [comment]
> 使用 alt 服务器来加载侧边存储，**而不是 ALTSTORE**。要修复登录问题，请将您的 anisette 服务器更改为 Macley

It Works, but why must be Macley?

**Comment by neoarz** [comment]
> > 使用 alt 服务器来加载侧边存储，**而不是 ALTSTORE**。要修复登录问题，请将您的 anisette 服务器更改为 Macley
> 
> It Works, but why must be Macley?

alot of the servers are down at the moment
