### ISSUE TITLE
[BUG] Sidestore asking about app extensions for each refresh

### ISSUE THREAD

**Issue by Aerozolic** [SideStore/SideStore#781]
### Describe the bug

After updating to nightly Sidestore is asking about app extensions on each refresh

### Instructions to reproduce

Refresh Sidestore

### What version of SideStore are you using?

0.5.9-nightly.2024.11.30.1

**Comment by leonardosolari** [comment]
How did you solve this?

**Comment by Aerozolic** [comment]
Chose to remove extensions and after that it didn't ask anymore. Might be related to installing/upgrading downloaded sidestore nightly ipa with sidestore.

**Comment by torma616** [comment]
Can confirm this bug is still active
