### ISSUE TITLE
[错误]The widget disappears

### ISSUE THREAD

**Issue by regitleap** [SideStore/SideStore#790]
### Describe the bug

18.0.1 The widget disappears

### Instructions to reproduce

I hope you can fix the widget problem. At present, I am using the latest 0.5.9 test version. The widget can tell me exactly when to refresh the software to avoid practical results. Thank you.

### What version of SideStore are you using?

0.5.9-nightly.2024.12.08.2+f5b47d0

### Other info

I often pay attention to the update of each version of nightly. It seems that the widget problem has not been fixed.

**Comment by regitleap** [comment]
If my speech hurts you, please forgive me. I don't know English. I'm using a translator. Sorry.

**Comment by mahee96** [comment]
We are aware of the widget issue, please wait as we are working on an even bigger update which will include the widget issues as well.

**Comment by mahee96** [comment]
fixed in nightly
