### ISSUE TITLE
[BUG] Sidestore not working even with vpn and wifi.

### ISSUE THREAD

**Issue by KeYozzy** [SideStore/SideStore#792]
### Describe the bug

So i have followed all the intructions and i had the wiregaurd vpn and wifi on but the problem is that i cannot upload any ipa or whenever i press the plus sign on top left or the refresh, it always says the error vpn/wifi not on. But they both are on. Please help me
![IMG_0281](https://github.com/user-attachments/assets/c3262108-6714-47c4-abc0-191fc33e25c8)
![IMG_0282](https://github.com/user-attachments/assets/37445772-8d53-4aff-99f8-f71ff05bee6e)
!

### Instructions to reproduce

Sidestorenot detecting wifi or vpn.

### What version of SideStore are you using?

SideStore 0.5.8

**Comment by KeYozzy** [comment]
the first shows my vpn is on and the second one is my wifi. Please help me. i really wanted to try this app.

**Comment by hugeBlack** [comment]
Just spam click the add icon until the file browser shows up.

**Comment by KeYozzy** [comment]
no still it doesnt workkk. any other possible ways?

**Comment by KeYozzy** [comment]
omg so it does keep sayign no wifi but when u keep spamming it works. i will have to do that everytme.

**Comment by KeYozzy** [comment]
thank you guys for your support

**Comment by jkcoxson** [comment]
Please join the discord for support. This isn't a support forum.
