### ISSUE TITLE
Expose UI for setting `customAnisetteURL` in settings

### ISSUE THREAD

**Issue by ianclawson** [SideStore/SideStore#86]
From Jawshoeadan on Discord:

> So the only thing we need for settings, is a text box that sets the userdefaults key "customAnisetteURL" to the url entered. preferably it would also check for https:// and make sure it's a valid url before saving, but I could add the checking stuff to the backend

**Comment by jawshoeadan** [comment]
See: https://github.com/jawshoeadan/SideStore/blob/16b263636745ddbf43608fc9fa00020e8ff406cc/AltStore/Operations/FetchAnisetteDataOperation.swift#L35

**Comment by Spidy123222** [comment]
Which settings is this referring to. In app settings tab or in settings app in sidestore's settings?

**Comment by Spidy123222** [comment]
> Could we improve this even further by fetching a list of servers from https://apps.sidestore.io or something, and allow the user to also select from those "verified" servers?

This would be more ideal of a solution.

**Comment by WesleyBryie** [comment]
I know with the original context of the issue, this is completed. 

> > Could we improve this even further by fetching a list of servers from https://apps.sidestore.io or something, and allow the user to also select from those "verified" servers?
> 
> This would be more ideal of a solution.

Is this still something that should be planned for/needs to be worked on?
