### ISSUE TITLE
Remove unnecessarily copied files from build

### ISSUE THREAD

**Issue by jawshoeadan** [SideStore/SideStore#88]
<img width="432" alt="Screen Shot 2022-09-15 at 11 44 48 PM" src="https://user-images.githubusercontent.com/62785552/190558461-6fa1126e-6155-4db2-87a6-e48d4ca0e750.png">
Not too hard to do, although I'm not sure what is needed and what isn't. To solve, go to build phases and delete all of the files in the copy files section. Just adding this issue as a part of our to-do list

**Comment by jkcoxson** [comment]
Yeah that's my bad lol, I threw everything at the wall trying to get an initial build just seeing what stuck.
