### ISSUE TITLE
App id's list is missing

### ISSUE THREAD

**Issue by Spidy123222** [SideStore/SideStore#92]
The list that is normally at bottom of my apps for looking at my appid's is missing in beta mode.
![image](https://user-images.githubusercontent.com/64176728/193997409-990ee2c2-6d38-4324-b5e6-c4c6ed6ce960.jpeg)

![image](https://user-images.githubusercontent.com/64176728/193997464-a579d845-e0da-4964-9935-6d069aa16749.jpeg)

**Comment by jkcoxson** [comment]
It doesn’t show up if you’re not signed in

**Comment by Spidy123222** [comment]
I was signed in btw. This is a bug when beta icon displays. Also makes sources crash.

**Comment by Spidy123222** [comment]
This was solved by removing issues with group ids and beta mode. This issue will be closed now.
